function lesson(data) {
  return data;
}

export const grammarLessons = [
  lesson({
    slug: "be-present",
    title: "Be 动词与一般现在时",
    titleEn: "Be & Present Simple",
    emoji: "🧱",
    stage: "A1",
    summary: "先把 I am / You are / It is 说顺，再谈每天发生的事。",
    points: [
      "I am, you are, he/she/it is, we/they are。",
      "一般现在时表示习惯、事实：I eat vegetables every day.",
      "第三人称单数动词加 -s / -es：She likes carrots. He goes to work.",
      "否定：I/you/we/they don't；he/she/it doesn't + 原形。",
      "疑问：Do you…? / Does she…? 回答用 Yes, I do. / No, she doesn't.",
    ],
    examples: [
      { en: "I am a student.", zh: "我是学生。", highlight: "am" },
      { en: "She likes tomato soup.", zh: "她喜欢番茄汤。", highlight: "likes" },
      { en: "They don't take a taxi.", zh: "他们不打车。", highlight: "don't" },
      { en: "Does he work here?", zh: "他在这里工作吗？", highlight: "Does" },
    ],
    quizzes: [
      { question: "He ____ at the hotel.", options: ["am", "is", "are", "be"], answer: 1, explain: "he 配 is。" },
      { question: "She ____ bananas.", options: ["like", "likes", "liking", "liked"], answer: 1, explain: "第三人称单数 likes。" },
      { question: "I ____ eat spicy food.", options: ["doesn't", "don't", "isn't", "aren't"], answer: 1, explain: "I 的否定用 don't。" },
      { question: "____ they live near the beach?", options: ["Does", "Do", "Are", "Is"], answer: 1, explain: "they 用 Do。" },
      { question: "The shop ____ at 9 a.m.", options: ["open", "opens", "opening", "opened"], answer: 1, explain: "第三人称单数 opens。" },
      { question: "We ____ students.", options: ["is", "am", "are", "be"], answer: 2, explain: "we 配 are。" },
    ],
  }),
  lesson({
    slug: "articles",
    title: "冠词 a / an / the",
    titleEn: "Articles",
    emoji: "🅰️",
    stage: "A1",
    summary: "第一次提到用 a/an，双方都知道是哪一个时用 the。",
    points: [
      "a 用在辅音音素开头：a carrot, a university（/j/ 是辅音）。",
      "an 用在元音音素开头：an apple, an hour（h 不发音）。",
      "the 表示特指：the menu on the table。",
      "不可数名词常不加 a：water, luggage, information。",
      "独一无二的事物用 the：the sun, the airport（双方都知道的那个）。",
    ],
    examples: [
      { en: "I'd like an apple.", zh: "我想要一个苹果。", highlight: "an" },
      { en: "The waiter is coming.", zh: "那位服务员过来了。", highlight: "The" },
      { en: "Can I have water?", zh: "可以给我水吗？", highlight: "water" },
      { en: "She is an honest person.", zh: "她是个诚实的人。", highlight: "an" },
    ],
    quizzes: [
      { question: "____ orange, please.", options: ["A", "An", "Thes", "Some a"], answer: 1, explain: "orange 以元音音素开头，用 an。" },
      { question: "Please show me ____ menu.", options: ["a", "an", "the", "any a"], answer: 2, explain: "双方都知道是哪份菜单，用 the。" },
      { question: "luggage 前面通常不用 a，因为？", options: ["它是动词", "它不可数", "它是人名", "它是过去时"], answer: 1, explain: "luggage 是不可数名词。" },
      { question: "I need ____ hour to pack.", options: ["a", "an", "thes", "one a"], answer: 1, explain: "hour 的 h 不发音，用 an。" },
      { question: "____ sun is very strong today.", options: ["A", "An", "The", "—"], answer: 2, explain: "独一无二用 the。" },
      { question: "She is ____ university student.", options: ["a", "an", "the", "—"], answer: 0, explain: "university 以 /j/ 开头，用 a。" },
    ],
  }),
  lesson({
    slug: "prepositions",
    title: "介词 in / on / at",
    titleEn: "Prepositions of Place & Time",
    emoji: "📍",
    stage: "A1",
    summary: "时间地点介词最容易混，用「大地方 in、表面 on、点 at」来记。",
    points: [
      "at：具体的点。at the airport, at 10:30, at night。",
      "in：范围里。in the hotel, in the morning, in July, in 2024。",
      "on：表面上或日期。on the beach, on Monday, on the third floor。",
      "交通：on a bus/train/plane；in a car/taxi。",
      "固定搭配整块记：at the gate, at home, in bed, on time。",
    ],
    examples: [
      { en: "Meet me at the airport.", zh: "机场见。", highlight: "at" },
      { en: "The room is on the third floor.", zh: "房间在三楼。", highlight: "on" },
      { en: "We swim in the morning.", zh: "我们早上游泳。", highlight: "in" },
      { en: "She goes to work on a train.", zh: "她坐火车上班。", highlight: "on" },
    ],
    quizzes: [
      { question: "I am ____ the hotel lobby.", options: ["on", "in", "at to", "by the"], answer: 1, explain: "lobby 是空间内部，用 in。" },
      { question: "The plane leaves ____ 9 a.m.", options: ["on", "in", "at", "to"], answer: 2, explain: "具体钟点用 at。" },
      { question: "Let's walk ____ the beach.", options: ["on", "in", "at", "into of"], answer: 0, explain: "在沙滩表面上用 on。" },
      { question: "I was born ____ 1998.", options: ["at", "on", "in", "to"], answer: 2, explain: "年份用 in。" },
      { question: "See you ____ Monday.", options: ["in", "on", "at", "by the"], answer: 1, explain: "星期用 on。" },
      { question: "He is sitting ____ a taxi.", options: ["on", "in", "at", "to"], answer: 1, explain: "小轿车里用 in。" },
    ],
  }),
  lesson({
    slug: "there-be",
    title: "There be 句型",
    titleEn: "There is / There are",
    emoji: "📦",
    stage: "A1",
    summary: "先说「有没有」，再说东西在哪。就近原则看后面第一个名词。",
    points: [
      "单数/不可数：There is a ticket. There is some water.",
      "复数：There are two gates.",
      "就近原则：There is a book and two pens.",
      "否定：There isn't / There aren't。",
      "疑问：Is there a vacancy? Are there any seats?",
    ],
    examples: [
      { en: "There is a shop behind you.", zh: "你身后有一家店。", highlight: "There is" },
      { en: "There are many fish in the lake.", zh: "湖里有很多鱼。", highlight: "There are" },
      { en: "Is there a double room available?", zh: "还有双人房吗？", highlight: "Is there" },
      { en: "There isn't any wifi in the room.", zh: "房间里没有无线网。", highlight: "isn't" },
    ],
    quizzes: [
      { question: "____ a reservation under Chen.", options: ["There are", "There is", "There be", "They is"], answer: 1, explain: "a reservation 是单数，用 There is。" },
      { question: "____ two chairs on the beach.", options: ["There is", "There are", "There be", "It are"], answer: 1, explain: "two chairs 复数用 There are。" },
      { question: "____ any milk in the fridge?", options: ["Is there", "Are there", "There is", "Do there"], answer: 0, explain: "milk 不可数，疑问用 Is there。" },
      { question: "There ____ a bag and two tickets.", options: ["are", "is", "be", "have"], answer: 1, explain: "就近原则，靠近动词的是 a bag。" },
      { question: "There aren't ____ seats left.", options: ["some", "any", "a", "the"], answer: 1, explain: "否定句常用 any。" },
      { question: "正确的是？", options: ["Has a shop here", "There has a shop", "There is a shop here", "It have a shop"], answer: 2, explain: "英语用 There is 表示某处有某物。" },
    ],
  }),
  lesson({
    slug: "countable",
    title: "可数与不可数名词",
    titleEn: "Countable & Uncountable",
    emoji: "🧮",
    stage: "A2",
    summary: "能数的加 a/复数；不能数的用 some、a piece of。",
    points: [
      "可数：a ticket, two tickets；不可数：luggage, water, advice, information。",
      "many / few 修饰可数；much / little 修饰不可数。",
      "some 用于肯定；any 常用于否定和疑问。",
      "量词：a piece of advice, a bottle of water, a loaf of bread。",
      "有的词两种都可：coffee（物质）/ a coffee（一杯）。",
    ],
    examples: [
      { en: "How many tickets do you need?", zh: "你需要几张票？", highlight: "many tickets" },
      { en: "How much luggage do you have?", zh: "你有多少行李？", highlight: "much luggage" },
      { en: "I need some information.", zh: "我需要一些信息。", highlight: "information" },
      { en: "Can I have a coffee, please?", zh: "请来一杯咖啡。", highlight: "a coffee" },
    ],
    quizzes: [
      { question: "How ____ water do you want?", options: ["many", "much", "few", "a"], answer: 1, explain: "water 不可数用 much。" },
      { question: "There aren't ____ chairs.", options: ["much", "little", "many", "a little"], answer: 2, explain: "chairs 可数复数用 many。" },
      { question: "advice 前面不能直接加 a，应说：", options: ["an advice", "a piece of advice", "advices", "one advice"], answer: 1, explain: "advice 不可数，用量词 a piece of。" },
      { question: "I don't have ____ money.", options: ["some", "any", "many", "a few"], answer: 1, explain: "否定句用 any。" },
      { question: "We need ____ bread.", options: ["a", "an", "some", "many"], answer: 2, explain: "bread 不可数，用 some。" },
      { question: "There are only ____ seats left.", options: ["a little", "little", "a few", "much"], answer: 2, explain: "seats 可数，少量用 a few。" },
    ],
  }),
  lesson({
    slug: "past-simple",
    title: "一般过去时",
    titleEn: "Past Simple",
    emoji: "⏪",
    stage: "A2",
    summary: "说昨天发生的事：动词变成过去式，否定用 didn't。",
    points: [
      "规则动词加 -ed：walked, stayed, packed。",
      "不规则要单记：go→went, eat→ate, take→took, see→saw, buy→bought。",
      "否定：didn't + 原形。I didn't check in yesterday.",
      "疑问：Did you order soup? Yes, I did.",
      "时间标志：yesterday, last week, in 2019, two days ago。",
    ],
    examples: [
      { en: "I went to the airport yesterday.", zh: "我昨天去了机场。", highlight: "went" },
      { en: "She didn't like the spicy dish.", zh: "她不喜欢那道辣菜。", highlight: "didn't like" },
      { en: "Did you pack sunscreen?", zh: "你带防晒霜了吗？", highlight: "Did" },
      { en: "We stayed at a quiet hotel.", zh: "我们住在安静的酒店。", highlight: "stayed" },
    ],
    quizzes: [
      { question: "Yesterday I ____ a taxi.", options: ["take", "took", "taken", "taking"], answer: 1, explain: "take 的过去式是 took。" },
      { question: "He ____ check out at 11.", options: ["didn't", "doesn't", "don't", "isn't"], answer: 0, explain: "过去否定用 didn't + 原形。" },
      { question: "____ you swim in the sea?", options: ["Do", "Does", "Did", "Are"], answer: 2, explain: "问过去的事情用 Did。" },
      { question: "She ____ a souvenir last night.", options: ["buy", "buys", "bought", "buying"], answer: 2, explain: "buy 的过去式 bought。" },
      { question: "They didn't ____ the key.", options: ["returned", "return", "returning", "returns"], answer: 1, explain: "didn't 后用原形。" },
      { question: "I ____ him two days ago.", options: ["see", "seen", "saw", "seeing"], answer: 2, explain: "ago 搭配一般过去时 saw。" },
    ],
  }),
  lesson({
    slug: "present-continuous",
    title: "现在进行时",
    titleEn: "Present Continuous",
    emoji: "▶️",
    stage: "A2",
    summary: "正在发生：am/is/are + doing。点餐、排队、登机都能用。",
    points: [
      "结构：am / is / are + 动词-ing。",
      "此刻正在做：I am waiting at the gate.",
      "也可表近期安排：I am flying tomorrow.",
      "状态动词一般不用进行时：know, like, want, believe, have（拥有）。",
      "拼写：make→making；sit→sitting；lie→lying。",
    ],
    examples: [
      { en: "The waiter is coming.", zh: "服务员正在过来。", highlight: "is coming" },
      { en: "We are staying at a beach hotel.", zh: "我们住在海边酒店。", highlight: "are staying" },
      { en: "I am unpacking my luggage.", zh: "我正在打开行李。", highlight: "am unpacking" },
      { en: "She is meeting the client at 3.", zh: "她三点见客户。", highlight: "is meeting" },
    ],
    quizzes: [
      { question: "She ____ boarding now.", options: ["is", "are", "am", "be"], answer: 0, explain: "she 配 is。" },
      { question: "They ____ waiting at the gate.", options: ["is", "are", "am", "be"], answer: 1, explain: "they 配 are。" },
      { question: "正确的是？", options: ["I am want water", "I wanting water", "I want water", "I is want water"], answer: 2, explain: "want 是状态动词，用一般现在时。" },
      { question: "Look! It ____.", options: ["rains", "is raining", "rained", "rain"], answer: 1, explain: "Look! 提示此刻正在发生。" },
      { question: "I ____ my keys. Have you seen them?", options: ["look for", "am looking for", "looked", "looks for"], answer: 1, explain: "正在找，用进行时。" },
      { question: "He ____ the answer.", options: ["is knowing", "knows", "knowing", "know"], answer: 1, explain: "know 不用进行时。" },
    ],
  }),
  lesson({
    slug: "future",
    title: "一般将来时 will / going to",
    titleEn: "Future: will & going to",
    emoji: "⏩",
    stage: "A2",
    summary: "临时决定和预测用 will；事先计划用 be going to。",
    points: [
      "will + 原形：I'll take a taxi.（说话时才决定）",
      "be going to + 原形：I'm going to stay three nights.（已有打算）",
      "will 也表预测：It will rain tomorrow.",
      "going to 也可根据眼前证据预测：Look at those clouds. It's going to rain.",
      "否定：won't / am not going to。疑问：Will you…? / Are you going to…?",
    ],
    examples: [
      { en: "I'll have the tomato soup.", zh: "我要番茄汤。", highlight: "I'll have" },
      { en: "We are going to visit the beach tomorrow.", zh: "我们明天打算去海边。", highlight: "are going to" },
      { en: "It will be crowded at the airport.", zh: "机场会很挤。", highlight: "will be" },
      { en: "I'm not going to check out late.", zh: "我不打算晚点退房。", highlight: "not going to" },
    ],
    quizzes: [
      { question: "（看菜单后临时决定）I ____ the salad.", options: ["am going have", "will have", "having", "have going"], answer: 1, explain: "临时决定用 will。" },
      { question: "We ____ fly to London next week. The tickets are booked.", options: ["will", "are going to", "going", "wills"], answer: 1, explain: "已经订票，是事先计划，用 going to。" },
      { question: "Look at the waves. It ____ dangerous.", options: ["will to be", "is going to be", "going be", "is will"], answer: 1, explain: "眼前证据用 going to。" },
      { question: "She ____ call you later.", options: ["will", "wills", "going", "is will"], answer: 0, explain: "will + 原形。" },
      { question: "I ____ stay. I just decided.", options: ["am going to", "'ll", "going", "wills"], answer: 1, explain: "刚决定用 'll / will。" },
      { question: "They ____ not going to wait.", options: ["is", "are", "will", "do"], answer: 1, explain: "they are going to 的否定。" },
    ],
  }),
  lesson({
    slug: "comparatives",
    title: "比较级与最高级",
    titleEn: "Comparatives & Superlatives",
    emoji: "📊",
    stage: "A2",
    summary: "两者比用 -er / more；三者以上用 the -est / the most。",
    points: [
      "短词：tall → taller → the tallest；big → bigger。",
      "长词：expensive → more expensive → the most expensive。",
      "不规则：good/better/best；bad/worse/worst；far/further。",
      "同级比较：as…as。This room is as quiet as that one.",
      "比较级后常用 than：A quieter room is better than this one.",
    ],
    examples: [
      { en: "I'd like a quieter room.", zh: "我想要更安静的房间。", highlight: "quieter" },
      { en: "This hotel is more expensive than that one.", zh: "这家酒店比那家贵。", highlight: "more expensive" },
      { en: "It is the best beach in town.", zh: "这是镇上最好的海滩。", highlight: "the best" },
      { en: "The train is as fast as the bus today.", zh: "今天火车和公交一样快。", highlight: "as fast as" },
    ],
    quizzes: [
      { question: "This bag is ____ than that one.", options: ["heavy", "heavier", "heaviest", "more heavy"], answer: 1, explain: "短词比较级 heavier。" },
      { question: "This is ____ room in the hotel.", options: ["quieter", "the quietest", "more quiet", "quietest the"], answer: 1, explain: "最高级前面加 the。" },
      { question: "The flight is ____ than I expected.", options: ["more cheaper", "cheaper", "cheap", "cheapest"], answer: 1, explain: "cheap 的比较级是 cheaper，不加 more。" },
      { question: "She is ____ student in the class.", options: ["better", "the best", "more good", "best the"], answer: 1, explain: "good 的最高级 the best。" },
      { question: "This soup is ____ that one.", options: ["as spicy as", "spicy as", "so spicy", "as spicy"], answer: 0, explain: "同级比较 as…as。" },
      { question: "Today is ____ than yesterday.", options: ["more hot", "hotter", "hottest", "the hotter"], answer: 1, explain: "hot → hotter。" },
    ],
  }),
  lesson({
    slug: "modals",
    title: "情态动词 can / should / must / may",
    titleEn: "Modals",
    emoji: "🎯",
    stage: "B1",
    summary: "表达能力、建议、必须和可能，旅行里特别常用。",
    points: [
      "can：能力或请求。Can you help me?",
      "could：更礼貌的请求，或过去的能力。Could I have the bill?",
      "should：建议。You should wear sunscreen.",
      "must：必须（说话人认为）。You must show your passport.",
      "have to：客观要求。You have to check in before 10.",
      "may / might：可能。It may rain. May I sit here?（许可）",
      "后面都接动词原形。否定：can't, shouldn't, mustn't, don't have to（不必）。",
    ],
    examples: [
      { en: "Can I have a window seat?", zh: "我可以要靠窗座位吗？", highlight: "Can" },
      { en: "You should stay near the shore.", zh: "你最好待在岸边。", highlight: "should" },
      { en: "You must prepare your passport.", zh: "你必须准备好护照。", highlight: "must" },
      { en: "You don't have to tip, but you can.", zh: "你可以不给小费，但给也可以。", highlight: "don't have to" },
    ],
    quizzes: [
      { question: "礼貌请求用？", options: ["Must I water?", "Can I have water, please?", "I should water?", "I musting water"], answer: 1, explain: "Can I have ... please? 是礼貌请求。" },
      { question: "提出建议用？", options: ["can", "should", "am", "the"], answer: 1, explain: "should 表示建议。" },
      { question: "You must ____ your ticket.", options: ["shows", "showing", "show", "showed"], answer: 2, explain: "情态动词后用原形。" },
      { question: "You ____ show ID. It's a rule.", options: ["can", "have to", "should maybe", "might"], answer: 1, explain: "规定要求用 have to。" },
      { question: "You ____ wait. It's optional.", options: ["mustn't", "don't have to", "can't to", "should not to"], answer: 1, explain: "don't have to = 不必。" },
      { question: "It ____ rain later, I'm not sure.", options: ["must to", "might", "should must", "can to"], answer: 1, explain: "不确定的可能用 might。" },
    ],
  }),
  lesson({
    slug: "present-perfect",
    title: "现在完成时",
    titleEn: "Present Perfect",
    emoji: "✅",
    stage: "B1",
    summary: "过去发生、和现在有关：have/has + 过去分词。",
    points: [
      "结构：have/has + done。I have booked a room.",
      "already / yet / just / ever / never 常一起出现。",
      "for + 一段时间；since + 起点。I have lived here for two years / since 2022.",
      "和一般过去时的差别：现在完成不说具体过去时间；yesterday 要用过去时。",
      "不规则分词：go-went-gone, see-saw-seen, write-wrote-written。",
    ],
    examples: [
      { en: "I have already checked in.", zh: "我已经办理入住了。", highlight: "have already checked" },
      { en: "Have you ever been to London?", zh: "你去过伦敦吗？", highlight: "Have you ever been" },
      { en: "She has lived here since 2020.", zh: "她从 2020 年起住在这里。", highlight: "has lived since" },
      { en: "I went there yesterday. (不能用 have gone + yesterday)", zh: "我昨天去的。", highlight: "went yesterday" },
    ],
    quizzes: [
      { question: "I ____ already packed.", options: ["have", "has", "had to have", "am"], answer: 0, explain: "I have + 过去分词。" },
      { question: "She ____ never eaten sushi.", options: ["have", "has", "is", "does"], answer: 1, explain: "she has。" },
      { question: "____ you finished the form yet?", options: ["Do", "Did", "Have", "Has"], answer: 2, explain: "you 用 Have。" },
      { question: "We have lived here ____ 2019.", options: ["for", "since", "ago", "in the"], answer: 1, explain: "since + 起点。" },
      { question: "I ____ him yesterday.", options: ["have seen", "saw", "seen", "have saw"], answer: 1, explain: "yesterday 用一般过去时。" },
      { question: "They haven't arrived ____.", options: ["already", "ever", "yet", "since"], answer: 2, explain: "否定句常用 yet。" },
    ],
  }),
  lesson({
    slug: "past-continuous",
    title: "过去进行时",
    titleEn: "Past Continuous",
    emoji: "⏯️",
    stage: "B1",
    summary: "过去某一刻正在做：was/were + doing，常和 when 搭配。",
    points: [
      "结构：was/were + doing。I was waiting at the gate.",
      "背景动作 + 打断：I was having dinner when he called.",
      "同时发生：While she was packing, I was checking emails.",
      "I/he/she/it was；you/we/they were。",
      "故事开头常用进行时铺背景。",
    ],
    examples: [
      { en: "I was waiting when the announcement started.", zh: "广播开始时我正在等。", highlight: "was waiting" },
      { en: "They were swimming at 4 p.m.", zh: "下午四点他们在游泳。", highlight: "were swimming" },
      { en: "While I was unpacking, the wifi failed.", zh: "我打开行李时网断了。", highlight: "was unpacking" },
      { en: "What were you doing at 8?", zh: "八点你在做什么？", highlight: "were you doing" },
    ],
    quizzes: [
      { question: "I ____ reading when she arrived.", options: ["am", "was", "were", "been"], answer: 1, explain: "I was + doing。" },
      { question: "They ____ having lunch at noon.", options: ["was", "were", "are", "been"], answer: 1, explain: "they were。" },
      { question: "He called while I ____.", options: ["cooked", "was cooking", "cook", "have cooked"], answer: 1, explain: "while 引导正在进行的背景。" },
      { question: "What ____ you doing at that time?", options: ["was", "were", "are", "did"], answer: 1, explain: "you were doing。" },
      { question: "She ____ not sleeping. She was working.", options: ["were", "was", "is", "did"], answer: 1, explain: "she was not。" },
      { question: "We ____ to the hotel when it started to rain.", options: ["walked", "were walking", "walk", "have walked"], answer: 1, explain: "下雨打断了正在走的动作。" },
    ],
  }),
  lesson({
    slug: "passive",
    title: "被动语态",
    titleEn: "Passive Voice",
    emoji: "🔄",
    stage: "B1",
    summary: "不知道谁做的、或更关心结果时用 be + 过去分词。",
    points: [
      "一般现在：is/are + done。Breakfast is included.",
      "一般过去：was/were + done。The room was cleaned.",
      "现在完成：has/have been + done。The bags have been checked.",
      "情态：must be shown, can be recycled。",
      "by 引出执行者：The hotel was designed by a local architect.",
    ],
    examples: [
      { en: "Breakfast is included.", zh: "含早餐。", highlight: "is included" },
      { en: "Your luggage was weighed.", zh: "行李称过了。", highlight: "was weighed" },
      { en: "Passports must be shown at the gate.", zh: "登机口必须出示护照。", highlight: "must be shown" },
      { en: "The room has been cleaned.", zh: "房间已经打扫过了。", highlight: "has been cleaned" },
    ],
    quizzes: [
      { question: "The bill ____ paid yesterday.", options: ["is", "was", "were", "been"], answer: 1, explain: "yesterday 用过去被动 was paid。" },
      { question: "Tickets ____ sold online.", options: ["is", "are", "was", "been"], answer: 1, explain: "tickets 复数 are sold。" },
      { question: "The form must ____ signed.", options: ["be", "been", "being", "is"], answer: 0, explain: "情态 + be + 过去分词。" },
      { question: "The bags have ____ checked.", options: ["be", "been", "being", "was"], answer: 1, explain: "现在完成被动 have been done。" },
      { question: "English ____ spoken here.", options: ["is", "are", "was being", "have"], answer: 0, explain: "English 视为单数 is spoken。" },
      { question: "The hotel ____ built in 1998.", options: ["is", "was", "has", "were"], answer: 1, explain: "1998 年发生，用 was built。" },
    ],
  }),
  lesson({
    slug: "conditionals",
    title: "条件句 If",
    titleEn: "Conditionals",
    emoji: "🔀",
    stage: "B1",
    summary: "真实条件用 If + 现在，will；虚拟现在用 If + 过去，would。",
    points: [
      "零类：If you heat ice, it melts.（真理）",
      "一类：If it rains, we will stay in.（可能发生）",
      "二类：If I had more time, I would walk.（现在不真实）",
      "If 从句用现在时，主句 will；不要 If it will rain。",
      "unless = if not。Unless you hurry, you will miss the gate.",
    ],
    examples: [
      { en: "If the waves are big, you shouldn't swim far.", zh: "浪大就别游远。", highlight: "If … shouldn't" },
      { en: "If I am late, I will call you.", zh: "如果我迟到，会给你打电话。", highlight: "If … will" },
      { en: "If I were you, I would take a taxi.", zh: "我要是你，就打车。", highlight: "If I were" },
      { en: "Unless you book now, there will be no rooms.", zh: "现在不订就没房了。", highlight: "Unless" },
    ],
    quizzes: [
      { question: "If it ____, we will stay in.", options: ["will rain", "rains", "rained", "raining"], answer: 1, explain: "一类条件从句用现在时 rains。" },
      { question: "If I ____ you, I would wait.", options: ["am", "was being", "were", "be"], answer: 2, explain: "虚拟用 If I were you。" },
      { question: "If she studied more, she ____ pass.", options: ["will", "would", "would to", "passes"], answer: 1, explain: "二类主句用 would。" },
      { question: "____ you hurry, you will miss it.", options: ["If not", "Unless", "When not", "Without if"], answer: 1, explain: "unless = if not。" },
      { question: "If you heat water to 100°C, it ____.", options: ["will boiling", "boils", "boiled", "would boil always"], answer: 1, explain: "零类用现在时 boils。" },
      { question: "If I ____ enough money, I would fly business.", options: ["have", "had", "will have", "has"], answer: 1, explain: "二类从句用过去式 had。" },
    ],
  }),
  lesson({
    slug: "relative-clauses",
    title: "定语从句 who / which / that",
    titleEn: "Relative Clauses",
    emoji: "🔗",
    stage: "B1",
    summary: "用从句给名词加信息：人用 who，物用 which，that 常可通用。",
    points: [
      "人：the waiter who served us。",
      "物：the room which / that faces the sea。",
      "地点：the hotel where we stayed。",
      "所有：the guest whose bag is missing。",
      "作宾语时可省略：the book (that) I bought。",
    ],
    examples: [
      { en: "This is the gate that we need.", zh: "这就是我们要去的登机口。", highlight: "that" },
      { en: "The woman who called is the receptionist.", zh: "打电话的是前台。", highlight: "who" },
      { en: "The hotel where we stayed was quiet.", zh: "我们住的酒店很安静。", highlight: "where" },
      { en: "The man whose passport was lost is at the desk.", zh: "护照丢了的那个人在柜台。", highlight: "whose" },
    ],
    quizzes: [
      { question: "The staff ____ helped me were kind.", options: ["which", "who", "where", "whose"], answer: 1, explain: "人用 who。" },
      { question: "This is the bag ____ I lost.", options: ["who", "where", "that", "whose"], answer: 2, explain: "物用 that/which。" },
      { question: "The city ____ I was born is small.", options: ["who", "which", "where", "whose"], answer: 2, explain: "地点用 where。" },
      { question: "The guest ____ room is 305 called.", options: ["who", "which", "where", "whose"], answer: 3, explain: "whose 表示所属。" },
      { question: "I like the soup ____ you recommended.", options: ["who", "that", "where", "whose"], answer: 1, explain: "物作宾语用 that，也可省略。" },
      { question: "People ____ live here are friendly.", options: ["which", "who", "where", "whose"], answer: 1, explain: "人作主语用 who。" },
    ],
  }),
  lesson({
    slug: "gerund-infinitive",
    title: "动名词与不定式",
    titleEn: "Gerunds & Infinitives",
    emoji: "🧩",
    stage: "B1",
    summary: "有的动词后接 doing，有的接 to do，要成组记。",
    points: [
      "enjoy / finish / avoid / mind / keep + doing。",
      "want / decide / hope / plan / refuse + to do。",
      "like / start 两者都可：I like swimming / to swim。",
      "stop doing = 停下正在做的；stop to do = 停下来去做另一件事。",
      "介词后用 doing：good at swimming, look forward to seeing you。（to 在这里是介词）",
    ],
    examples: [
      { en: "I enjoy walking on the beach.", zh: "我喜欢在沙滩上散步。", highlight: "enjoy walking" },
      { en: "We decided to stay one more night.", zh: "我们决定再住一晚。", highlight: "decided to stay" },
      { en: "She stopped to buy water.", zh: "她停下来去买水。", highlight: "stopped to buy" },
      { en: "I look forward to seeing you.", zh: "我期待见到你。", highlight: "to seeing" },
    ],
    quizzes: [
      { question: "I enjoy ____ by the sea.", options: ["walk", "to walking", "walking", "walked"], answer: 2, explain: "enjoy + doing。" },
      { question: "They decided ____ later.", options: ["leaving", "to leave", "leave", "left"], answer: 1, explain: "decide + to do。" },
      { question: "Would you mind ____ the window?", options: ["open", "to open", "opening", "opened"], answer: 2, explain: "mind + doing。" },
      { question: "He stopped ____ a photo. Then he walked on.", options: ["taking", "to take", "take", "took"], answer: 1, explain: "停下来去做另一件事，用 to take。" },
      { question: "I'm good at ____ maps.", options: ["read", "to read", "reading", "reads"], answer: 2, explain: "介词 at 后用 doing。" },
      { question: "We hope ____ you soon.", options: ["seeing", "to see", "see", "saw"], answer: 1, explain: "hope + to do。" },
    ],
  }),
  lesson({
    slug: "reported-speech",
    title: "间接引语",
    titleEn: "Reported Speech",
    emoji: "💬",
    stage: "B2",
    summary: "转述别人的话：时态通常往后推一格，人称也要变。",
    points: [
      "He said, \"I am tired.\" → He said (that) he was tired.",
      "现在 → 过去；过去 → 过去完成；will → would；can → could。",
      "said to sb → told sb。He told me he had a reservation.",
      "问句用 if / whether 或原疑问词：She asked if the wifi worked.",
      "时间词：today→that day, tomorrow→the next day, yesterday→the day before。",
    ],
    examples: [
      { en: "She said she had a reservation.", zh: "她说她有预订。", highlight: "said she had" },
      { en: "He told me the gate was 18.", zh: "他告诉我登机口是 18。", highlight: "told me" },
      { en: "They asked if breakfast was included.", zh: "他们问含不含早餐。", highlight: "asked if" },
      { en: "She said she would call the next day.", zh: "她说第二天会打电话。", highlight: "would … the next day" },
    ],
    quizzes: [
      { question: "He said, \"I am late.\" → He said he ____ late.", options: ["is", "was", "were", "been"], answer: 1, explain: "现在变成过去 was。" },
      { question: "She said, \"I will wait.\" → She said she ____ wait.", options: ["will", "would", "can", "is"], answer: 1, explain: "will → would。" },
      { question: "He ____ me the wifi password.", options: ["said", "told", "says to", "told to"], answer: 1, explain: "told sb 不接 to。" },
      { question: "She asked ____ the room was ready.", options: ["that", "if", "what", "to"], answer: 1, explain: "一般疑问转述用 if/whether。" },
      { question: "\"Can you help?\" → He asked if I ____ help.", options: ["can", "could", "will", "may"], answer: 1, explain: "can → could。" },
      { question: "\"I saw her yesterday.\" → He said he had seen her ____.", options: ["yesterday", "the day before", "tomorrow", "today"], answer: 1, explain: "yesterday → the day before。" },
    ],
  }),
  lesson({
    slug: "used-to",
    title: "used to / be used to",
    titleEn: "Used to vs Be used to",
    emoji: "🕰️",
    stage: "B2",
    summary: "used to do 是过去习惯；be used to doing 是习惯于。",
    points: [
      "used to + 原形：过去常常，现在不再。I used to take a taxi every day.",
      "否定：didn't use to；疑问：Did you use to…?",
      "be used to + 名词/doing：习惯于。I am used to the noise.",
      "get used to doing：逐渐习惯。You will get used to the jet lag.",
      "不要把 used to do 和 be used to doing 混在一起。",
    ],
    examples: [
      { en: "I used to live near the airport.", zh: "我以前住在机场附近。", highlight: "used to live" },
      { en: "I am used to getting up early.", zh: "我习惯早起。", highlight: "am used to getting" },
      { en: "Did you use to work here?", zh: "你以前在这里工作吗？", highlight: "Did you use to" },
      { en: "You'll get used to the spicy food.", zh: "你会习惯辣的。", highlight: "get used to" },
    ],
    quizzes: [
      { question: "I ____ play tennis, but I don't now.", options: ["am used to", "used to", "use to", "using to"], answer: 1, explain: "过去习惯用 used to。" },
      { question: "She is used to ____ in a crowded city.", options: ["live", "living", "lived", "lives"], answer: 1, explain: "be used to + doing。" },
      { question: "____ you use to take this bus?", options: ["Do", "Did", "Are", "Have"], answer: 1, explain: "Did you use to…?" },
      { question: "I am getting used to ____ on the left.", options: ["drive", "driving", "drove", "driven"], answer: 1, explain: "get used to doing。" },
      { question: "He didn't ____ drink coffee.", options: ["used to", "use to", "using to", "uses to"], answer: 1, explain: "否定 didn't use to。" },
      { question: "正确表示「我现在习惯加班」：", options: ["I used to overtime", "I am used to working overtime", "I use to work overtime", "I used working overtime"], answer: 1, explain: "be used to doing。" },
    ],
  }),
  lesson({
    slug: "agreement",
    title: "主谓一致",
    titleEn: "Subject-Verb Agreement",
    emoji: "⚖️",
    stage: "B1",
    summary: "主语单复数决定动词形式，就近和意义一致都要会。",
    points: [
      "单数主语 + 单数动词：The news is good.（news 形式上复数，意义上单数）",
      "复数主语 + 复数动词：The staff are helpful.（英式里 staff 常作复数）",
      "A and B → 复数；A or B / either…or 就近。",
      "each / everyone / somebody + 单数动词。",
      "a number of + 复数；the number of + 单数。",
    ],
    examples: [
      { en: "The news is on at nine.", zh: "九点有新闻。", highlight: "is" },
      { en: "Everybody has a ticket.", zh: "每个人都有票。", highlight: "has" },
      { en: "Either the manager or the staff are coming.", zh: "经理或员工会来。", highlight: "are" },
      { en: "The number of rooms is limited.", zh: "房间数量有限。", highlight: "is" },
    ],
    quizzes: [
      { question: "The information ____ useful.", options: ["are", "is", "were", "have"], answer: 1, explain: "information 不可数，用 is。" },
      { question: "Everybody ____ ready.", options: ["are", "is", "have", "were"], answer: 1, explain: "everybody 作单数。" },
      { question: "A number of guests ____ waiting.", options: ["is", "are", "has", "was"], answer: 1, explain: "a number of + 复数动词。" },
      { question: "The number of flights ____ small.", options: ["are", "is", "have", "were"], answer: 1, explain: "the number of + 单数。" },
      { question: "There ____ some luggage by the door.", options: ["are", "is", "have", "were"], answer: 1, explain: "luggage 不可数用 is。" },
      { question: "Tom and Jerry ____ at the gate.", options: ["is", "are", "has", "was"], answer: 1, explain: "A and B 用复数。" },
    ],
  }),
  lesson({
    slug: "so-such-too",
    title: "so / such / too / enough",
    titleEn: "So, Such, Too, Enough",
    emoji: "🌡️",
    stage: "B1",
    summary: "强调程度：so + 形容词；such + 名词；too 太……；enough 足够。",
    points: [
      "so + adj/adv：The soup is so spicy that I can't eat it.",
      "such + (adj) + 名词：It is such a quiet room.",
      "too + adj + to do：The bag is too heavy to carry.",
      "adj + enough / enough + 名词：warm enough; enough time。",
      "too 偏负面「太……而不能」；enough 是「够不够」。",
    ],
    examples: [
      { en: "The waves are too big to swim.", zh: "浪太大，不能游。", highlight: "too … to" },
      { en: "It is such a delicious meal.", zh: "这真是美味的一餐。", highlight: "such a" },
      { en: "The room is big enough for two.", zh: "房间够两个人住。", highlight: "enough" },
      { en: "I arrived early enough to check in.", zh: "我到得够早，能办入住。", highlight: "early enough" },
    ],
    quizzes: [
      { question: "It is ____ hot that we stayed inside.", options: ["such", "so", "too", "enough"], answer: 1, explain: "so + adj + that。" },
      { question: "It is ____ a busy airport.", options: ["so", "such", "too", "enough"], answer: 1, explain: "such + a + adj + 名词。" },
      { question: "The case is ____ heavy to lift.", options: ["enough", "so", "too", "such"], answer: 2, explain: "too … to 表示太……而不能。" },
      { question: "We don't have ____ time.", options: ["too", "so", "enough", "such"], answer: 2, explain: "enough + 名词。" },
      { question: "Is the tea warm ____?", options: ["too", "enough", "so", "such"], answer: 1, explain: "形容词后 enough。" },
      { question: "She is ____ tired to walk.", options: ["enough", "too", "such", "so a"], answer: 1, explain: "too tired to walk。" },
    ],
  }),
  lesson({
    slug: "conjunctions",
    title: "连词 because / although / however",
    titleEn: "Conjunctions & Linkers",
    emoji: "🧵",
    stage: "B1",
    summary: "把两句话接起来：原因、转折、结果。雅思写作特别常用。",
    points: [
      "because / since / as 表原因。because 后面是句子。",
      "so 表结果，不要和 because 叠用在同一句。",
      "although / even though 表让步，后面接句子；despite / in spite of 接名词。",
      "however / therefore 常放句首，后面加逗号。",
      "if / unless 表条件；when / while 表时间。",
    ],
    examples: [
      { en: "I took a taxi because I was late.", zh: "我迟到了，所以打车。", highlight: "because" },
      { en: "Although the hotel was small, it was clean.", zh: "酒店虽小但干净。", highlight: "Although" },
      { en: "Despite the rain, we walked on the beach.", zh: "尽管下雨，我们仍去了沙滩。", highlight: "Despite" },
      { en: "The flight was delayed. However, we still arrived on time.", zh: "航班延误了。不过我们还是准时到了。", highlight: "However" },
    ],
    quizzes: [
      { question: "I stayed in ____ it was raining.", options: ["so", "because", "however", "despite"], answer: 1, explain: "because + 句子表原因。" },
      { question: "____ the delay, we caught the train.", options: ["Because", "Although", "Despite", "So"], answer: 2, explain: "despite + 名词。" },
      { question: "The room was small. ____, it was quiet.", options: ["Because", "However", "So that", "Despite"], answer: 1, explain: "however 连接转折的两句。" },
      { question: "____ he was tired, he kept walking.", options: ["Despite", "Although", "However", "Because of"], answer: 1, explain: "although + 句子。" },
      { question: "错误的是？", options: ["Because I was late, I ran.", "I was late, so I ran.", "Because I was late, so I ran.", "I ran because I was late."], answer: 2, explain: "because 和 so 不能叠用。" },
      { question: "Take a coat ____ it gets cold.", options: ["despite", "in case", "however", "although of"], answer: 1, explain: "in case 以防。" },
    ],
  }),
  lesson({
    slug: "question-tags",
    title: "反意疑问句",
    titleEn: "Question Tags",
    emoji: "❓",
    stage: "B1",
    summary: "前肯后否、前否后肯，用来确认信息。",
    points: [
      "You're from Beijing, aren't you?",
      "She doesn't like spicy food, does she?",
      "Let's go, shall we? I'm late, aren't I?",
      "There is a shop, isn't there?",
      "祈使句：Open the window, will you? / Don't be late, will you?",
    ],
    examples: [
      { en: "The wifi is working, isn't it?", zh: "网是通的，对吧？", highlight: "isn't it" },
      { en: "You haven't checked out, have you?", zh: "你还没退房，是吗？", highlight: "have you" },
      { en: "Let's take a taxi, shall we?", zh: "我们打车吧，好吗？", highlight: "shall we" },
      { en: "Don't forget the sunscreen, will you?", zh: "别忘了防晒霜，好吗？", highlight: "will you" },
    ],
    quizzes: [
      { question: "It's expensive, ____?", options: ["is it", "isn't it", "doesn't it", "hasn't it"], answer: 1, explain: "前肯后否 isn't it。" },
      { question: "You don't mind, ____?", options: ["do you", "don't you", "are you", "will you"], answer: 0, explain: "前否后肯 do you。" },
      { question: "She has arrived, ____?", options: ["hasn't she", "doesn't she", "isn't she", "has she"], answer: 0, explain: "has 的否定 hasn't she。" },
      { question: "Let's wait, ____?", options: ["will we", "shall we", "don't we", "aren't we"], answer: 1, explain: "Let's 用 shall we。" },
      { question: "There aren't any seats, ____?", options: ["are there", "aren't there", "is there", "don't there"], answer: 0, explain: "前否后肯 are there。" },
      { question: "I'm early, ____?", options: ["am I", "aren't I", "isn't I", "don't I"], answer: 1, explain: "I'm 的反意用 aren't I。" },
    ],
  }),
  lesson({
    slug: "adverbs",
    title: "副词与频度",
    titleEn: "Adverbs of Frequency & Manner",
    emoji: "⏲️",
    stage: "A2",
    summary: "频度副词放在实义动词前、be 动词后。",
    points: [
      "always > usually > often > sometimes > rarely > never。",
      "I always take a bus. She is always late.",
      "方式副词多在句末：He spoke slowly. She packed carefully.",
      "very / really 修饰形容词：very spicy；so 也可。",
      "hard（努力）和 hardly（几乎不）意思完全不同。",
    ],
    examples: [
      { en: "I usually check in online.", zh: "我通常网上值机。", highlight: "usually" },
      { en: "He is never late for flights.", zh: "赶飞机他从不迟到。", highlight: "never" },
      { en: "Please speak slowly.", zh: "请说慢一点。", highlight: "slowly" },
      { en: "She works hard, but she hardly sleeps.", zh: "她工作很努力，但几乎不睡觉。", highlight: "hard / hardly" },
    ],
    quizzes: [
      { question: "She ____ drinks coffee. (从不)", options: ["always", "never", "usually", "often"], answer: 1, explain: "从不是 never。" },
      { question: "He is ____ helpful.", options: ["always", "always is", "is always not", "always be"], answer: 0, explain: "频度副词在 be 后：is always。" },
      { question: "Please wait ____.", options: ["quiet", "quietly", "quietness", "quiets"], answer: 1, explain: "修饰动词用副词 quietly。" },
      { question: "I ____ go by train. (通常)", options: ["never", "hardly", "usually", "ever"], answer: 2, explain: "usually = 通常。" },
      { question: "He ____ sleeps. (几乎不)", options: ["hard", "hardly", "harder", "hardly ever not"], answer: 1, explain: "hardly = 几乎不。" },
      { question: "They packed the bags ____.", options: ["careful", "carefully", "care", "caring"], answer: 1, explain: "方式副词 carefully。" },
    ],
  }),
  lesson({
    slug: "pronouns",
    title: "代词与所有格",
    titleEn: "Pronouns",
    emoji: "👤",
    stage: "A1",
    summary: "主格 I、宾格 me、形容词性 my、名词性 mine 要分清。",
    points: [
      "主格：I you he she it we they（做主语）。",
      "宾格：me you him her it us them（做宾语）。",
      "形容词性物主代词：my your his her its our their + 名词。",
      "名词性：mine yours his hers ours theirs，后面不再接名词。",
      "反身：myself yourself himself herself itself ourselves yourselves themselves。",
    ],
    examples: [
      { en: "Can you help me?", zh: "你能帮我吗？", highlight: "me" },
      { en: "This is my key. That one is yours.", zh: "这是我的钥匙。那个是你的。", highlight: "yours" },
      { en: "She booked the room herself.", zh: "她自己订的房。", highlight: "herself" },
      { en: "The wifi password is on the desk. Don't lose it.", zh: "密码在桌上，别弄丢。", highlight: "it" },
    ],
    quizzes: [
      { question: "Please give ____ the menu.", options: ["I", "my", "me", "mine"], answer: 2, explain: "宾语用 me。" },
      { question: "This seat is ____.", options: ["my", "me", "mine", "I"], answer: 2, explain: "后面没名词，用 mine。" },
      { question: "They carried the bags ____.", options: ["themself", "themselves", "theirselves", "them"], answer: 1, explain: "复数反身 themselves。" },
      { question: "____ room is on the third floor.", options: ["They", "Them", "Their", "Theirs"], answer: 2, explain: "修饰名词 room 用 their。" },
      { question: "I made it ____.", options: ["me", "my", "myself", "mine"], answer: 2, explain: "自己做的用 myself。" },
      { question: "This passport is ____, not hers.", options: ["he", "him", "his", "he's"], answer: 2, explain: "名词性 his。" },
    ],
  }),
  lesson({
    slug: "present-perfect-vs-past",
    title: "现在完成时 vs 一般过去时",
    titleEn: "Present Perfect vs Past Simple",
    emoji: "⚔️",
    stage: "B1",
    summary: "有具体过去时间用过去时；强调到现在的结果或经历用完成时。",
    points: [
      "Have you been to Paris?（经历，没说何时）",
      "Did you go to Paris last year?（有 last year）",
      "I've lost my key.（现在还没找到）I lost my key yesterday.（单纯叙述）",
      "already/yet/ever/never/since/for 偏完成时；ago/yesterday/last 偏过去时。",
      "been to 去过已回；gone to 去了还没回。",
    ],
    examples: [
      { en: "I have lost my passport. I can't find it.", zh: "护照丢了，找不到。", highlight: "have lost" },
      { en: "I lost my passport last Monday.", zh: "护照是上周一丢的。", highlight: "lost last Monday" },
      { en: "She has gone to the gate.", zh: "她去登机口了（人还不在这儿）。", highlight: "has gone" },
      { en: "She has been to London twice.", zh: "她去过伦敦两次。", highlight: "has been" },
    ],
    quizzes: [
      { question: "I ____ my wallet yesterday.", options: ["have lost", "lost", "lose", "had lose"], answer: 1, explain: "yesterday 用过去时。" },
      { question: "____ you ever stayed here?", options: ["Did", "Have", "Do", "Had"], answer: 1, explain: "ever 搭配现在完成时。" },
      { question: "He isn't here. He ____ to the bank.", options: ["has been", "has gone", "went already", "goes"], answer: 1, explain: "人不在用 has gone。" },
      { question: "We lived there ____ three years. Now we don't.", options: ["since", "for", "already", "yet"], answer: 1, explain: "过去住过一段时间用过去时 + for。" },
      { question: "I ____ just arrived.", options: ["did", "have", "had", "am"], answer: 1, explain: "just 常用现在完成时。" },
      { question: "When ____ you book the hotel?", options: ["have", "did", "has", "do"], answer: 1, explain: "when 问具体时间，用过去时。" },
    ],
  }),
  lesson({
    slug: "wish",
    title: "wish 与虚拟语气",
    titleEn: "Wish & Unreal Situations",
    emoji: "🌠",
    stage: "B2",
    summary: "对现在不满用过去式；对过去后悔用过去完成。雅思口语常考。",
    points: [
      "I wish I were taller.（现在不真实，be 常用 were）",
      "I wish I had packed sunscreen.（过去后悔）",
      "I wish you would stop making noise.（对别人习惯不满）",
      "If only 语气更强：If only I had a window seat.",
      "It's time we went. / I'd rather you didn't smoke.",
    ],
    examples: [
      { en: "I wish I had more time.", zh: "真希望我有更多时间。", highlight: "wish I had" },
      { en: "I wish I had booked earlier.", zh: "真希望早点订。", highlight: "had booked" },
      { en: "If only the waves were smaller.", zh: "浪要是小一点就好了。", highlight: "If only … were" },
      { en: "I wish they would lower the music.", zh: "真希望他们把音乐关小。", highlight: "would lower" },
    ],
    quizzes: [
      { question: "I wish I ____ richer now.", options: ["am", "were", "was being", "be"], answer: 1, explain: "对现在虚拟用 were。" },
      { question: "I wish I ____ that flight yesterday.", options: ["didn't miss", "hadn't missed", "haven't missed", "don't miss"], answer: 1, explain: "对过去后悔用过去完成。" },
      { question: "If only it ____ raining.", options: ["stops", "stopped", "stop", "will stop"], answer: 1, explain: "对现在不满用过去式。" },
      { question: "I wish you ____ make so much noise.", options: ["don't", "wouldn't", "won't", "aren't"], answer: 1, explain: "对别人习惯用 would。" },
      { question: "It's time we ____.", options: ["leave", "left", "leaving", "have left"], answer: 1, explain: "It's time + 过去式。" },
      { question: "I'd rather you ____ here.", options: ["don't smoke", "didn't smoke", "not to smoke", "aren't smoke"], answer: 1, explain: "would rather + 过去式。" },
    ],
  }),
  lesson({
    slug: "participle",
    title: "分词作状语与定语",
    titleEn: "Participles",
    emoji: "🌿",
    stage: "B2",
    summary: "doing 表主动进行；done 表被动完成。阅读里能帮你拆长句。",
    points: [
      "定语：a waiting guest；a broken key。",
      "状语：Looking at the menu, I ordered soup.",
      "被动背景：Built in 1990, the hotel is still popular.",
      "Having packed, we left for the airport.（先完成）",
      "逻辑主语要一致：不能写 Looking at the sea, the waves were big.",
    ],
    examples: [
      { en: "The waiting passengers looked tired.", zh: "等候的乘客显得很累。", highlight: "waiting" },
      { en: "The lost passport was found.", zh: "丢失的护照找到了。", highlight: "lost" },
      { en: "Walking on the beach, we collected shells.", zh: "在沙滩走时我们捡了贝壳。", highlight: "Walking" },
      { en: "Having checked in, she went to the gate.", zh: "办完值机她去了登机口。", highlight: "Having checked" },
    ],
    quizzes: [
      { question: "The ____ window needs repair.", options: ["breaking", "broken", "broke", "breaks"], answer: 1, explain: "被打破的窗户用 broken。" },
      { question: "____ the bill, we left.", options: ["Pay", "Paying", "Paid", "Pays"], answer: 1, explain: "主动进行用 Paying。" },
      { question: "____ in 2010, the bridge is still new.", options: ["Building", "Built", "Build", "Builds"], answer: 1, explain: "桥是被建的，用 Built。" },
      { question: "____ packed, we called a taxi.", options: ["Have", "Having", "Had", "Has"], answer: 1, explain: "先完成用 Having done。" },
      { question: "a ____ child（正在睡觉）", options: ["slept", "sleeping", "sleeps", "sleepy of"], answer: 1, explain: "主动进行 sleeping。" },
      { question: "错误的是？", options: ["Looking at the map, I found the gate.", "Looking at the map, the gate was near.", "I found the gate looking at the map."], answer: 1, explain: "分词逻辑主语应是 I，不能是 the gate。" },
    ],
  }),
];
