import { pack } from "./pack.js";

export const lifeWords = [
  ...pack({ category: "documents", cluster: "papers", clusterName: "票据单据", exam: "CET4", stage: "A2" }, [
    ["receipt", "/rɪˈsiːt/", "收据", "🧾", "Please keep the receipt.", "请保留收据。"],
    ["invoice", "/ˈɪnvɔɪs/", "发票", "📄", "They emailed the invoice today.", "他们今天把发票发到了邮箱。"],
    ["bill", "/bɪl/", "账单", "💵", "Could we have the bill, please?", "请结账。"],
    ["ticket", "/ˈtɪkɪt/", "小票", "🎟️", "The shop gave me a ticket.", "店员给了我一张小票。"],
    ["voucher", "/ˈvaʊtʃə/", "凭证", "🎫", "This voucher is valid for one year.", "这张凭证一年内有效。"],
    ["statement", "/ˈsteɪtmənt/", "对账单", "📊", "I checked my bank statement.", "我核对了银行对账单。", "n.", ["tion"]],
    ["slip", "/slɪp/", "单据", "📃", "Sign the deposit slip, please.", "请在存款单据上签名。"],
    ["purchase order", "/ˈpɜːtʃəs ˈɔːdə/", "采购订单", "🛒", "We sent a purchase order to the supplier.", "我们向供应商发了采购订单。"],
    ["delivery note", "/dɪˈlɪvəri nəʊt/", "送货单", "📦", "Check the goods against the delivery note.", "请对照送货单验收货物。"],
  ]),
  ...pack({ category: "documents", cluster: "office-docs", clusterName: "商务文件", exam: "CET6", stage: "B1" }, [
    ["contract", "/ˈkɒntrækt/", "合同", "📝", "Please sign the contract.", "请签署合同。"],
    ["quotation", "/kwəʊˈteɪʃn/", "报价单", "💹", "We need a quotation before ordering.", "下单前我们需要一份报价单。", "n.", ["tion"]],
    ["cheque", "/tʃek/", "支票", "🏦", "He paid by cheque.", "他用支票付款。"],
    ["warranty", "/ˈwɒrənti/", "保修单", "🛡️", "The laptop has a two-year warranty.", "这台笔记本有两年保修。"],
    ["receipts", "/rɪˈsiːts/", "收入凭据", "📁", "Keep all receipts for tax.", "报税请保留所有凭据。"],
    ["memo", "/ˈmeməʊ/", "备忘录", "🗒️", "I wrote a memo to the team.", "我给团队写了一份备忘录。"],
    ["agenda", "/əˈdʒendə/", "议程", "📅", "The meeting agenda is attached.", "会议议程已附上。"],
    ["minutes", "/ˈmɪnɪts/", "会议纪要", "✒️", "She took the minutes of the meeting.", "她做了会议纪要。"],
    ["appendix", "/əˈpendɪks/", "附录", "📎", "See appendix A for details.", "详情见附录 A。"],
    ["resume", "/ˈrezjumeɪ/", "简历", "👤", "Please send your resume.", "请发送你的简历。"],
    ["certificate", "/səˈtɪfɪkət/", "证书", "🏅", "He got a certificate in accounting.", "他拿到了会计证书。"],
    ["license", "/ˈlaɪsns/", "执照", "🪪", "You need a driving license.", "你需要驾驶执照。"],
    ["form", "/fɔːm/", "表格", "📋", "Fill in this form.", "请填写这张表格。"],
    ["application", "/ˌæplɪˈkeɪʃn/", "申请表", "✉️", "Submit your application online.", "请在线提交申请。", "n.", ["tion"]],
    ["archive", "/ˈɑːkaɪv/", "档案", "🗃️", "The files are in the archive.", "文件在档案室里。"],
  ]),
  ...pack({ category: "documents", cluster: "finance-docs", clusterName: "财务票据", exam: "IELTS", stage: "B2" }, [
    ["ledger", "/ˈledʒə/", "分类账", "📚", "Enter the sum in the ledger.", "把金额记入分类账。"],
    ["balance sheet", "/ˈbæləns ʃiːt/", "资产负债表", "📈", "The balance sheet looks healthy.", "资产负债表看起来很稳健。"],
    ["audit", "/ˈɔːdɪt/", "审计", "🔍", "The company is under audit.", "公司正在接受审计。"],
    ["reimbursement", "/ˌriːɪmˈbɜːsmənt/", "报销", "💸", "Claim reimbursement for travel.", "申请差旅报销。", "n.", ["ment"]],
    ["deduction", "/dɪˈdʌkʃn/", "扣款", "➖", "Tax deduction is shown here.", "税款扣减显示在这里。", "n.", ["tion"]],
    ["overdue", "/ˌəʊvəˈdjuː/", "逾期的", "⏰", "This invoice is overdue.", "这张发票已逾期。", "adj."],
    ["payable", "/ˈpeɪəbl/", "应付的", "📤", "Accounts payable rose this month.", "本月应付账款上升。", "adj.", ["able"]],
    ["receivable", "/rɪˈsiːvəbl/", "应收的", "📥", "Accounts receivable are delayed.", "应收账款回款延迟。", "adj.", ["able"]],
    ["fiscal", "/ˈfɪskl/", "财政的", "🏛️", "The fiscal year ends in March.", "财年于三月结束。", "adj."],
    ["transaction", "/trænˈzækʃn/", "交易", "🔄", "Each transaction is recorded.", "每笔交易都有记录。", "n.", ["tion"]],
  ]),

  ...pack({ category: "home", cluster: "structure", clusterName: "房屋结构", exam: "CET4", stage: "A1" }, [
    ["ceiling", "/ˈsiːlɪŋ/", "天花板", "🏠", "The ceiling is white.", "天花板是白色的。"],
    ["hall", "/hɔːl/", "走廊", "🚪", "Leave your shoes in the hall.", "把鞋放在走廊。"],
    ["floor", "/flɔː/", "地板", "🪵", "The wooden floor is smooth.", "木地板很光滑。"],
    ["stair", "/steə/", "楼梯", "🪜", "Be careful on the stair.", "上下楼梯要小心。"],
    ["attic", "/ˈætɪk/", "阁楼", "🏡", "Old boxes are in the attic.", "旧箱子放在阁楼里。"],
    ["roof", "/ruːf/", "屋顶", "🏘️", "Rain is falling on the roof.", "雨打在屋顶上。"],
    ["wall", "/wɔːl/", "墙壁", "🧱", "Hang the picture on the wall.", "把画挂在墙上。"],
    ["window", "/ˈwɪndəʊ/", "窗户", "🪟", "Open the window, please.", "请打开窗户。"],
    ["door", "/dɔː/", "门", "🚪", "Close the door behind you.", "请随手关门。"],
    ["basement", "/ˈbeɪsmənt/", "地下室", "⬇️", "The washer is in the basement.", "洗衣机在地下室。", "n.", ["ment"]],
    ["balcony", "/ˈbælkəni/", "阳台", "🌅", "We have breakfast on the balcony.", "我们在阳台上吃早餐。"],
    ["chimney", "/ˈtʃɪmni/", "烟囱", "🏭", "Smoke rose from the chimney.", "烟从烟囱里冒出来。"],
    ["fence", "/fens/", "篱笆", "🚧", "A wooden fence surrounds the yard.", "院子四周有木篱笆。"],
    ["garage", "/ˈɡærɑːʒ/", "车库", "🚗", "Park the car in the garage.", "把车停进车库。"],
  ]),
  ...pack({ category: "home", cluster: "garden", clusterName: "庭院花草", exam: "CET4", stage: "A1" }, [
    ["garden", "/ˈɡɑːdn/", "花园", "🏡", "She is watering the garden.", "她正在给花园浇水。"],
    ["yard", "/jɑːd/", "院子", "🌳", "The children play in the yard.", "孩子们在院子里玩。"],
    ["plant", "/plɑːnt/", "植物", "🌿", "This plant needs sunlight.", "这株植物需要阳光。"],
    ["flower", "/ˈflaʊə/", "鲜花", "🌸", "He bought a bunch of flowers.", "他买了一束鲜花。"],
    ["lawn", "/lɔːn/", "草坪", "🟢", "Please mow the lawn.", "请修剪草坪。"],
    ["hedge", "/hedʒ/", "树篱", "🌲", "A hedge hides the road.", "树篱挡住了马路。"],
    ["soil", "/sɔɪl/", "土壤", "🟤", "The soil is rich and dark.", "土壤肥沃而发黑。"],
    ["seed", "/siːd/", "种子", "🌱", "Plant the seeds in spring.", "春天把种子种下。"],
    ["weed", "/wiːd/", "杂草", "🌾", "Pull the weeds out.", "把杂草拔掉。"],
    ["greenhouse", "/ˈɡriːnhaʊs/", "温室", "🪴", "Tomatoes grow in the greenhouse.", "西红柿在温室里生长。"],
  ]),
  ...pack({ category: "home", cluster: "living", clusterName: "起居电器", exam: "CET4", stage: "A1" }, [
    ["home", "/həʊm/", "家", "🏠", "There is no place like home.", "没有什么地方比得上家。"],
    ["television", "/ˈtelɪvɪʒn/", "电视", "📺", "Turn on the television.", "打开电视。"],
    ["telephone", "/ˈtelɪfəʊn/", "电话", "☎️", "The telephone is ringing.", "电话在响。"],
    ["movie", "/ˈmuːvi/", "电影", "🎬", "We watched a movie last night.", "我们昨晚看了一部电影。"],
    ["news", "/njuːz/", "新闻", "📰", "I watch the evening news.", "我看晚间新闻。"],
    ["switch", "/swɪtʃ/", "开关", "💡", "The light switch is by the door.", "电灯开关在门边。"],
    ["remote", "/rɪˈməʊt/", "遥控器", "📡", "Where is the remote?", "遥控器在哪？"],
    ["socket", "/ˈsɒkɪt/", "插座", "🔌", "Plug it into the socket.", "把它插到插座上。"],
    ["fridge", "/frɪdʒ/", "冰箱", "❄️", "Put the milk in the fridge.", "把牛奶放进冰箱。"],
    ["oven", "/ˈʌvn/", "烤箱", "🔥", "Bake the cake in the oven.", "把蛋糕放进烤箱烤。"],
    ["microwave", "/ˈmaɪkrəweɪv/", "微波炉", "📻", "Heat it in the microwave.", "用微波炉加热。"],
    ["dishwasher", "/ˈdɪʃwɒʃə/", "洗碗机", "🍽️", "Load the dishwasher, please.", "请把碗放进洗碗机。"],
    ["vacuum", "/ˈvækjuəm/", "吸尘器", "🧹", "I vacuum the carpet every week.", "我每周用吸尘器吸地毯。"],
    ["heater", "/ˈhiːtə/", "暖气", "♨️", "Turn up the heater.", "把暖气开大一点。"],
  ]),
  ...pack({ category: "home", cluster: "decor", clusterName: "陈设音乐", exam: "CET4", stage: "A2" }, [
    ["vase", "/vɑːz/", "花瓶", "🏺", "Put the roses in the vase.", "把玫瑰插进花瓶。"],
    ["carpet", "/ˈkɑːpɪt/", "地毯", "🟫", "The carpet feels soft.", "地毯踩起来很软。"],
    ["guitar", "/ɡɪˈtɑː/", "吉他", "🎸", "He plays the guitar well.", "他吉他弹得很好。"],
    ["piano", "/piˈænəʊ/", "钢琴", "🎹", "She practised the piano.", "她练了钢琴。"],
    ["music", "/ˈmjuːzɪk/", "音乐", "🎵", "I love classical music.", "我喜欢古典音乐。"],
    ["curtain", "/ˈkɜːtn/", "窗帘", "🪟", "Draw the curtains at night.", "晚上把窗帘拉上。"],
    ["sofa", "/ˈsəʊfə/", "沙发", "🛋️", "Sit on the sofa.", "坐到沙发上。"],
    ["cushion", "/ˈkʊʃn/", "靠垫", "🟠", "This cushion is comfortable.", "这个靠垫很舒服。"],
    ["lamp", "/læmp/", "台灯", "🪔", "The lamp is too bright.", "灯太亮了。"],
    ["mirror", "/ˈmɪrə/", "镜子", "🪞", "Look in the mirror.", "照照镜子。"],
    ["shelf", "/ʃelf/", "架子", "📚", "Put the books on the shelf.", "把书放到架子上。"],
    ["drawer", "/drɔː/", "抽屉", "🗄️", "The keys are in the drawer.", "钥匙在抽屉里。"],
    ["blanket", "/ˈblæŋkɪt/", "毯子", "🛏️", "I need a thicker blanket.", "我需要更厚的毯子。"],
    ["pillow", "/ˈpɪləʊ/", "枕头", "🛌", "This pillow is too high.", "这个枕头太高了。"],
  ]),

  ...pack({ category: "vegetables", cluster: "common", clusterName: "常见蔬菜", exam: "CET4", stage: "A1" }, [
    ["carrot", "/ˈkærət/", "胡萝卜", "🥕", "I like carrot soup.", "我喜欢胡萝卜汤。"],
    ["cabbage", "/ˈkæbɪdʒ/", "卷心菜", "🥬", "This cabbage is fresh.", "这颗卷心菜很新鲜。"],
    ["potato", "/pəˈteɪtəʊ/", "土豆", "🥔", "Boil the potatoes.", "把土豆煮一下。"],
    ["tomato", "/təˈmɑːtəʊ/", "西红柿", "🍅", "Add one tomato.", "加一个西红柿。"],
    ["onion", "/ˈʌnjən/", "洋葱", "🧅", "Chop the onion finely.", "把洋葱切碎。"],
    ["broccoli", "/ˈbrɒkəli/", "西兰花", "🥦", "Broccoli is good for you.", "西兰花对身体好。"],
    ["cucumber", "/ˈkjuːkʌmbə/", "黄瓜", "🥒", "Slice the cucumber.", "把黄瓜切片。"],
    ["pepper", "/ˈpepə/", "辣椒；胡椒", "🌶️", "This pepper is spicy.", "这个辣椒很辣。"],
    ["lettuce", "/ˈletɪs/", "生菜", "🥗", "Wash the lettuce.", "把生菜洗干净。"],
    ["corn", "/kɔːn/", "玉米", "🌽", "We had corn for dinner.", "晚饭我们吃了玉米。"],
    ["spinach", "/ˈspɪnɪtʃ/", "菠菜", "🥬", "Spinach is rich in iron.", "菠菜富含铁。"],
    ["garlic", "/ˈɡɑːlɪk/", "大蒜", "🧄", "Add two cloves of garlic.", "加两瓣蒜。"],
    ["ginger", "/ˈdʒɪndʒə/", "姜", "🫚", "Ginger tea helps a cold.", "姜茶对感冒有帮助。"],
    ["eggplant", "/ˈeɡplɑːnt/", "茄子", "🍆", "Fry the eggplant lightly.", "把茄子稍微煎一下。"],
    ["pumpkin", "/ˈpʌmpkɪn/", "南瓜", "🎃", "Pumpkin soup is sweet.", "南瓜汤有点甜。"],
    ["mushroom", "/ˈmʌʃrʊm/", "蘑菇", "🍄", "I added mushrooms to the pasta.", "我在意面里加了蘑菇。"],
    ["celery", "/ˈseləri/", "芹菜", "🥬", "Celery is crunchy.", "芹菜很脆。"],
    ["radish", "/ˈrædɪʃ/", "萝卜", "🔴", "The radish is crisp.", "这根萝卜很脆。"],
    ["bean", "/biːn/", "豆子", "🫘", "Green beans are in season.", "四季豆正当季。"],
    ["pea", "/piː/", "豌豆", "🟢", "The child likes green peas.", "孩子喜欢豌豆。"],
  ]),
  ...pack({ category: "fruits", cluster: "common", clusterName: "常见水果", exam: "CET4", stage: "A1" }, [
    ["apple", "/ˈæpl/", "苹果", "🍎", "An apple a day keeps the doctor away.", "一天一苹果，医生远离我。"],
    ["banana", "/bəˈnɑːnə/", "香蕉", "🍌", "Monkeys love bananas.", "猴子喜欢香蕉。"],
    ["orange", "/ˈɒrɪndʒ/", "橙子", "🍊", "Would you like orange juice?", "你想喝橙汁吗？"],
    ["grape", "/ɡreɪp/", "葡萄", "🍇", "These grapes are sweet.", "这些葡萄很甜。"],
    ["strawberry", "/ˈstrɔːbəri/", "草莓", "🍓", "I want strawberry ice cream.", "我想要草莓冰淇淋。"],
    ["watermelon", "/ˈwɔːtəmelən/", "西瓜", "🍉", "Watermelon is perfect in summer.", "夏天吃西瓜最合适。"],
    ["lemon", "/ˈlemən/", "柠檬", "🍋", "Add a slice of lemon.", "加一片柠檬。"],
    ["peach", "/piːtʃ/", "桃子", "🍑", "This peach is juicy.", "这个桃子很多汁。"],
    ["pear", "/peə/", "梨", "🍐", "The pear is ripe.", "这梨熟了。"],
    ["cherry", "/ˈtʃeri/", "樱桃", "🍒", "Cherries are in season now.", "樱桃正当时。"],
    ["mango", "/ˈmæŋɡəʊ/", "芒果", "🥭", "The mango is very sweet.", "这芒果很甜。"],
    ["pineapple", "/ˈpaɪnæpl/", "菠萝", "🍍", "Pineapple is a bit sour.", "菠萝有点酸。"],
    ["kiwi", "/ˈkiːwiː/", "猕猴桃", "🥝", "Cut the kiwi in half.", "把猕猴桃切成两半。"],
    ["coconut", "/ˈkəʊkənʌt/", "椰子", "🥥", "Coconut water is refreshing.", "椰子水很解渴。"],
    ["blueberry", "/ˈbluːbəri/", "蓝莓", "🫐", "Blueberries are rich in vitamins.", "蓝莓富含维生素。"],
    ["plum", "/plʌm/", "李子", "🟣", "The plum is sour.", "这李子有点酸。"],
    ["fig", "/fɪɡ/", "无花果", "🟤", "Dried figs are sweet.", "无花果干很甜。"],
    ["avocado", "/ˌævəˈkɑːdəʊ/", "牛油果", "🥑", "Mash the avocado.", "把牛油果压成泥。"],
  ]),
  ...pack({ category: "animals", cluster: "pets", clusterName: "宠物家畜", exam: "CET4", stage: "A1" }, [
    ["dog", "/dɒɡ/", "狗", "🐶", "My dog is friendly.", "我的狗很友好。"],
    ["cat", "/kæt/", "猫", "🐱", "The cat is sleeping.", "猫在睡觉。"],
    ["bird", "/bɜːd/", "鸟", "🐦", "A bird is singing.", "一只鸟在唱歌。"],
    ["fish", "/fɪʃ/", "鱼", "🐟", "There are many fish in the lake.", "湖里有很多鱼。"],
    ["horse", "/hɔːs/", "马", "🐴", "She can ride a horse.", "她会骑马。"],
    ["rabbit", "/ˈræbɪt/", "兔子", "🐰", "The rabbit is eating a carrot.", "兔子在吃胡萝卜。"],
    ["sheep", "/ʃiːp/", "羊", "🐑", "The sheep are in the field.", "羊在田野里。"],
    ["cow", "/kaʊ/", "奶牛", "🐮", "The cow gives milk.", "奶牛产奶。"],
    ["pig", "/pɪɡ/", "猪", "🐷", "The pig is in the mud.", "猪在泥里。"],
    ["chicken", "/ˈtʃɪkɪn/", "鸡", "🐔", "The chicken laid an egg.", "鸡下了一只蛋。"],
    ["duck", "/dʌk/", "鸭子", "🦆", "Ducks swim in the pond.", "鸭子在池塘里游。"],
    ["mouse", "/maʊs/", "老鼠", "🐭", "A mouse ran under the sofa.", "一只老鼠钻到沙发下。"],
  ]),
  ...pack({ category: "animals", cluster: "wildlife", clusterName: "野生动物", exam: "CET6", stage: "B1" }, [
    ["species", "/ˈspiːʃiːz/", "物种", "🧬", "This species is endangered.", "这一物种濒临灭绝。"],
    ["habitat", "/ˈhæbɪtæt/", "栖息地", "🏞️", "Forests are their natural habitat.", "森林是它们的自然栖息地。"],
    ["predator", "/ˈpredətə/", "捕食者", "🦁", "The lion is a top predator.", "狮子是顶级捕食者。"],
    ["prey", "/preɪ/", "猎物", "🦌", "The eagle spotted its prey.", "鹰发现了猎物。"],
    ["mammal", "/ˈmæml/", "哺乳动物", "🐘", "Whales are mammals.", "鲸是哺乳动物。"],
    ["reptile", "/ˈreptaɪl/", "爬行动物", "🦎", "A snake is a reptile.", "蛇是爬行动物。"],
    ["migrate", "/maɪˈɡreɪt/", "迁徙", "🦢", "These birds migrate south.", "这些鸟向南迁徙。", "v."],
    ["endangered", "/ɪnˈdeɪndʒəd/", "濒危的", "⚠️", "Pandas are endangered.", "大熊猫是濒危动物。", "adj."],
    ["extinct", "/ɪkˈstɪŋkt/", "灭绝的", "💀", "Dinosaurs are extinct.", "恐龙已经灭绝。", "adj."],
    ["wildlife", "/ˈwaɪldlaɪf/", "野生生物", "🦒", "The park protects wildlife.", "公园保护野生生物。"],
    ["beast", "/biːst/", "野兽", "🐯", "A wild beast roared.", "一头野兽在吼。"],
    ["herd", "/hɜːd/", "兽群", "🐃", "A herd of elephants passed.", "一群大象走过。"],
  ]),
  ...pack({ category: "transport", cluster: "vehicles", clusterName: "交通工具", exam: "CET4", stage: "A1" }, [
    ["plane", "/pleɪn/", "飞机", "✈️", "The plane takes off at 9 a.m.", "飞机上午九点起飞。"],
    ["train", "/treɪn/", "火车", "🚆", "I go to work by train.", "我坐火车上班。"],
    ["bus", "/bʌs/", "公交车", "🚌", "Which bus goes to the airport?", "哪路车去机场？"],
    ["taxi", "/ˈtæksi/", "出租车", "🚕", "Let's take a taxi.", "我们打车吧。"],
    ["subway", "/ˈsʌbweɪ/", "地铁", "🚇", "The subway is crowded.", "地铁很挤。"],
    ["ferry", "/ˈferi/", "渡轮", "⛴️", "We crossed by ferry.", "我们坐渡轮过去。"],
    ["bicycle", "/ˈbaɪsɪkl/", "自行车", "🚲", "I go to school by bicycle.", "我骑自行车上学。"],
    ["motorcycle", "/ˈməʊtəsaɪkl/", "摩托车", "🏍️", "He rides a motorcycle.", "他骑摩托车。"],
    ["truck", "/trʌk/", "卡车", "🚚", "The truck is overloaded.", "卡车超载了。"],
    ["helicopter", "/ˈhelɪkɒptə/", "直升机", "🚁", "A helicopter landed on the roof.", "直升机落在屋顶上。"],
  ]),
  ...pack({ category: "transport", cluster: "travel-words", clusterName: "出行用语", exam: "CET4", stage: "A2" }, [
    ["passport", "/ˈpɑːspɔːt/", "护照", "🛂", "Please show your passport.", "请出示您的护照。"],
    ["luggage", "/ˈlʌɡɪdʒ/", "行李", "🧳", "Your luggage is overweight.", "您的行李超重了。"],
    ["gate", "/ɡeɪt/", "登机口", "🚪", "Please go to gate 12.", "请前往 12 号登机口。"],
    ["fare", "/feə/", "车费", "🪙", "How much is the bus fare?", "公交票多少钱？"],
    ["boarding pass", "/ˈbɔːdɪŋ pɑːs/", "登机牌", "🎫", "Show your boarding pass.", "请出示登机牌。"],
    ["platform", "/ˈplætfɔːm/", "站台", "🚉", "The train leaves from platform 3.", "火车从 3 站台开出。"],
    ["delay", "/dɪˈleɪ/", "延误", "⏳", "The flight has a delay.", "航班延误了。"],
    ["departure", "/dɪˈpɑːtʃə/", "出发", "🛫", "Departure is at noon.", "正午出发。"],
    ["arrival", "/əˈraɪvl/", "到达", "🛬", "Arrival time is 6 p.m.", "到达时间是下午六点。"],
    ["transfer", "/ˈtrænsfɜː/", "换乘", "🔁", "I need to transfer in Dubai.", "我要在迪拜转机。"],
    ["customs", "/ˈkʌstəmz/", "海关", "🧳", "Go through customs first.", "先过海关。"],
    ["terminal", "/ˈtɜːmɪnl/", "航站楼", "🏢", "We are in terminal 2.", "我们在 2 号航站楼。"],
  ]),
  ...pack({ category: "food", cluster: "dining", clusterName: "餐厅点餐", exam: "CET4", stage: "A2" }, [
    ["menu", "/ˈmenjuː/", "菜单", "📋", "Can I see the menu?", "请给我看一下菜单。"],
    ["order", "/ˈɔːdə/", "点餐；订单", "🧾", "I'd like to order a salad.", "我想点一份沙拉。", "v."],
    ["delicious", "/dɪˈlɪʃəs/", "美味的", "😋", "This soup is delicious.", "这汤很好喝。", "adj."],
    ["spicy", "/ˈspaɪsi/", "辣的", "🥵", "Is this dish spicy?", "这道菜辣吗？", "adj."],
    ["waiter", "/ˈweɪtə/", "服务员", "👨‍🍳", "The waiter is coming.", "服务员过来了。"],
    ["appetizer", "/ˈæpɪtaɪzə/", "开胃菜", "🥗", "We shared an appetizer.", "我们分享了一份开胃菜。"],
    ["dessert", "/dɪˈzɜːt/", "甜点", "🍰", "Chocolate cake for dessert.", "甜点要巧克力蛋糕。"],
    ["beverage", "/ˈbevərɪdʒ/", "饮品", "🥤", "What beverage do you want?", "你想喝什么？"],
    ["tip", "/tɪp/", "小费", "💵", "Leave a 10% tip.", "留 10% 的小费。"],
    ["reservation", "/ˌrezəˈveɪʃn/", "预订", "📅", "I have a reservation.", "我有预订。", "n.", ["tion"]],
    ["ingredient", "/ɪnˈɡriːdiənt/", "食材", "🧂", "List all the ingredients.", "列出所有食材。"],
    ["recipe", "/ˈresəpi/", "食谱", "📖", "This recipe is easy.", "这份食谱很简单。"],
    ["cuisine", "/kwɪˈziːn/", "菜系", "🍜", "I love Sichuan cuisine.", "我爱川菜。"],
    ["vegetarian", "/ˌvedʒəˈteəriən/", "素食者", "🥬", "Is there a vegetarian option?", "有素食选项吗？"],
    ["allergy", "/ˈælədʒi/", "过敏", "🚫", "I have a peanut allergy.", "我对花生过敏。"],
    ["sour", "/ˈsaʊə/", "酸的", "🍋", "The sauce is too sour.", "酱太酸了。", "adj."],
    ["bitter", "/ˈbɪtə/", "苦的", "☕", "The coffee tastes bitter.", "咖啡有点苦。", "adj."],
    ["steak", "/steɪk/", "牛排", "🥩", "I'd like a medium steak.", "我要七分熟牛排。"],
  ]),
  ...pack({ category: "hotel", cluster: "stay", clusterName: "入住设施", exam: "CET4", stage: "A2" }, [
    ["check-in", "/tʃek ɪn/", "办理入住", "🛎️", "Check-in starts at 3 p.m.", "下午三点开始办理入住。"],
    ["check-out", "/tʃek aʊt/", "退房", "🔑", "Check-out is at 11 a.m.", "退房时间是上午十一点。"],
    ["room", "/ruːm/", "房间", "🛏️", "I'd like a quiet room.", "我想要一间安静的房间。"],
    ["key", "/kiː/", "钥匙；房卡", "🗝️", "Here is your room key.", "这是您的房卡。"],
    ["wifi", "/ˈwaɪfaɪ/", "无线网络", "📶", "What's the wifi password?", "无线网密码是多少？"],
    ["suite", "/swiːt/", "套房", "🏨", "They booked a suite.", "他们订了套房。"],
    ["lobby", "/ˈlɒbi/", "大堂", "🏛️", "Wait for me in the lobby.", "在大堂等我。"],
    ["receptionist", "/rɪˈsepʃənɪst/", "前台", "💁", "Ask the receptionist.", "去问前台。"],
    ["housekeeping", "/ˈhaʊskiːpɪŋ/", "客房服务", "🧹", "Please call housekeeping.", "请叫客房服务。"],
    ["amenity", "/əˈmiːnəti/", "配套设施", "🏊", "The hotel amenities include a gym.", "酒店设施包括健身房。"],
    ["deposit", "/dɪˈpɒzɪt/", "押金", "💰", "A deposit is required.", "需要交押金。"],
    ["vacancy", "/ˈveɪkənsi/", "空房", "🟢", "Do you have any vacancies?", "还有空房吗？"],
    ["comfortable", "/ˈkʌmftəbl/", "舒服的", "😌", "Is the bed comfortable?", "床舒服吗？", "adj.", ["able"]],
    ["available", "/əˈveɪləbl/", "可获得的", "🟢", "Is a double room available?", "还有双人房吗？", "adj.", ["able"]],
    ["unpack", "/ʌnˈpæk/", "打开行李", "👜", "I need to unpack my luggage.", "我得打开行李。", "v.", ["un"]],
    ["return", "/rɪˈtɜːn/", "返回；归还", "↩️", "Return the key at check-out.", "退房时归还房卡。", "v.", ["re"]],
    ["helpful", "/ˈhelpfl/", "有帮助的", "🤗", "The staff are very helpful.", "工作人员非常热心。", "adj.", ["ful"]],
    ["wireless", "/ˈwaɪələs/", "无线的", "📡", "The hotel has wireless internet.", "酒店有无线网络。", "adj.", ["less"]],
  ]),
  ...pack({ category: "beach", cluster: "seaside", clusterName: "海边度假", exam: "CET4", stage: "A2" }, [
    ["beach", "/biːtʃ/", "海滩", "🏖️", "Let's walk on the beach.", "我们去沙滩上走走吧。"],
    ["sand", "/sænd/", "沙子", "🏜️", "The sand is warm.", "沙子是温热的。"],
    ["wave", "/weɪv/", "海浪", "🌊", "Look at those big waves.", "看那些大浪。"],
    ["sunscreen", "/ˈsʌnskriːn/", "防晒霜", "🧴", "Don't forget the sunscreen.", "别忘了防晒霜。"],
    ["swim", "/swɪm/", "游泳", "🏊", "I want to swim in the sea.", "我想在海里游泳。", "v."],
    ["shell", "/ʃel/", "贝壳", "🐚", "She collected pretty shells.", "她捡了一些漂亮的贝壳。"],
    ["tide", "/taɪd/", "潮汐", "🌊", "The tide is coming in.", "潮水正在上涨。"],
    ["reef", "/riːf/", "礁石", "🪸", "Do not stand on the reef.", "不要站在礁石上。"],
    ["lifeguard", "/ˈlaɪfɡɑːd/", "救生员", "🛟", "The lifeguard blew a whistle.", "救生员吹了哨。"],
    ["umbrella", "/ʌmˈbrelə/", "遮阳伞", "⛱️", "Rent a beach umbrella.", "租一把沙滩伞。"],
    ["snorkel", "/ˈsnɔːkl/", "浮潜", "🤿", "We snorkeled near the island.", "我们在岛边浮潜。", "v."],
    ["horizon", "/həˈraɪzn/", "地平线", "🌅", "The sun sank below the horizon.", "太阳沉到了地平线以下。"],
  ]),
  ...pack({ category: "daily", cluster: "basics", clusterName: "日常基础", exam: "CET4", stage: "A1" }, [
    ["morning", "/ˈmɔːnɪŋ/", "早上", "🌅", "Good morning!", "早上好！"],
    ["water", "/ˈwɔːtə/", "水", "💧", "Can I have some water?", "可以给我一些水吗？"],
    ["happy", "/ˈhæpi/", "开心的", "😊", "I am happy today.", "我今天很开心。", "adj."],
    ["help", "/help/", "帮助", "🤝", "Can you help me, please?", "你能帮我一下吗？", "v."],
    ["please", "/pliːz/", "请", "🙏", "A coffee, please.", "请来一杯咖啡。", "adv."],
    ["thank", "/θæŋk/", "感谢", "💖", "Thank you so much.", "非常感谢。", "v."],
    ["sorry", "/ˈsɒri/", "抱歉", "🙇", "I am sorry I am late.", "抱歉我迟到了。", "adj."],
    ["time", "/taɪm/", "时间", "⏰", "What time is it?", "现在几点？"],
    ["today", "/təˈdeɪ/", "今天", "📆", "Today is Monday.", "今天是星期一。"],
    ["tomorrow", "/təˈmɒrəʊ/", "明天", "➡️", "See you tomorrow.", "明天见。"],
    ["yesterday", "/ˈjestədeɪ/", "昨天", "⬅️", "I arrived yesterday.", "我昨天到的。"],
    ["weather", "/ˈweðə/", "天气", "⛅", "The weather is fine.", "天气很好。"],
    ["able", "/ˈeɪbl/", "能够的", "✅", "She is able to swim.", "她会游泳。", "adj.", ["able"]],
    ["repeat", "/rɪˈpiːt/", "重复", "🔁", "Could you repeat that?", "请再说一遍。", "v.", ["re"]],
    ["prepare", "/prɪˈpeə/", "准备", "🧳", "Please prepare your passport.", "请准备好护照。", "v.", ["pre"]],
    ["careful", "/ˈkeəfl/", "小心的", "⚠️", "Be careful on the wet floor.", "地板湿，请小心。", "adj.", ["ful"]],
    ["unhappy", "/ʌnˈhæpi/", "不高兴的", "☹️", "He looks unhappy.", "他看起来不高兴。", "adj.", ["un"]],
    ["enable", "/ɪˈneɪbl/", "使能够", "🟢", "This tool can enable you to learn faster.", "这个工具能让你学得更快。", "v.", ["able"]],
    ["disable", "/dɪsˈeɪbl/", "禁用", "🚫", "Please disable the alarm.", "请关掉警报。", "v.", ["dis", "able"]],
    ["preview", "/ˈpriːvjuː/", "预习；预览", "👀", "Let's preview tomorrow's lesson.", "我们预习一下明天的课。", "v.", ["pre"]],
  ]),
  ...pack({ category: "clothing", cluster: "wear", clusterName: "衣着穿戴", exam: "CET4", stage: "A2" }, [
    ["shirt", "/ʃɜːt/", "衬衫", "👕", "This shirt is too tight.", "这件衬衫太紧。"],
    ["trousers", "/ˈtraʊzəz/", "裤子", "👖", "I need a pair of trousers.", "我需要一条裤子。"],
    ["dress", "/dres/", "连衣裙", "👗", "She wore a red dress.", "她穿了一条红裙子。"],
    ["coat", "/kəʊt/", "外套", "🧥", "Take a coat. It is cold.", "带件外套，天冷。"],
    ["jacket", "/ˈdʒækɪt/", "夹克", "🧥", "Hang your jacket here.", "把夹克挂这儿。"],
    ["skirt", "/skɜːt/", "半身裙", "👗", "The skirt matches the blouse.", "裙子和衬衫很配。"],
    ["socks", "/sɒks/", "袜子", "🧦", "These socks are wool.", "这双袜子是羊毛的。"],
    ["shoes", "/ʃuːz/", "鞋子", "👟", "Take off your shoes.", "请脱鞋。"],
    ["boots", "/buːts/", "靴子", "👢", "Wear boots in the snow.", "下雪要穿靴子。"],
    ["hat", "/hæt/", "帽子", "🎩", "A hat protects you from the sun.", "帽子可以防晒。"],
    ["scarf", "/skɑːf/", "围巾", "🧣", "Wrap a scarf around your neck.", "围上围巾。"],
    ["gloves", "/ɡlʌvz/", "手套", "🧤", "I lost one of my gloves.", "我丢了一只手套。"],
    ["belt", "/belt/", "皮带", "➰", "Tighten the belt.", "把皮带收紧。"],
    ["uniform", "/ˈjuːnɪfɔːm/", "制服", "👔", "Students wear a uniform.", "学生穿校服。"],
    ["fashion", "/ˈfæʃn/", "时尚", "✨", "She works in fashion.", "她在时尚行业工作。"],
    ["fabric", "/ˈfæbrɪk/", "面料", "🧵", "This fabric is cotton.", "这种面料是棉的。"],
    ["sleeve", "/sliːv/", "袖子", "👕", "Roll up your sleeves.", "把袖子卷起来。"],
    ["collar", "/ˈkɒlə/", "衣领", "👔", "The collar is dirty.", "衣领脏了。"],
  ]),
  ...pack({ category: "sports", cluster: "games", clusterName: "运动项目", exam: "CET4", stage: "A2" }, [
    ["football", "/ˈfʊtbɔːl/", "足球", "⚽", "They play football after class.", "他们课后踢足球。"],
    ["basketball", "/ˈbɑːskɪtbɔːl/", "篮球", "🏀", "He is on the basketball team.", "他在篮球队。"],
    ["tennis", "/ˈtenɪs/", "网球", "🎾", "Shall we play tennis?", "我们打网球好吗？"],
    ["swimming", "/ˈswɪmɪŋ/", "游泳", "🏊", "Swimming builds stamina.", "游泳能练耐力。"],
    ["running", "/ˈrʌnɪŋ/", "跑步", "🏃", "I go running at dawn.", "我黎明去跑步。"],
    ["cycling", "/ˈsaɪklɪŋ/", "骑行", "🚴", "Cycling is good exercise.", "骑行是很好的运动。"],
    ["athlete", "/ˈæθliːt/", "运动员", "🏅", "The athlete won a medal.", "这位运动员得了奖牌。"],
    ["coach", "/kəʊtʃ/", "教练", "📢", "Our coach is strict.", "我们教练很严。"],
    ["stadium", "/ˈsteɪdiəm/", "体育场", "🏟️", "The stadium was full.", "体育场坐满了。"],
    ["score", "/skɔː/", "比分", "🔢", "The final score was 2-1.", "最终比分 2 比 1。"],
    ["champion", "/ˈtʃæmpiən/", "冠军", "🏆", "She is the world champion.", "她是世界冠军。"],
    ["tournament", "/ˈtʊənəmənt/", "锦标赛", "🥇", "The tournament starts in May.", "锦标赛五月开始。"],
    ["stretch", "/stretʃ/", "拉伸", "🙆", "Stretch before you run.", "跑前先拉伸。", "v."],
    ["endurance", "/ɪnˈdjʊərəns/", "耐力", "💪", "Marathon needs endurance.", "马拉松需要耐力。"],
    ["referee", "/ˌrefəˈriː/", "裁判", "🟨", "The referee blew the whistle.", "裁判吹哨了。"],
    ["spectator", "/spekˈteɪtə/", "观众", "👀", "Spectators cheered loudly.", "观众大声欢呼。"],
  ]),
  ...pack({ category: "emotions", cluster: "feelings", clusterName: "情绪性格", exam: "CET4", stage: "A2" }, [
    ["angry", "/ˈæŋɡri/", "生气的", "😡", "He got angry at the delay.", "他对延误很生气。", "adj."],
    ["anxious", "/ˈæŋkʃəs/", "焦虑的", "😰", "I feel anxious before tests.", "考试前我会焦虑。", "adj."],
    ["calm", "/kɑːm/", "平静的", "😌", "Stay calm and think.", "保持冷静，想一想。", "adj."],
    ["confident", "/ˈkɒnfɪdənt/", "自信的", "💪", "She is confident in English.", "她对自己的英语很有信心。", "adj."],
    ["curious", "/ˈkjʊəriəs/", "好奇的", "🧐", "Children are curious.", "孩子很好奇。", "adj."],
    ["disappointed", "/ˌdɪsəˈpɔɪntɪd/", "失望的", "😞", "I was disappointed by the news.", "这个消息让我失望。", "adj.", ["dis"]],
    ["embarrassed", "/ɪmˈbærəst/", "尴尬的", "😳", "He felt embarrassed.", "他觉得很尴尬。", "adj."],
    ["grateful", "/ˈɡreɪtfl/", "感激的", "🙏", "I am grateful for your help.", "感谢你的帮助。", "adj.", ["ful"]],
    ["lonely", "/ˈləʊnli/", "孤独的", "🌧️", "She felt lonely abroad.", "她在国外感到孤独。", "adj."],
    ["optimistic", "/ˌɒptɪˈmɪstɪk/", "乐观的", "🌞", "Try to stay optimistic.", "尽量保持乐观。", "adj."],
    ["patience", "/ˈpeɪʃns/", "耐心", "🕊️", "Please have patience.", "请有点耐心。"],
    ["proud", "/praʊd/", "骄傲的", "🦚", "I am proud of you.", "我为你感到骄傲。", "adj."],
    ["stressed", "/strest/", "有压力的", "😫", "He is stressed at work.", "他工作压力很大。", "adj."],
    ["sympathy", "/ˈsɪmpəθi/", "同情", "💗", "She showed sympathy.", "她表示了同情。"],
    ["ambition", "/æmˈbɪʃn/", "志向", "🎯", "He has great ambition.", "他很有志向。", "n.", ["tion"]],
    ["attitude", "/ˈætɪtjuːd/", "态度", "🧭", "Attitude matters more than talent.", "态度比天赋更重要。"],
  ]),
];
