import { pack } from "./pack.js";

export const examWords = [
  ...pack({ category: "office", cluster: "workplace", clusterName: "职场办公", exam: "CET6", stage: "B1" }, [
    ["colleague", "/ˈkɒliːɡ/", "同事", "👥", "Discuss it with your colleague.", "和同事商量一下。"],
    ["deadline", "/ˈdedlaɪn/", "截止日期", "⌛", "The deadline is Friday.", "截止日期是周五。"],
    ["meeting", "/ˈmiːtɪŋ/", "会议", "💼", "We have a meeting at ten.", "我们十点开会。"],
    ["promotion", "/prəˈməʊʃn/", "晋升", "📈", "She got a promotion.", "她升职了。", "n.", ["tion"]],
    ["salary", "/ˈsæləri/", "薪水", "💶", "His salary increased.", "他的薪水涨了。"],
    ["overtime", "/ˈəʊvətaɪm/", "加班", "🌙", "I worked overtime yesterday.", "我昨天加班了。"],
    ["interview", "/ˈɪntəvjuː/", "面试", "🎤", "I have a job interview.", "我有一场面试。"],
    ["resume", "/ˈrezjumeɪ/", "简历", "📄", "Update your resume.", "更新一下简历。"],
    ["client", "/ˈklaɪənt/", "客户", "🤝", "The client is waiting.", "客户在等。"],
    ["project", "/ˈprɒdʒekt/", "项目", "📁", "The project is on track.", "项目进展顺利。"],
    ["task", "/tɑːsk/", "任务", "✅", "Finish the task today.", "今天把任务做完。"],
    ["efficient", "/ɪˈfɪʃnt/", "高效的", "⚡", "This method is more efficient.", "这个方法更高效。", "adj."],
    ["negotiate", "/nɪˈɡəʊʃieɪt/", "谈判", "🗣️", "We will negotiate the price.", "我们会谈价格。", "v."],
    ["supervise", "/ˈsuːpəvaɪz/", "监督", "👀", "She supervises the team.", "她负责监督团队。", "v."],
    ["workload", "/ˈwɜːkləʊd/", "工作量", "📦", "My workload is heavy.", "我的工作量很大。"],
    ["bonus", "/ˈbəʊnəs/", "奖金", "🎁", "Staff received a year-end bonus.", "员工拿到了年终奖。"],
    ["resign", "/rɪˈzaɪn/", "辞职", "📤", "He decided to resign.", "他决定辞职。", "v."],
    ["internship", "/ˈɪntɜːnʃɪp/", "实习", "🎓", "I applied for an internship.", "我申请了实习。"],
    ["headquarters", "/ˌhedˈkwɔːtəz/", "总部", "🏢", "Headquarters is in Shanghai.", "总部位于上海。"],
    ["shift", "/ʃɪft/", "班次", "🔄", "I am on the night shift.", "我上夜班。"],
  ]),
  ...pack({ category: "education", cluster: "campus", clusterName: "校园学习", exam: "CET4", stage: "A2" }, [
    ["campus", "/ˈkæmpəs/", "校园", "🏫", "The campus is beautiful.", "校园很美。"],
    ["lecture", "/ˈlektʃə/", "讲座", "👩‍🏫", "The lecture starts at nine.", "讲座九点开始。"],
    ["assignment", "/əˈsaɪnmənt/", "作业", "📝", "Submit the assignment tomorrow.", "作业明天交。", "n.", ["ment"]],
    ["exam", "/ɪɡˈzæm/", "考试", "🧪", "The final exam is hard.", "期末考试很难。"],
    ["semester", "/sɪˈmestə/", "学期", "📅", "This semester I take economics.", "这学期我选修经济学。"],
    ["scholarship", "/ˈskɒləʃɪp/", "奖学金", "🎖️", "She won a scholarship.", "她获得了奖学金。"],
    ["tuition", "/tjuˈɪʃn/", "学费", "💷", "Tuition has increased.", "学费上涨了。", "n.", ["tion"]],
    ["library", "/ˈlaɪbrəri/", "图书馆", "📚", "I study in the library.", "我在图书馆学习。"],
    ["professor", "/prəˈfesə/", "教授", "👨‍🏫", "The professor is famous.", "这位教授很有名。"],
    ["major", "/ˈmeɪdʒə/", "专业", "🎯", "My major is linguistics.", "我的专业是语言学。"],
    ["degree", "/dɪˈɡriː/", "学位", "🎓", "He has a master's degree.", "他有硕士学位。"],
    ["thesis", "/ˈθiːsɪs/", "论文", "📖", "She is writing her thesis.", "她在写论文。"],
    ["curriculum", "/kəˈrɪkjələm/", "课程体系", "🧭", "The curriculum was updated.", "课程体系更新了。"],
    ["revise", "/rɪˈvaɪz/", "复习", "🔁", "Revise the chapter tonight.", "今晚复习这一章。", "v.", ["re"]],
    ["literacy", "/ˈlɪtərəsi/", "读写能力", "✍️", "Digital literacy is essential.", "数字读写能力很重要。"],
    ["enroll", "/ɪnˈrəʊl/", "注册入学", "🖊️", "I enrolled in a night class.", "我报了一个夜校班。", "v."],
    ["dropout", "/ˈdrɒpaʊt/", "辍学", "🚪", "The dropout rate fell.", "辍学率下降了。"],
    ["seminar", "/ˈsemɪnɑː/", "研讨课", "💬", "We discussed it in the seminar.", "我们在研讨课上讨论了这个。"],
  ]),
  ...pack({ category: "academic", cluster: "awl", clusterName: "学术核心词", exam: "IELTS", stage: "B2" }, [
    ["analyze", "/ˈænəlaɪz/", "分析", "🔬", "Analyze the data carefully.", "仔细分析数据。", "v."],
    ["approach", "/əˈprəʊtʃ/", "方法；接近", "🛤️", "We need a new approach.", "我们需要新方法。"],
    ["assess", "/əˈses/", "评估", "📏", "Teachers assess students weekly.", "老师每周评估学生。", "v."],
    ["assume", "/əˈsjuːm/", "假设", "💭", "Don't assume it is true.", "别假定它是真的。", "v."],
    ["authority", "/ɔːˈθɒrəti/", "权威", "⚖️", "He is an authority on climate.", "他是气候领域的权威。"],
    ["benefit", "/ˈbenɪfɪt/", "益处", "🎁", "Exercise has many benefits.", "运动好处很多。"],
    ["concept", "/ˈkɒnsept/", "概念", "💡", "The concept is hard to grasp.", "这个概念不好懂。"],
    ["consist", "/kənˈsɪst/", "由……组成", "🧩", "The team consists of six people.", "团队由六人组成。", "v."],
    ["constitute", "/ˈkɒnstɪtjuːt/", "构成", "🧱", "These acts constitute a crime.", "这些行为构成犯罪。", "v."],
    ["context", "/ˈkɒntekst/", "语境；背景", "🖼️", "Guess the word from context.", "根据语境猜词。"],
    ["create", "/kriˈeɪt/", "创造", "✨", "Artists create new worlds.", "艺术家创造新世界。", "v."],
    ["data", "/ˈdeɪtə/", "数据", "📊", "The data supports the claim.", "数据支持这一说法。"],
    ["define", "/dɪˈfaɪn/", "定义", "📘", "Please define the term.", "请给这个术语下定义。", "v."],
    ["derive", "/dɪˈraɪv/", "源自", "🌱", "The word derives from Latin.", "这个词源自拉丁语。", "v."],
    ["distribute", "/dɪˈstrɪbjuːt/", "分配", "📤", "Distribute the copies fairly.", "把复印件公平分发。", "v."],
    ["establish", "/ɪˈstæblɪʃ/", "建立", "🏛️", "They established a new lab.", "他们建了一座新实验室。", "v."],
    ["estimate", "/ˈestɪmeɪt/", "估计", "📐", "We estimate a 10% rise.", "我们估计会上升 10%。", "v."],
    ["evidence", "/ˈevɪdəns/", "证据", "🔎", "There is little evidence.", "证据很少。"],
    ["factor", "/ˈfæktə/", "因素", "⚖️", "Cost is a key factor.", "成本是关键因素。"],
    ["formula", "/ˈfɔːmjələ/", "公式", "➗", "Remember this formula.", "记住这个公式。"],
    ["function", "/ˈfʌŋkʃn/", "功能", "⚙️", "What is the function of this tool?", "这个工具的功能是什么？", "n.", ["tion"]],
    ["identify", "/aɪˈdentɪfaɪ/", "识别", "🆔", "Can you identify the problem?", "你能找出问题吗？", "v."],
    ["indicate", "/ˈɪndɪkeɪt/", "表明", "👉", "Results indicate improvement.", "结果表明有进步。", "v."],
    ["individual", "/ˌɪndɪˈvɪdʒuəl/", "个人", "🧍", "Each individual is unique.", "每个人都是独特的。"],
    ["interpret", "/ɪnˈtɜːprɪt/", "解释", "🗣️", "How do you interpret this graph?", "你怎么解读这张图？", "v."],
    ["involve", "/ɪnˈvɒlv/", "涉及", "🔗", "The job involves travel.", "这份工作需要出差。", "v."],
    ["issue", "/ˈɪʃuː/", "问题；期号", "❗", "This is a serious issue.", "这是一个严重问题。"],
    ["labour", "/ˈleɪbə/", "劳动", "🛠️", "Cheap labour attracted factories.", "廉价劳动力吸引了工厂。"],
    ["legal", "/ˈliːɡl/", "合法的", "⚖️", "Is this practice legal?", "这种做法合法吗？", "adj."],
    ["major", "/ˈmeɪdʒə/", "主要的", "⭐", "This is a major change.", "这是一项重大变化。", "adj."],
    ["method", "/ˈmeθəd/", "方法", "🧰", "Try a different method.", "换一种方法试试。"],
    ["occur", "/əˈkɜː/", "发生", "⚡", "Accidents occur at night.", "事故常在夜间发生。", "v."],
    ["percent", "/pəˈsent/", "百分之", "💯", "Unemployment fell 2 percent.", "失业率下降了百分之二。"],
    ["period", "/ˈpɪəriəd/", "时期", "⏳", "It was a difficult period.", "那是一段艰难时期。"],
    ["policy", "/ˈpɒləsi/", "政策", "📜", "The new policy takes effect tomorrow.", "新政策明天生效。"],
    ["principle", "/ˈprɪnsəpl/", "原则", "🧭", "We follow this principle.", "我们遵循这一原则。"],
    ["process", "/ˈprəʊses/", "过程", "🔄", "Learning is a slow process.", "学习是一个缓慢的过程。"],
    ["require", "/rɪˈkwaɪə/", "需要", "📌", "The course requires calculus.", "这门课需要微积分。", "v."],
    ["research", "/rɪˈsɜːtʃ/", "研究", "🔬", "Her research is well known.", "她的研究很有名。"],
    ["respond", "/rɪˈspɒnd/", "回应", "💬", "Please respond by Friday.", "请在周五前回复。", "v.", ["re"]],
    ["role", "/rəʊl/", "角色", "🎭", "What is your role in the team?", "你在团队里扮演什么角色？"],
    ["section", "/ˈsekʃn/", "部分", "✂️", "Read section two.", "读第二部分。", "n.", ["tion"]],
    ["sector", "/ˈsektə/", "部门；行业", "🏭", "The public sector is growing.", "公共部门在扩大。"],
    ["significant", "/sɪɡˈnɪfɪkənt/", "显著的", "📌", "There is a significant difference.", "存在显著差异。", "adj."],
    ["similar", "/ˈsɪmələ/", "相似的", "🪞", "The two cases are similar.", "这两个案例很相似。", "adj."],
    ["source", "/sɔːs/", "来源", "⛲", "Cite your sources.", "请注明来源。"],
    ["specific", "/spəˈsɪfɪk/", "具体的", "🎯", "Give a specific example.", "举一个具体例子。", "adj."],
    ["structure", "/ˈstrʌktʃə/", "结构", "🏗️", "The essay has a clear structure.", "这篇文章结构清晰。"],
    ["theory", "/ˈθɪəri/", "理论", "🧠", "The theory is widely accepted.", "该理论被广泛接受。"],
    ["vary", "/ˈveəri/", "变化", "🌈", "Prices vary by season.", "价格随季节变化。", "v."],
    ["criterion", "/kraɪˈtɪəriən/", "标准", "📏", "What is the main criterion?", "主要标准是什么？"],
    ["hypothesis", "/haɪˈpɒθəsɪs/", "假设", "🧪", "Test the hypothesis in the lab.", "在实验室检验这个假设。"],
    ["variable", "/ˈveəriəbl/", "变量", "📉", "Control the other variables.", "控制其他变量。", "n.", ["able"]],
    ["valid", "/ˈvælɪd/", "有效的", "✅", "Is this argument valid?", "这个论证有效吗？", "adj."],
    ["implication", "/ˌɪmplɪˈkeɪʃn/", "含义；影响", "➡️", "Consider the implications.", "考虑一下影响。", "n.", ["tion"]],
    ["perspective", "/pəˈspektɪv/", "视角", "🔭", "From this perspective, it works.", "从这个角度看是可行的。"],
    ["emphasize", "/ˈemfəsaɪz/", "强调", "❗", "The paper emphasizes fairness.", "论文强调公平。", "v."],
    ["evaluate", "/ɪˈvæljueɪt/", "评价", "⚖️", "Evaluate both sides.", "评价双方观点。", "v."],
    ["illustrate", "/ˈɪləstreɪt/", "说明", "🖼️", "This graph illustrates the trend.", "这张图说明了趋势。", "v."],
    ["conclude", "/kənˈkluːd/", "得出结论", "🏁", "We conclude that the plan works.", "我们的结论是该计划可行。", "v."],
    ["furthermore", "/ˌfɜːðəˈmɔː/", "此外", "➕", "Furthermore, costs will fall.", "此外，成本会下降。", "adv."],
    ["nevertheless", "/ˌnevəðəˈles/", "尽管如此", "↔️", "Nevertheless, we continued.", "尽管如此，我们还是继续了。", "adv.", ["less"]],
    ["whereas", "/ˌweərˈæz/", "然而；而", "⚖️", "He is quiet, whereas she is loud.", "他很安静，而她很吵。", "conj."],
  ]),
  ...pack({ category: "environment", cluster: "planet", clusterName: "环境气候", exam: "CET6", stage: "B1" }, [
    ["pollution", "/pəˈluːʃn/", "污染", "🏭", "Air pollution is serious.", "空气污染很严重。", "n.", ["tion"]],
    ["climate", "/ˈklaɪmət/", "气候", "🌍", "The climate is changing.", "气候正在变化。"],
    ["emission", "/ɪˈmɪʃn/", "排放", "💨", "Cut carbon emissions.", "减少碳排放。", "n.", ["tion"]],
    ["recycle", "/ˌriːˈsaɪkl/", "回收", "♻️", "Recycle plastic bottles.", "回收塑料瓶。", "v.", ["re"]],
    ["sustainable", "/səˈsteɪnəbl/", "可持续的", "🌱", "We need sustainable energy.", "我们需要可持续能源。", "adj.", ["able"]],
    ["biodiversity", "/ˌbaɪəʊdaɪˈvɜːsəti/", "生物多样性", "🦋", "Biodiversity is declining.", "生物多样性正在下降。"],
    ["deforestation", "/diːˌfɒrɪˈsteɪʃn/", "滥伐森林", "🌳", "Deforestation causes floods.", "滥伐森林会导致洪水。", "n.", ["tion"]],
    ["drought", "/draʊt/", "干旱", "🏜️", "The drought lasted two years.", "干旱持续了两年。"],
    ["flood", "/flʌd/", "洪水", "🌊", "The flood destroyed homes.", "洪水冲毁了房屋。"],
    ["renewable", "/rɪˈnjuːəbl/", "可再生的", "🔋", "Wind is a renewable resource.", "风能是可再生资源。", "adj.", ["able"]],
    ["greenhouse gas", "/ˈɡriːnhaʊs ɡæs/", "温室气体", "🌡️", "Greenhouse gases trap heat.", "温室气体锁住热量。"],
    ["conservation", "/ˌkɒnsəˈveɪʃn/", "保护", "🛡️", "Wildlife conservation matters.", "野生动物保护很重要。", "n.", ["tion"]],
    ["ecosystem", "/ˈiːkəʊsɪstəm/", "生态系统", "🕸️", "Coral reefs are fragile ecosystems.", "珊瑚礁是脆弱的生态系统。"],
    ["carbon", "/ˈkɑːbən/", "碳", "⚫", "Reduce your carbon footprint.", "减少你的碳足迹。"],
    ["waste", "/weɪst/", "废物", "🗑️", "Don't dump waste in rivers.", "不要把废物倒进河里。"],
    ["smog", "/smɒɡ/", "雾霾", "🌫️", "The city was covered in smog.", "城市被雾霾笼罩。"],
    ["ozone", "/ˈəʊzəʊn/", "臭氧", "🛡️", "The ozone layer is recovering.", "臭氧层正在恢复。"],
    ["erosion", "/ɪˈrəʊʒn/", "侵蚀", "⛰️", "Soil erosion is severe here.", "这里水土流失很严重。", "n.", ["tion"]],
    ["hazardous", "/ˈhæzədəs/", "危险的", "☢️", "Hazardous waste must be sealed.", "危险废物必须密封。", "adj."],
    ["mitigate", "/ˈmɪtɪɡeɪt/", "缓解", "🧯", "Trees mitigate urban heat.", "树木能缓解城市热岛。", "v."],
  ]),
  ...pack({ category: "health", cluster: "body", clusterName: "健康医疗", exam: "CET6", stage: "B1" }, [
    ["symptom", "/ˈsɪmptəm/", "症状", "🤒", "Fever is a common symptom.", "发烧是常见症状。"],
    ["diagnosis", "/ˌdaɪəɡˈnəʊsɪs/", "诊断", "🩺", "The diagnosis was flu.", "诊断结果是流感。"],
    ["prescription", "/prɪˈskrɪpʃn/", "处方", "💊", "Take this prescription to the pharmacy.", "拿处方去药房。", "n.", ["tion"]],
    ["vaccine", "/ˈvæksiːn/", "疫苗", "💉", "The vaccine is safe.", "这种疫苗是安全的。"],
    ["infection", "/ɪnˈfekʃn/", "感染", "🦠", "Wash hands to avoid infection.", "洗手以防感染。", "n.", ["tion"]],
    ["surgery", "/ˈsɜːdʒəri/", "手术", "🏥", "He had heart surgery.", "他做了心脏手术。"],
    ["patient", "/ˈpeɪʃnt/", "病人", "🛏️", "The patient is recovering.", "病人正在康复。"],
    ["clinic", "/ˈklɪnɪk/", "诊所", "🏪", "I went to the dental clinic.", "我去了牙科诊所。"],
    ["emergency", "/ɪˈmɜːdʒənsi/", "急诊", "🚨", "Call emergency services.", "拨打急救电话。"],
    ["nutrition", "/njuˈtrɪʃn/", "营养", "🥦", "Good nutrition prevents disease.", "良好营养能预防疾病。", "n.", ["tion"]],
    ["immune", "/ɪˈmjuːn/", "免疫的", "🛡️", "Sleep helps the immune system.", "睡眠有助于免疫系统。", "adj."],
    ["chronic", "/ˈkrɒnɪk/", "慢性的", "📆", "He has chronic pain.", "他有慢性疼痛。", "adj."],
    ["mental", "/ˈmentl/", "精神的", "🧠", "Mental health is important.", "心理健康很重要。", "adj."],
    ["therapy", "/ˈθerəpi/", "治疗", "🗣️", "She is in physical therapy.", "她在做物理治疗。"],
    ["obesity", "/əʊˈbiːsəti/", "肥胖", "⚖️", "Obesity raises health risks.", "肥胖会增加健康风险。"],
    ["addiction", "/əˈdɪkʃn/", "成瘾", "📱", "Phone addiction is common.", "手机成瘾很常见。", "n.", ["tion"]],
    ["hygiene", "/ˈhaɪdʒiːn/", "卫生", "🧼", "Personal hygiene matters.", "个人卫生很重要。"],
    ["recovery", "/rɪˈkʌvəri/", "康复", "💪", "Recovery takes time.", "康复需要时间。", "n.", ["re"]],
    ["side effect", "/saɪd ɪˈfekt/", "副作用", "⚠️", "Drowsiness is a side effect.", "嗜睡是一种副作用。"],
    ["checkup", "/ˈtʃekʌp/", "体检", "📋", "I have an annual checkup.", "我每年做一次体检。"],
  ]),
  ...pack({ category: "technology", cluster: "digital", clusterName: "科技数码", exam: "CET6", stage: "B1" }, [
    ["software", "/ˈsɒftweə/", "软件", "💿", "Update the software.", "更新软件。"],
    ["hardware", "/ˈhɑːdweə/", "硬件", "🖥️", "The hardware is outdated.", "硬件过时了。"],
    ["algorithm", "/ˈælɡərɪðəm/", "算法", "🧮", "The algorithm recommends videos.", "算法会推荐视频。"],
    ["database", "/ˈdeɪtəbeɪs/", "数据库", "🗄️", "Store records in the database.", "把记录存进数据库。"],
    ["network", "/ˈnetwɜːk/", "网络", "🕸️", "The network is down.", "网络断了。"],
    ["password", "/ˈpɑːswɜːd/", "密码", "🔐", "Change your password often.", "经常更换密码。"],
    ["privacy", "/ˈprɪvəsi/", "隐私", "🕶️", "Protect your privacy online.", "在网上保护隐私。"],
    ["artificial", "/ˌɑːtɪˈfɪʃl/", "人工的", "🤖", "Artificial intelligence is growing.", "人工智能正在发展。", "adj."],
    ["innovation", "/ˌɪnəˈveɪʃn/", "创新", "💡", "The company values innovation.", "公司重视创新。", "n.", ["tion"]],
    ["device", "/dɪˈvaɪs/", "设备", "📱", "Charge the device overnight.", "设备充一夜电。"],
    ["download", "/ˌdaʊnˈləʊd/", "下载", "⬇️", "Download the app.", "下载这个应用。", "v."],
    ["upload", "/ˌʌpˈləʊd/", "上传", "⬆️", "Upload the file to the cloud.", "把文件上传到云端。", "v."],
    ["cyber", "/ˈsaɪbə/", "网络的", "🕸️", "Cyber security is vital.", "网络安全至关重要。", "adj."],
    ["virtual", "/ˈvɜːtʃuəl/", "虚拟的", "🥽", "We held a virtual meeting.", "我们开了线上会。", "adj."],
    ["automation", "/ˌɔːtəˈmeɪʃn/", "自动化", "🤖", "Automation replaces routine jobs.", "自动化取代重复劳动。", "n.", ["tion"]],
    ["bandwidth", "/ˈbændwɪdθ/", "带宽", "📶", "The bandwidth is not enough.", "带宽不够。"],
    ["encrypt", "/ɪnˈkrɪpt/", "加密", "🔒", "Encrypt sensitive emails.", "给敏感邮件加密。", "v."],
    ["interface", "/ˈɪntəfeɪs/", "界面", "🖥️", "The interface is user-friendly.", "界面很友好。"],
    ["portable", "/ˈpɔːtəbl/", "便携的", "🔋", "I need a portable charger.", "我需要便携充电器。", "adj.", ["able"]],
    ["upgrade", "/ˈʌpɡreɪd/", "升级", "⬆️", "Upgrade to the latest version.", "升级到最新版本。", "v."],
  ]),
  ...pack({ category: "economy", cluster: "money", clusterName: "经济金融", exam: "CET6", stage: "B1" }, [
    ["inflation", "/ɪnˈfleɪʃn/", "通货膨胀", "📈", "Inflation is rising.", "通胀在上升。", "n.", ["tion"]],
    ["interest", "/ˈɪntrəst/", "利息；兴趣", "💹", "The interest rate is low.", "利率很低。"],
    ["budget", "/ˈbʌdʒɪt/", "预算", "📒", "We must stick to the budget.", "我们必须守住预算。"],
    ["investment", "/ɪnˈvestmənt/", "投资", "💰", "This is a long-term investment.", "这是一项长期投资。", "n.", ["ment"]],
    ["profit", "/ˈprɒfɪt/", "利润", "📊", "The firm made a profit.", "公司盈利了。"],
    ["loss", "/lɒs/", "亏损", "📉", "They reported a huge loss.", "他们报告了巨额亏损。"],
    ["tax", "/tæks/", "税", "🏛️", "Income tax is deducted monthly.", "所得税按月扣除。"],
    ["debt", "/det/", "债务", "⛓️", "He paid off his debt.", "他还清了债务。"],
    ["loan", "/ləʊn/", "贷款", "🏦", "She took out a student loan.", "她贷了学生贷款。"],
    ["currency", "/ˈkʌrənsi/", "货币", "💴", "The currency fell against the dollar.", "该货币对美元贬值。"],
    ["recession", "/rɪˈseʃn/", "衰退", "📉", "The economy entered a recession.", "经济陷入衰退。", "n.", ["tion"]],
    ["supply", "/səˈplaɪ/", "供给", "📦", "Supply cannot meet demand.", "供给跟不上需求。"],
    ["demand", "/dɪˈmɑːnd/", "需求", "🙋", "Demand for housing is high.", "住房需求很高。"],
    ["consumer", "/kənˈsjuːmə/", "消费者", "🛍️", "Consumers are more cautious.", "消费者更谨慎了。"],
    ["shareholder", "/ˈʃeəhəʊldə/", "股东", "🧾", "Shareholders voted for the plan.", "股东投票通过了该计划。"],
    ["revenue", "/ˈrevənjuː/", "营收", "💵", "Revenue grew by 8%.", "营收增长了 8%。"],
    ["subsidy", "/ˈsʌbsədi/", "补贴", "🎁", "Farmers receive a subsidy.", "农民获得补贴。"],
    ["tariff", "/ˈtærɪf/", "关税", "🚢", "The tariff on steel rose.", "钢铁关税上涨了。"],
    ["bankruptcy", "/ˈbæŋkrʌptsi/", "破产", "💥", "The shop faced bankruptcy.", "这家店面临破产。"],
    ["prosperity", "/prɒˈsperəti/", "繁荣", "🌟", "Trade brought prosperity.", "贸易带来了繁荣。"],
  ]),
  ...pack({ category: "society", cluster: "civic", clusterName: "社会文化", exam: "IELTS", stage: "B2" }, [
    ["community", "/kəˈmjuːnəti/", "社区", "🏘️", "The community organized a fair.", "社区组织了游园会。"],
    ["citizen", "/ˈsɪtɪzn/", "公民", "🪪", "Every citizen has rights.", "每个公民都有权利。"],
    ["equality", "/iˈkwɒləti/", "平等", "⚖️", "They fight for gender equality.", "他们为性别平等而奋斗。"],
    ["poverty", "/ˈpɒvəti/", "贫困", "🏚️", "Poverty remains a challenge.", "贫困仍是挑战。"],
    ["welfare", "/ˈwelfeə/", "福利", "🤲", "Welfare helps the unemployed.", "福利帮助失业者。"],
    ["discrimination", "/dɪˌskrɪmɪˈneɪʃn/", "歧视", "🚫", "Discrimination is illegal.", "歧视是违法的。", "n.", ["tion"]],
    ["diversity", "/daɪˈvɜːsəti/", "多样性", "🌈", "The city values diversity.", "这座城市重视多样性。"],
    ["tradition", "/trəˈdɪʃn/", "传统", "🧧", "This tradition is centuries old.", "这一传统有数百年历史。", "n.", ["tion"]],
    ["generation", "/ˌdʒenəˈreɪʃn/", "一代人", "👨‍👧", "The younger generation is digital.", "年轻一代更数字化。", "n.", ["tion"]],
    ["volunteer", "/ˌvɒlənˈtɪə/", "志愿者", "🙋", "I volunteer at a hospital.", "我在医院做志愿者。"],
    ["urban", "/ˈɜːbən/", "城市的", "🏙️", "Urban life is fast.", "城市生活节奏快。", "adj."],
    ["rural", "/ˈrʊərəl/", "乡村的", "🌾", "Rural areas lack doctors.", "乡村缺少医生。", "adj."],
    ["migration", "/maɪˈɡreɪʃn/", "迁移", "🚶", "Rural-urban migration is common.", "城乡迁移很常见。", "n.", ["tion"]],
    ["infrastructure", "/ˈɪnfrəstrʌktʃə/", "基础设施", "🛣️", "The infrastructure is aging.", "基础设施在老化。"],
    ["census", "/ˈsensəs/", "人口普查", "🔢", "The census is held every ten years.", "人口普查每十年一次。"],
    ["stereotype", "/ˈsteriətaɪp/", "刻板印象", "📦", "Avoid gender stereotypes.", "避免性别刻板印象。"],
    ["ethics", "/ˈeθɪks/", "伦理", "🧭", "Medical ethics must be followed.", "必须遵守医学伦理。"],
    ["privilege", "/ˈprɪvəlɪdʒ/", "特权", "👑", "Education should not be a privilege.", "教育不该是特权。"],
    ["solidarity", "/ˌsɒlɪˈdærəti/", "团结", "🤝", "Workers showed solidarity.", "工人们表现出团结。"],
    ["reform", "/rɪˈfɔːm/", "改革", "🔧", "The reform improved schools.", "改革改善了学校。", "n.", ["re"]],
  ]),
  ...pack({ category: "nature", cluster: "earth", clusterName: "自然地理", exam: "CET6", stage: "B1" }, [
    ["mountain", "/ˈmaʊntən/", "山", "⛰️", "They climbed the mountain.", "他们爬了那座山。"],
    ["valley", "/ˈvæli/", "山谷", "🏞️", "A river runs through the valley.", "一条河穿过山谷。"],
    ["desert", "/ˈdezət/", "沙漠", "🏜️", "The desert is extremely dry.", "沙漠极其干燥。"],
    ["island", "/ˈaɪlənd/", "岛屿", "🏝️", "The island is volcanic.", "这座岛是火山岛。"],
    ["continent", "/ˈkɒntɪnənt/", "大陆", "🌍", "Africa is a vast continent.", "非洲是一片广阔的大陆。"],
    ["ocean", "/ˈəʊʃn/", "海洋", "🌊", "The Pacific is the largest ocean.", "太平洋是最大的洋。"],
    ["volcano", "/vɒlˈkeɪnəʊ/", "火山", "🌋", "The volcano erupted last year.", "这座火山去年喷发了。"],
    ["earthquake", "/ˈɜːθkweɪk/", "地震", "📳", "The earthquake shook the city.", "地震震动了城市。"],
    ["glacier", "/ˈɡlæsiə/", "冰川", "🧊", "The glacier is melting.", "冰川正在融化。"],
    ["canyon", "/ˈkænjən/", "峡谷", "🏜️", "We hiked into the canyon.", "我们徒步走进峡谷。"],
    ["peninsula", "/pəˈnɪnsjələ/", "半岛", "🗺️", "Korea is a peninsula.", "朝鲜半岛是半岛。"],
    ["latitude", "/ˈlætɪtjuːd/", "纬度", "🧭", "Singapore is near the equator in latitude.", "新加坡纬度靠近赤道。"],
    ["altitude", "/ˈæltɪtjuːd/", "海拔", "📏", "The altitude made us dizzy.", "海拔让我们头晕。"],
    ["current", "/ˈkʌrənt/", "洋流", "🌊", "A warm current flows north.", "一股暖流北上。"],
    ["mineral", "/ˈmɪnərəl/", "矿物", "💎", "The region is rich in minerals.", "该地区矿产丰富。"],
    ["fossil", "/ˈfɒsl/", "化石", "🦴", "They found a dinosaur fossil.", "他们发现了恐龙化石。"],
    ["plain", "/pleɪn/", "平原", "🌾", "Crops grow on the plain.", "庄稼长在平原上。"],
    ["coastline", "/ˈkəʊstlaɪn/", "海岸线", "🏖️", "The coastline is rugged.", "海岸线崎岖。"],
  ]),
  ...pack({ category: "city", cluster: "urban-life", clusterName: "城市生活", exam: "CET6", stage: "B1" }, [
    ["downtown", "/ˌdaʊnˈtaʊn/", "市中心", "🏙️", "We live downtown.", "我们住在市中心。"],
    ["suburb", "/ˈsʌbɜːb/", "郊区", "🏡", "They moved to the suburb.", "他们搬到了郊区。"],
    ["skyscraper", "/ˈskaɪskreɪpə/", "摩天大楼", "🏢", "A new skyscraper is going up.", "一座新摩天楼正在建设。"],
    ["pedestrian", "/pəˈdestriən/", "行人", "🚶", "This street is for pedestrians.", "这条街只走行人。"],
    ["congestion", "/kənˈdʒestʃən/", "拥堵", "🚗", "Traffic congestion is worse at 8.", "八点交通更堵。", "n.", ["tion"]],
    ["metro", "/ˈmetrəʊ/", "地铁", "🚇", "Take the metro to work.", "坐地铁上班。"],
    ["crosswalk", "/ˈkrɒswɔːk/", "人行横道", "🚸", "Stop at the crosswalk.", "在人行横道前停下。"],
    ["billboard", "/ˈbɪlbɔːd/", "广告牌", "🪧", "A huge billboard lights the square.", "巨幅广告牌照亮广场。"],
    ["neighborhood", "/ˈneɪbəhʊd/", "街区", "🏘️", "It is a quiet neighborhood.", "这是个安静的街区。"],
    ["rent", "/rent/", "租金", "🔑", "Rent is expensive here.", "这里租金很贵。"],
    ["landlord", "/ˈlændlɔːd/", "房东", "🏠", "Call the landlord about the leak.", "漏水要找房东。"],
    ["utility", "/juːˈtɪləti/", "水电费", "💡", "Utilities are included.", "水电费已包含。"],
    ["commute", "/kəˈmjuːt/", "通勤", "🚆", "My commute takes one hour.", "我通勤要一小时。"],
    ["facility", "/fəˈsɪləti/", "设施", "🏋️", "The gym is a public facility.", "健身房是公共设施。"],
    ["crowded", "/ˈkraʊdɪd/", "拥挤的", "👥", "The mall is crowded on weekends.", "周末商场很挤。", "adj."],
    ["outlet", "/ˈaʊtlet/", "奥特莱斯；出口", "🛍️", "We shopped at an outlet mall.", "我们去奥特莱斯购物。"],
    ["district", "/ˈdɪstrɪkt/", "区域", "🗺️", "The art district is nearby.", "艺术区就在附近。"],
    ["skyline", "/ˈskaɪlaɪn/", "天际线", "🌃", "The skyline looks stunning at night.", "夜景天际线很美。"],
  ]),
  ...pack({ category: "law", cluster: "justice", clusterName: "法律公正", exam: "IELTS", stage: "B2" }, [
    ["law", "/lɔː/", "法律", "⚖️", "Everyone is equal before the law.", "法律面前人人平等。"],
    ["crime", "/kraɪm/", "犯罪", "🚨", "Violent crime has fallen.", "暴力犯罪下降了。"],
    ["court", "/kɔːt/", "法庭", "🏛️", "The case went to court.", "案件上了法庭。"],
    ["judge", "/dʒʌdʒ/", "法官", "👩‍⚖️", "The judge dismissed the case.", "法官驳回了案件。"],
    ["jury", "/ˈdʒʊəri/", "陪审团", "👥", "The jury reached a verdict.", "陪审团做出了裁决。"],
    ["lawyer", "/ˈlɔːjə/", "律师", "💼", "Hire a lawyer immediately.", "立刻请律师。"],
    ["trial", "/ˈtraɪəl/", "审判", "⚖️", "The trial lasted three weeks.", "审判持续了三周。"],
    ["verdict", "/ˈvɜːdɪkt/", "裁决", "📜", "The verdict was not guilty.", "裁决是无罪。"],
    ["punishment", "/ˈpʌnɪʃmənt/", "惩罚", "⛓️", "The punishment must fit the crime.", "罚要与罪相当。", "n.", ["ment"]],
    ["prison", "/ˈprɪzn/", "监狱", "🔒", "He was sent to prison.", "他被送进监狱。"],
    ["witness", "/ˈwɪtnəs/", "证人", "👁️", "A witness saw the accident.", "一名证人看到了事故。"],
    ["exhibit", "/ɪɡˈzɪbɪt/", "证物；展品", "📁", "The police collected the exhibit.", "警方收集了证物。"],
    ["appeal", "/əˈpiːl/", "上诉", "📢", "They will appeal the decision.", "他们将对裁决上诉。", "v."],
    ["legislation", "/ˌledʒɪsˈleɪʃn/", "立法", "📜", "New legislation was passed.", "新立法获得通过。", "n.", ["tion"]],
    ["constitution", "/ˌkɒnstɪˈtjuːʃn/", "宪法", "📘", "Freedom of speech is in the constitution.", "言论自由写在宪法里。", "n.", ["tion"]],
    ["justice", "/ˈdʒʌstɪs/", "正义", "⚖️", "They demanded justice.", "他们要求伸张正义。"],
    ["illegal", "/ɪˈliːɡl/", "非法的", "🚫", "It is illegal to dump waste here.", "在此倾倒废物是非法的。", "adj."],
    ["innocent", "/ˈɪnəsnt/", "无辜的", "🕊️", "He claimed he was innocent.", "他声称自己是无辜的。", "adj."],
    ["guilty", "/ˈɡɪlti/", "有罪的", "⛓️", "The court found her guilty.", "法庭判她有罪。", "adj."],
    ["regulate", "/ˈreɡjuleɪt/", "监管", "📋", "The agency regulates banks.", "该机构监管银行。", "v."],
  ]),
  ...pack({ category: "media", cluster: "news", clusterName: "媒体传播", exam: "CET6", stage: "B1" }, [
    ["headline", "/ˈhedlaɪn/", "标题", "📰", "The headline was misleading.", "标题有误导性。"],
    ["journalist", "/ˈdʒɜːnəlɪst/", "记者", "🎤", "A journalist interviewed the mayor.", "记者采访了市长。"],
    ["broadcast", "/ˈbrɔːdkɑːst/", "广播", "📻", "The speech was broadcast live.", "演讲进行了直播。"],
    ["audience", "/ˈɔːdiəns/", "观众；听众", "👥", "The audience clapped.", "观众鼓掌了。"],
    ["advertisement", "/ədˈvɜːtɪsmənt/", "广告", "📢", "I skipped the advertisement.", "我跳过了广告。", "n.", ["ment"]],
    ["editor", "/ˈedɪtə/", "编辑", "✏️", "The editor cut two paragraphs.", "编辑删了两段。"],
    ["publish", "/ˈpʌblɪʃ/", "出版", "📚", "They will publish the book in May.", "他们五月出版这本书。", "v."],
    ["censorship", "/ˈsensəʃɪp/", "审查", "🚫", "Censorship limits free speech.", "审查限制言论自由。"],
    ["rumor", "/ˈruːmə/", "谣言", "👂", "Don't spread rumors.", "不要散布谣言。"],
    ["bias", "/ˈbaɪəs/", "偏见", "📉", "The report shows political bias.", "报道带有政治偏见。"],
    ["coverage", "/ˈkʌvərɪdʒ/", "报道", "📡", "Media coverage was intense.", "媒体报道很密集。"],
    ["press conference", "/pres ˈkɒnfərəns/", "新闻发布会", "🎙️", "She gave an exclusive press conference.", "她召开了独家新闻发布会。"],
    ["viral", "/ˈvaɪrəl/", "走红的", "📲", "The video went viral.", "这段视频火了。", "adj."],
    ["podcast", "/ˈpɒdkɑːst/", "播客", "🎧", "I listen to a news podcast.", "我听新闻播客。"],
    ["documentary", "/ˌdɒkjuˈmentri/", "纪录片", "🎬", "The documentary won an award.", "这部纪录片得了奖。"],
    ["caption", "/ˈkæpʃn/", "字幕；说明", "💬", "Turn on captions.", "打开字幕。", "n.", ["tion"]],
    ["circulation", "/ˌsɜːkjəˈleɪʃn/", "发行量", "📰", "Newspaper circulation is falling.", "报纸发行量在下降。", "n.", ["tion"]],
    ["press", "/pres/", "新闻界", "🗞️", "The press asked tough questions.", "媒体问了尖锐问题。"],
  ]),
  ...pack({ category: "science", cluster: "lab", clusterName: "科学实验", exam: "IELTS", stage: "B2" }, [
    ["experiment", "/ɪkˈsperɪmənt/", "实验", "🧪", "The experiment confirmed the theory.", "实验证实了该理论。"],
    ["laboratory", "/ləˈbɒrətri/", "实验室", "🔬", "Keep the laboratory clean.", "保持实验室清洁。"],
    ["molecule", "/ˈmɒlɪkjuːl/", "分子", "⚛️", "Water is a simple molecule.", "水是简单分子。"],
    ["atom", "/ˈætəm/", "原子", "⚛️", "An atom has a nucleus.", "原子有原子核。"],
    ["gravity", "/ˈɡrævəti/", "重力", "🍎", "Gravity pulls objects down.", "重力把物体往下拉。"],
    ["evolution", "/ˌiːvəˈluːʃn/", "进化", "🦎", "Evolution takes millions of years.", "进化需要数百万年。", "n.", ["tion"]],
    ["gene", "/dʒiːn/", "基因", "🧬", "The gene was identified in 1999.", "该基因于 1999 年被识别。"],
    ["cell", "/sel/", "细胞", "🧫", "Every cell contains DNA.", "每个细胞都含 DNA。"],
    ["energy", "/ˈenədʒi/", "能量", "⚡", "The sun provides energy.", "太阳提供能量。"],
    ["reaction", "/riˈækʃn/", "反应", "💥", "A chemical reaction occurred.", "发生了化学反应。", "n.", ["tion"]],
    ["observe", "/əbˈzɜːv/", "观察", "👀", "Observe the change closely.", "仔细观察变化。", "v."],
    ["sample", "/ˈsɑːmpl/", "样本", "🧪", "Collect a water sample.", "采集水样。"],
    ["microscope", "/ˈmaɪkrəskəʊp/", "显微镜", "🔬", "Look through the microscope.", "用显微镜看。"],
    ["physics", "/ˈfɪzɪks/", "物理", "📐", "She studies physics.", "她学物理。"],
    ["chemistry", "/ˈkemɪstri/", "化学", "⚗️", "Chemistry explains this change.", "化学能解释这种变化。"],
    ["biology", "/baɪˈɒlədʒi/", "生物", "🧬", "Biology is my favorite subject.", "生物是我最喜欢的科目。"],
    ["engineer", "/ˌendʒɪˈnɪə/", "工程师", "👷", "She is a software engineer.", "她是软件工程师。"],
    ["patent", "/ˈpætnt/", "专利", "📜", "They filed a patent.", "他们申请了专利。"],
    ["prototype", "/ˈprəʊtətaɪp/", "原型", "🛠️", "This is only a prototype.", "这只是原型。"],
    ["accurate", "/ˈækjərət/", "精确的", "🎯", "The measurement is accurate.", "测量很精确。", "adj."],
  ]),
  ...pack({ category: "relationships", cluster: "people", clusterName: "人际关系", exam: "CET4", stage: "A2" }, [
    ["friend", "/frend/", "朋友", "🫂", "She is my best friend.", "她是我最好的朋友。"],
    ["neighbor", "/ˈneɪbə/", "邻居", "🏡", "Our neighbor is kind.", "邻居人很好。"],
    ["stranger", "/ˈstreɪndʒə/", "陌生人", "👤", "Don't talk to strangers.", "不要和陌生人说话。"],
    ["relative", "/ˈrelətɪv/", "亲戚", "👪", "Relatives visited at New Year.", "亲戚新年时来访。"],
    ["couple", "/ˈkʌpl/", "一对；夫妻", "💑", "The couple got married.", "那对夫妻结婚了。"],
    ["colleague", "/ˈkɒliːɡ/", "同事", "👔", "A colleague helped me.", "一位同事帮了我。"],
    ["partner", "/ˈpɑːtnə/", "伴侣；搭档", "🤝", "He is my business partner.", "他是我的生意伙伴。"],
    ["acquaintance", "/əˈkweɪntəns/", "熟人", "👋", "She is only an acquaintance.", "她只是个熟人。"],
    ["trust", "/trʌst/", "信任", "🤝", "Trust takes time.", "信任需要时间。"],
    ["conflict", "/ˈkɒnflɪkt/", "冲突", "⚡", "They resolved the conflict.", "他们化解了冲突。"],
    ["compromise", "/ˈkɒmprəmaɪz/", "妥协", "🤝", "A compromise was reached.", "双方达成了妥协。"],
    ["cooperate", "/kəʊˈɒpəreɪt/", "合作", "🧩", "We must cooperate closely.", "我们必须紧密合作。", "v."],
    ["apologize", "/əˈpɒlədʒaɪz/", "道歉", "🙇", "I apologize for the delay.", "延误了我很抱歉。", "v."],
    ["forgive", "/fəˈɡɪv/", "原谅", "💗", "Please forgive my mistake.", "请原谅我的错误。", "v."],
    ["rely", "/rɪˈlaɪ/", "依靠", "🪢", "You can rely on me.", "你可以依靠我。", "v."],
    ["loyal", "/ˈlɔɪəl/", "忠诚的", "🐕", "Dogs are loyal animals.", "狗是忠诚的动物。", "adj."],
    ["intimate", "/ˈɪntɪmət/", "亲密的", "💞", "They have an intimate friendship.", "他们友谊很亲密。", "adj."],
    ["isolated", "/ˈaɪsəleɪtɪd/", "孤立的", "🏝️", "He felt isolated in the new city.", "他在新城市感到孤立。", "adj."],
  ]),
];
