import { pack } from "./pack.js";

export const plusWords = [
  ...pack({ category: "academic", cluster: "verbs", clusterName: "学术动词", exam: "IELTS", stage: "B2" }, [
    ["demonstrate", "/ˈdemənstreɪt/", "证明；演示", "👉", "The results demonstrate a clear trend.", "结果证明趋势很明显。", "v."],
    ["distinguish", "/dɪˈstɪŋɡwɪʃ/", "区分", "🔍", "Distinguish fact from opinion.", "把事实和观点区分开。", "v."],
    ["contribute", "/kənˈtrɪbjuːt/", "贡献", "🧩", "Many factors contribute to this.", "许多因素导致了这一点。", "v."],
    ["maintain", "/meɪnˈteɪn/", "维持", "🛠️", "Maintain a balanced diet.", "保持均衡饮食。", "v."],
    ["obtain", "/əbˈteɪn/", "获得", "📥", "How did you obtain this data?", "你如何获得这些数据？", "v."],
    ["predict", "/prɪˈdɪkt/", "预测", "🔮", "Models predict a warmer climate.", "模型预测气候会更暖。", "v.", ["pre"]],
    ["reveal", "/rɪˈviːl/", "揭示", "🪟", "The study revealed a gap.", "研究揭示了一个差距。", "v.", ["re"]],
    ["suggest", "/səˈdʒest/", "表明；建议", "💬", "Findings suggest a link.", "结果表明存在关联。", "v."],
    ["summarize", "/ˈsʌməraɪz/", "总结", "🧾", "Summarize the paragraph.", "总结这一段。", "v."],
    ["undermine", "/ˌʌndəˈmaɪn/", "削弱", "🕳️", "This undermines the argument.", "这削弱了该论点。", "v."],
    ["acknowledge", "/əkˈnɒlɪdʒ/", "承认", "🙋", "Acknowledge the limitations.", "承认局限性。", "v."],
    ["advocate", "/ˈædvəkeɪt/", "主张", "📢", "She advocates renewable energy.", "她主张可再生能源。", "v."],
    ["compensate", "/ˈkɒmpenseɪt/", "补偿", "⚖️", "Nothing can compensate for the loss.", "损失无法补偿。", "v."],
    ["decline", "/dɪˈklaɪn/", "下降；拒绝", "📉", "Birth rates continue to decline.", "出生率持续下降。", "v."],
    ["dominate", "/ˈdɒmɪneɪt/", "主导", "👑", "One company dominates the market.", "一家公司主导市场。", "v."],
    ["emerge", "/ɪˈmɜːdʒ/", "出现", "🌅", "New evidence emerged.", "新证据出现了。", "v."],
    ["fluctuate", "/ˈflʌktʃueɪt/", "波动", "📊", "Prices fluctuate daily.", "价格每天波动。", "v."],
    ["generate", "/ˈdʒenəreɪt/", "产生", "⚡", "Wind farms generate electricity.", "风电场发电。", "v."],
    ["inhibit", "/ɪnˈhɪbɪt/", "抑制", "🛑", "Fear can inhibit learning.", "恐惧会抑制学习。", "v."],
    ["justify", "/ˈdʒʌstɪfaɪ/", "证明合理", "✅", "Can you justify this expense?", "你能证明这笔开支合理吗？", "v."],
    ["manipulate", "/məˈnɪpjuleɪt/", "操纵", "🎮", "Don't manipulate the figures.", "不要篡改数据。", "v."],
    ["neglect", "/nɪˈɡlekt/", "忽视", "🙈", "Don't neglect mental health.", "不要忽视心理健康。", "v."],
    ["overcome", "/ˌəʊvəˈkʌm/", "克服", "🧗", "She overcame many obstacles.", "她克服了许多障碍。", "v."],
    ["prohibit", "/prəˈhɪbɪt/", "禁止", "🚫", "Smoking is prohibited here.", "此处禁止吸烟。", "v."],
    ["reinforce", "/ˌriːɪnˈfɔːs/", "加强", "🧱", "Examples reinforce the point.", "例子加强了论点。", "v.", ["re"]],
    ["substitute", "/ˈsʌbstɪtjuːt/", "代替", "🔄", "Substitute honey for sugar.", "用蜂蜜代替糖。", "v."],
    ["trigger", "/ˈtrɪɡə/", "触发", "💥", "Stress can trigger headaches.", "压力会触发头痛。", "v."],
    ["undertake", "/ˌʌndəˈteɪk/", "承担", "🧳", "They undertook a survey.", "他们开展了一项调查。", "v."],
    ["utilize", "/ˈjuːtəlaɪz/", "利用", "🔧", "Utilize available resources.", "利用现有资源。", "v."],
    ["verify", "/ˈverɪfaɪ/", "核实", "✔️", "Verify the sources before citing.", "引用前核实来源。", "v."],
  ]),
  ...pack({ category: "academic", cluster: "adj", clusterName: "学术形容词", exam: "IELTS", stage: "B2" }, [
    ["abstract", "/ˈæbstrækt/", "抽象的", "🌫️", "The idea is too abstract.", "这个想法太抽象。", "adj."],
    ["adequate", "/ˈædɪkwət/", "足够的", "👌", "The sample is not adequate.", "样本不够。", "adj."],
    ["ambiguous", "/æmˈbɪɡjuəs/", "含糊的", "❔", "The wording is ambiguous.", "措辞含糊。", "adj."],
    ["apparent", "/əˈpærənt/", "明显的", "👁️", "It is apparent that costs rose.", "成本上升是明显的。", "adj."],
    ["arbitrary", "/ˈɑːbɪtrəri/", "任意的", "🎲", "The decision seemed arbitrary.", "这个决定显得随意。", "adj."],
    ["coherent", "/kəʊˈhɪərənt/", "连贯的", "🧵", "Write a coherent paragraph.", "写一段连贯的话。", "adj."],
    ["comprehensive", "/ˌkɒmprɪˈhensɪv/", "全面的", "🗺️", "We need a comprehensive plan.", "我们需要全面计划。", "adj."],
    ["controversial", "/ˌkɒntrəˈvɜːʃl/", "有争议的", "⚡", "The topic is controversial.", "这个话题有争议。", "adj."],
    ["crucial", "/ˈkruːʃl/", "关键的", "🔑", "Timing is crucial.", "时机很关键。", "adj."],
    ["dramatic", "/drəˈmætɪk/", "急剧的", "🎭", "There was a dramatic drop.", "出现了急剧下降。", "adj."],
    ["explicit", "/ɪkˈsplɪsɪt/", "明确的", "📢", "Give explicit instructions.", "给出明确指示。", "adj."],
    ["feasible", "/ˈfiːzəbl/", "可行的", "🛤️", "Is the proposal feasible?", "该提案可行吗？", "adj.", ["able"]],
    ["inevitable", "/ɪnˈevɪtəbl/", "不可避免的", "⏳", "Change is inevitable.", "变化不可避免。", "adj.", ["able"]],
    ["marginal", "/ˈmɑːdʒɪnl/", "微小的", "📏", "The difference is marginal.", "差异很小。", "adj."],
    ["objective", "/əbˈdʒektɪv/", "客观的", "🎯", "Remain objective in research.", "研究中保持客观。", "adj."],
    ["potential", "/pəˈtenʃl/", "潜在的", "🌱", "There is potential risk.", "存在潜在风险。", "adj."],
    ["preliminary", "/prɪˈlɪmɪnəri/", "初步的", "1️⃣", "These are preliminary results.", "这些是初步结果。", "adj.", ["pre"]],
    ["prominent", "/ˈprɒmɪnənt/", "突出的", "⭐", "She is a prominent scholar.", "她是著名学者。", "adj."],
    ["radical", "/ˈrædɪkl/", "根本的", "💥", "They proposed radical reform.", "他们提出根本性改革。", "adj."],
    ["relevant", "/ˈreləvənt/", "相关的", "🔗", "Keep only relevant details.", "只保留相关细节。", "adj."],
    ["rigid", "/ˈrɪdʒɪd/", "死板的", "📏", "The rules are too rigid.", "规则太死板。", "adj."],
    ["stable", "/ˈsteɪbl/", "稳定的", "🪨", "Prices remained stable.", "价格保持稳定。", "adj.", ["able"]],
    ["subtle", "/ˈsʌtl/", "微妙的", "🪶", "There is a subtle difference.", "有细微差别。", "adj."],
    ["sufficient", "/səˈfɪʃnt/", "充足的", "✅", "Is the evidence sufficient?", "证据充足吗？", "adj."],
    ["theoretical", "/ˌθɪəˈretɪkl/", "理论的", "🧠", "This is a theoretical model.", "这是理论模型。", "adj."],
    ["widespread", "/ˌwaɪdˈspred/", "普遍的", "🌐", "The practice is widespread.", "这种做法很普遍。", "adj."],
  ]),
  ...pack({ category: "body", cluster: "parts", clusterName: "身体部位", exam: "CET4", stage: "A1" }, [
    ["head", "/hed/", "头", "🧠", "He nodded his head.", "他点了点头。"],
    ["face", "/feɪs/", "脸", "🙂", "Wash your face.", "洗洗脸。"],
    ["eye", "/aɪ/", "眼睛", "👁️", "She has brown eyes.", "她有棕色的眼睛。"],
    ["ear", "/ɪə/", "耳朵", "👂", "My left ear hurts.", "我左耳疼。"],
    ["nose", "/nəʊz/", "鼻子", "👃", "He has a blocked nose.", "他鼻塞。"],
    ["mouth", "/maʊθ/", "嘴", "👄", "Open your mouth.", "张开嘴。"],
    ["tooth", "/tuːθ/", "牙齿", "🦷", "I have a sore tooth.", "我有一颗牙疼。"],
    ["neck", "/nek/", "脖子", "🦒", "My neck is stiff.", "我脖子僵。"],
    ["shoulder", "/ˈʃəʊldə/", "肩膀", "🏋️", "He tapped my shoulder.", "他拍了拍我的肩。"],
    ["arm", "/ɑːm/", "手臂", "💪", "Raise your arm.", "举起手臂。"],
    ["hand", "/hænd/", "手", "✋", "Wash your hands.", "洗手。"],
    ["finger", "/ˈfɪŋɡə/", "手指", "☝️", "She cut her finger.", "她切到了手指。"],
    ["chest", "/tʃest/", "胸部", "🫁", "He felt pain in the chest.", "他感到胸口疼。"],
    ["heart", "/hɑːt/", "心脏", "❤️", "Exercise is good for the heart.", "运动对心脏好。"],
    ["stomach", "/ˈstʌmək/", "胃", "🫃", "My stomach is empty.", "我肚子空了。"],
    ["back", "/bæk/", "后背", "🔙", "I hurt my back.", "我伤到了背。"],
    ["leg", "/leɡ/", "腿", "🦵", "She broke her leg.", "她腿骨折了。"],
    ["knee", "/niː/", "膝盖", "🦴", "He fell on his knee.", "他膝盖着地摔倒。"],
    ["foot", "/fʊt/", "脚", "🦶", "My foot is swollen.", "我脚肿了。"],
    ["skin", "/skɪn/", "皮肤", "🧴", "Protect your skin from the sun.", "防晒保护皮肤。"],
    ["bone", "/bəʊn/", "骨头", "🦴", "Calcium strengthens bones.", "钙能强壮骨骼。"],
    ["muscle", "/ˈmʌsl/", "肌肉", "💪", "Stretch your muscles.", "拉伸肌肉。"],
    ["blood", "/blʌd/", "血液", "🩸", "The nurse took a blood sample.", "护士抽了血样。"],
    ["brain", "/breɪn/", "大脑", "🧠", "Sleep rests the brain.", "睡眠让大脑休息。"],
  ]),
  ...pack({ category: "weather", cluster: "climate-words", clusterName: "天气气候", exam: "CET4", stage: "A2" }, [
    ["sunny", "/ˈsʌni/", "晴朗的", "☀️", "It is sunny today.", "今天晴朗。", "adj."],
    ["cloudy", "/ˈklaʊdi/", "多云的", "☁️", "The sky is cloudy.", "天空多云。", "adj."],
    ["rainy", "/ˈreɪni/", "下雨的", "🌧️", "Take an umbrella on rainy days.", "下雨天带伞。", "adj."],
    ["snowy", "/ˈsnəʊi/", "下雪的", "❄️", "The road is snowy.", "路上有雪。", "adj."],
    ["windy", "/ˈwɪndi/", "有风的", "💨", "It is too windy to sail.", "风太大不能出海。", "adj."],
    ["foggy", "/ˈfɒɡi/", "有雾的", "🌫️", "Driving is dangerous in foggy weather.", "雾天开车危险。", "adj."],
    ["storm", "/stɔːm/", "暴风雨", "⛈️", "A storm is coming.", "暴风雨要来了。"],
    ["thunder", "/ˈθʌndə/", "雷", "🌩️", "Thunder woke the baby.", "雷声吵醒了婴儿。"],
    ["lightning", "/ˈlaɪtnɪŋ/", "闪电", "⚡", "Lightning struck a tree.", "闪电劈中一棵树。"],
    ["temperature", "/ˈtemprətʃə/", "温度", "🌡️", "The temperature dropped overnight.", "夜里气温下降了。"],
    ["humidity", "/hjuːˈmɪdəti/", "湿度", "💧", "Humidity is high in summer.", "夏天湿度高。"],
    ["forecast", "/ˈfɔːkɑːst/", "预报", "📺", "The forecast says rain.", "预报说会下雨。"],
    ["breeze", "/briːz/", "微风", "🍃", "A cool breeze came from the sea.", "一阵凉风从海上吹来。"],
    ["hail", "/heɪl/", "冰雹", "🧊", "Hail damaged the cars.", "冰雹砸坏了车。"],
    ["frost", "/frɒst/", "霜", "❄️", "There was frost on the grass.", "草上有霜。"],
    ["heatwave", "/ˈhiːtweɪv/", "热浪", "🔥", "A heatwave hit the city.", "热浪袭击了城市。"],
  ]),
  ...pack({ category: "work-verbs", cluster: "action", clusterName: "职场动词", exam: "CET6", stage: "B1" }, [
    ["accomplish", "/əˈkʌmplɪʃ/", "完成", "✅", "We accomplished the goal.", "我们完成了目标。", "v."],
    ["allocate", "/ˈæləkeɪt/", "分配", "📦", "Allocate more time to writing.", "给写作分配更多时间。", "v."],
    ["collaborate", "/kəˈlæbəreɪt/", "协作", "🤝", "Teams collaborate across offices.", "团队跨办公室协作。", "v."],
    ["delegate", "/ˈdelɪɡeɪt/", "委派", "📤", "Learn to delegate tasks.", "学会委派任务。", "v."],
    ["implement", "/ˈɪmplɪment/", "实施", "🛠️", "We will implement the plan.", "我们将实施该计划。", "v."],
    ["monitor", "/ˈmɒnɪtə/", "监控", "📺", "Monitor the progress weekly.", "每周监控进度。", "v."],
    ["optimize", "/ˈɒptɪmaɪz/", "优化", "⚙️", "Optimize the workflow.", "优化工作流程。", "v."],
    ["prioritize", "/praɪˈɒrətaɪz/", "优先处理", "1️⃣", "Prioritize urgent emails.", "优先处理紧急邮件。", "v."],
    ["schedule", "/ˈʃedjuːl/", "安排", "📅", "Schedule a call for Monday.", "把电话安排在周一。", "v."],
    ["streamline", "/ˈstriːmlaɪn/", "精简", "➡️", "Streamline the approval process.", "精简审批流程。", "v."],
    ["coordinate", "/kəʊˈɔːdɪneɪt/", "协调", "🧭", "She coordinates three teams.", "她协调三个团队。", "v."],
    ["execute", "/ˈeksɪkjuːt/", "执行", "▶️", "Execute the strategy carefully.", "认真执行战略。", "v."],
    ["facilitate", "/fəˈsɪlɪteɪt/", "促进", "🚪", "Workshops facilitate discussion.", "工作坊促进讨论。", "v."],
    ["initiate", "/ɪˈnɪʃieɪt/", "发起", "🚀", "He initiated the project.", "他发起了这个项目。", "v."],
    ["postpone", "/pəˈspəʊn/", "推迟", "⏭️", "They postponed the launch.", "他们推迟了发布。", "v."],
    ["resolve", "/rɪˈzɒlv/", "解决", "🔓", "We resolved the conflict.", "我们解决了冲突。", "v.", ["re"]],
    ["submit", "/səbˈmɪt/", "提交", "📨", "Submit the report by 5 p.m.", "下午五点前提交报告。", "v."],
    ["track", "/træk/", "跟踪", "📍", "Track customer feedback.", "跟踪客户反馈。", "v."],
  ]),
  ...pack({ category: "ielts-topics", cluster: "global", clusterName: "雅思话题", exam: "IELTS", stage: "B2" }, [
    ["globalization", "/ˌɡləʊbəlaɪˈzeɪʃn/", "全球化", "🌐", "Globalization affects local culture.", "全球化影响本土文化。", "n.", ["tion"]],
    ["urbanization", "/ˌɜːbənaɪˈzeɪʃn/", "城市化", "🏙️", "Urbanization puts pressure on housing.", "城市化给住房带来压力。", "n.", ["tion"]],
    ["overpopulation", "/ˌəʊvəˌpɒpjuˈleɪʃn/", "人口过剩", "👥", "Overpopulation strains resources.", "人口过剩使资源紧张。", "n.", ["tion"]],
    ["unemployment", "/ˌʌnɪmˈplɔɪmənt/", "失业", "📉", "Youth unemployment is high.", "青年失业率很高。", "n.", ["un", "ment"]],
    ["literacy rate", "/ˈlɪtərəsi reɪt/", "识字率", "📖", "The literacy rate has improved.", "识字率提高了。"],
    ["life expectancy", "/laɪf ɪkˈspektənsi/", "预期寿命", "⏳", "Life expectancy rose by five years.", "预期寿命提高了五年。"],
    ["standard of living", "/ˈstændəd əv ˈlɪvɪŋ/", "生活水平", "🏠", "The standard of living varies widely.", "生活水平差异很大。"],
    ["public transport", "/ˈpʌblɪk ˈtrænspɔːt/", "公共交通", "🚌", "Invest more in public transport.", "加大对公交的投入。"],
    ["traffic jam", "/ˈtræfɪk dʒæm/", "堵车", "🚗", "I was stuck in a traffic jam.", "我堵在路上了。"],
    ["work-life balance", "/wɜːk laɪf ˈbæləns/", "工作生活平衡", "⚖️", "Work-life balance is poor here.", "这里很难平衡工作和生活。"],
    ["gap year", "/ɡæp jɪə/", "间隔年", "🎒", "She took a gap year to travel.", "她用间隔年去旅行。"],
    ["distance learning", "/ˈdɪstəns ˈlɜːnɪŋ/", "远程学习", "💻", "Distance learning became common.", "远程学习变得普遍。"],
    ["cultural heritage", "/ˈkʌltʃərəl ˈherɪtɪdʒ/", "文化遗产", "🏯", "Protect cultural heritage sites.", "保护文化遗产。"],
    ["fast food", "/fɑːst fuːd/", "快餐", "🍔", "Too much fast food is unhealthy.", "快餐吃太多不健康。"],
    ["organic food", "/ɔːˈɡænɪk fuːd/", "有机食品", "🥬", "Organic food is more expensive.", "有机食品更贵。"],
    ["renewable energy", "/rɪˈnjuːəbl ˈenədʒi/", "可再生能源", "🔋", "The country invested in renewable energy.", "该国投资可再生能源。"],
    ["space exploration", "/speɪs ˌekspləˈreɪʃn/", "太空探索", "🚀", "Space exploration is costly.", "太空探索成本很高。"],
    ["genetic engineering", "/dʒəˈnetɪk ˌendʒɪˈnɪərɪŋ/", "基因工程", "🧬", "Genetic engineering raises ethics questions.", "基因工程引发伦理问题。"],
    ["artificial intelligence", "/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/", "人工智能", "🤖", "Artificial intelligence is transforming work.", "人工智能正在改变工作。"],
    ["climate change", "/ˈklaɪmət tʃeɪndʒ/", "气候变化", "🌍", "Climate change is a global issue.", "气候变化是全球问题。"],
    ["online shopping", "/ˌɒnlaɪn ˈʃɒpɪŋ/", "网购", "🛒", "Online shopping saves time.", "网购节省时间。"],
    ["social media", "/ˈsəʊʃl ˈmiːdiə/", "社交媒体", "📱", "Social media affects attention spans.", "社交媒体影响注意力。"],
    ["peer pressure", "/pɪə ˈpreʃə/", "同辈压力", "👥", "Teenagers face peer pressure.", "青少年面临同辈压力。"],
    ["gap between rich and poor", "/ɡæp bɪˈtwiːn rɪtʃ ənd pɔː/", "贫富差距", "📊", "The gap between rich and poor is widening.", "贫富差距在扩大。"],
  ]),
  ...pack({ category: "cooking", cluster: "kitchen", clusterName: "烹饪厨房", exam: "CET4", stage: "A2" }, [
    ["boil", "/bɔɪl/", "煮", "🫧", "Boil the water first.", "先把水烧开。", "v."],
    ["fry", "/fraɪ/", "煎；炒", "🍳", "Fry the eggs in oil.", "用油煎蛋。", "v."],
    ["bake", "/beɪk/", "烘烤", "🍞", "Bake the bread for 30 minutes.", "面包烤三十分钟。", "v."],
    ["grill", "/ɡrɪl/", "烧烤", "🔥", "Grill the fish outdoors.", "在户外烤鱼。", "v."],
    ["steam", "/stiːm/", "蒸", "♨️", "Steam the vegetables.", "把蔬菜蒸一下。", "v."],
    ["chop", "/tʃɒp/", "切碎", "🔪", "Chop the garlic.", "把蒜切碎。", "v."],
    ["stir", "/stɜː/", "搅拌", "🥄", "Stir the soup slowly.", "慢慢搅汤。", "v."],
    ["season", "/ˈsiːzn/", "调味", "🧂", "Season with salt and pepper.", "用盐和胡椒调味。", "v."],
    ["taste", "/teɪst/", "品尝", "👅", "Taste the sauce.", "尝尝酱汁。", "v."],
    ["serve", "/sɜːv/", "上菜", "🍽️", "Serve it hot.", "趁热上桌。", "v."],
    ["knife", "/naɪf/", "刀", "🔪", "Be careful with the knife.", "小心刀。"],
    ["fork", "/fɔːk/", "叉", "🍴", "Use a fork and knife.", "用刀叉。"],
    ["spoon", "/spuːn/", "勺", "🥄", "I need a bigger spoon.", "我需要更大的勺子。"],
    ["bowl", "/bəʊl/", "碗", "🥣", "Pour soup into the bowl.", "把汤倒进碗里。"],
    ["pan", "/pæn/", "平底锅", "🍳", "Heat the pan first.", "先把锅加热。"],
    ["pot", "/pɒt/", "锅", "🍲", "The pot is too small.", "这口锅太小。"],
    ["flour", "/ˈflaʊə/", "面粉", "🌾", "Add 200 grams of flour.", "加 200 克面粉。"],
    ["oil", "/ɔɪl/", "油", "🫒", "Use olive oil.", "用橄榄油。"],
    ["salt", "/sɔːlt/", "盐", "🧂", "Don't add too much salt.", "别放太多盐。"],
    ["sugar", "/ˈʃʊɡə/", "糖", "🍬", "This tea has no sugar.", "这茶没放糖。"],
  ]),
  ...pack({ category: "time", cluster: "calendar", clusterName: "时间日历", exam: "CET4", stage: "A1" }, [
    ["second", "/ˈsekənd/", "秒", "⏱️", "Wait a second.", "等一秒。"],
    ["minute", "/ˈmɪnɪt/", "分钟", "⏰", "It takes five minutes.", "要五分钟。"],
    ["hour", "/ˈaʊə/", "小时", "🕐", "The class lasts one hour.", "这节课一个小时。"],
    ["week", "/wiːk/", "周", "📆", "See you next week.", "下周见。"],
    ["month", "/mʌnθ/", "月", "🗓️", "I will travel next month.", "我下个月旅行。"],
    ["year", "/jɪə/", "年", "🎆", "This year is special.", "今年很特别。"],
    ["century", "/ˈsentʃəri/", "世纪", "🏛️", "It happened last century.", "那是上个世纪的事。"],
    ["dawn", "/dɔːn/", "黎明", "🌄", "We left at dawn.", "我们黎明出发。"],
    ["noon", "/nuːn/", "正午", "☀️", "Let's meet at noon.", "中午见。"],
    ["midnight", "/ˈmɪdnaɪt/", "午夜", "🌙", "The train arrives at midnight.", "火车午夜到。"],
    ["weekend", "/ˌwiːkˈend/", "周末", "🎉", "I relax at the weekend.", "我周末休息。"],
    ["schedule", "/ˈʃedjuːl/", "日程", "📋", "Check the schedule.", "看一下日程。"],
    ["punctual", "/ˈpʌŋktʃuəl/", "准时的", "⏰", "Please be punctual.", "请准时。", "adj."],
    ["delay", "/dɪˈleɪ/", "延误", "🐢", "Sorry for the delay.", "抱歉延误了。"],
    ["duration", "/djuˈreɪʃn/", "持续时间", "⏳", "The duration of the flight is 11 hours.", "飞行持续 11 小时。", "n.", ["tion"]],
    ["deadline", "/ˈdedlaɪn/", "截止时间", "📌", "The deadline is tight.", "截止日期很紧。"],
  ]),
];
