function R(meta, examples) {
  return { ...meta, examples };
}

export const roots = [
  R({ slug: "un", affix: "un-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "不，相反", meaningEn: "not / opposite", tip: "happy → unhappy，直接加在形容词前。", color: "#E07A5F", emoji: "🚫", stage: "A2" }, [
    { lemma: "unhappy", ipa: "/ʌnˈhæpi/", meaning: "不高兴的", emoji: "☹️", breakdown: "un + happy" },
    { lemma: "unfair", ipa: "/ʌnˈfeə/", meaning: "不公平的", emoji: "⚖️", breakdown: "un + fair" },
    { lemma: "unpack", ipa: "/ʌnˈpæk/", meaning: "打开行李", emoji: "👜", breakdown: "un + pack" },
    { lemma: "unclear", ipa: "/ʌnˈklɪə/", meaning: "不清楚的", emoji: "❔", breakdown: "un + clear" },
    { lemma: "unusual", ipa: "/ʌnˈjuːʒuəl/", meaning: "不寻常的", emoji: "🦄", breakdown: "un + usual" },
  ]),
  R({ slug: "dis", affix: "dis-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "否定，分开", meaningEn: "not / apart", tip: "agree → disagree。", color: "#C45C26", emoji: "🙅", stage: "A2" }, [
    { lemma: "disagree", ipa: "/ˌdɪsəˈɡriː/", meaning: "不同意", emoji: "🙅", breakdown: "dis + agree" },
    { lemma: "disable", ipa: "/dɪsˈeɪbl/", meaning: "禁用", emoji: "🚫", breakdown: "dis + able" },
    { lemma: "dislike", ipa: "/dɪsˈlaɪk/", meaning: "不喜欢", emoji: "👎", breakdown: "dis + like" },
    { lemma: "disappear", ipa: "/ˌdɪsəˈpɪə/", meaning: "消失", emoji: "👻", breakdown: "dis + appear" },
    { lemma: "discount", ipa: "/ˈdɪskaʊnt/", meaning: "折扣", emoji: "🏷️", breakdown: "dis + count" },
  ]),
  R({ slug: "in", affix: "in-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "不，向内", meaningEn: "not / into", tip: "correct → incorrect。在 b/m/p 前常变成 im-。", color: "#B45309", emoji: "⛔", stage: "B1" }, [
    { lemma: "incorrect", ipa: "/ˌɪnkəˈrekt/", meaning: "不正确的", emoji: "❌", breakdown: "in + correct" },
    { lemma: "invisible", ipa: "/ɪnˈvɪzəbl/", meaning: "看不见的", emoji: "🫥", breakdown: "in + vis + ible" },
    { lemma: "incomplete", ipa: "/ˌɪnkəmˈpliːt/", meaning: "不完整的", emoji: "🧩", breakdown: "in + complete" },
    { lemma: "informal", ipa: "/ɪnˈfɔːml/", meaning: "非正式的", emoji: "👕", breakdown: "in + formal" },
  ]),
  R({ slug: "im", affix: "im-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "不（在 b/m/p 前）", meaningEn: "not (before b/m/p)", tip: "possible → impossible。", color: "#9A3412", emoji: "🧱", stage: "B1" }, [
    { lemma: "impossible", ipa: "/ɪmˈpɒsəbl/", meaning: "不可能的", emoji: "🚫", breakdown: "im + possible" },
    { lemma: "impolite", ipa: "/ˌɪmpəˈlaɪt/", meaning: "不礼貌的", emoji: "😒", breakdown: "im + polite" },
    { lemma: "impatient", ipa: "/ɪmˈpeɪʃnt/", meaning: "不耐烦的", emoji: "😤", breakdown: "im + patient" },
    { lemma: "immature", ipa: "/ɪˈmətʃʊə/", meaning: "不成熟的", emoji: "🍼", breakdown: "im + mature" },
  ]),
  R({ slug: "non", affix: "non-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "非，无", meaningEn: "not / without", tip: "fiction → nonfiction，常带连字符。", color: "#7C2D12", emoji: "⭕", stage: "B1" }, [
    { lemma: "nonfiction", ipa: "/ˌnɒnˈfɪkʃn/", meaning: "非虚构", emoji: "📘", breakdown: "non + fiction" },
    { lemma: "nonprofit", ipa: "/ˌnɒnˈprɒfɪt/", meaning: "非营利的", emoji: "🤲", breakdown: "non + profit" },
    { lemma: "nonsense", ipa: "/ˈnɒnsns/", meaning: "胡说", emoji: "🗯️", breakdown: "non + sense" },
    { lemma: "nonstop", ipa: "/ˌnɒnˈstɒp/", meaning: "直达的", emoji: "✈️", breakdown: "non + stop" },
  ]),
  R({ slug: "mis", affix: "mis-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "错误地", meaningEn: "wrongly", tip: "understand → misunderstand。", color: "#A16207", emoji: "😵", stage: "B1" }, [
    { lemma: "misunderstand", ipa: "/ˌmɪsʌndəˈstænd/", meaning: "误解", emoji: "😵", breakdown: "mis + understand" },
    { lemma: "mistake", ipa: "/mɪˈsteɪk/", meaning: "错误", emoji: "❌", breakdown: "mis + take" },
    { lemma: "mislead", ipa: "/ˌmɪsˈliːd/", meaning: "误导", emoji: "↪️", breakdown: "mis + lead" },
    { lemma: "misspell", ipa: "/ˌmɪsˈspel/", meaning: "拼错", emoji: "🔤", breakdown: "mis + spell" },
  ]),
  R({ slug: "anti", affix: "anti-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "反对，抗", meaningEn: "against", tip: "virus → antivirus。", color: "#B91C1C", emoji: "🛡️", stage: "B1" }, [
    { lemma: "antivirus", ipa: "/ˌæntiˈvaɪrəs/", meaning: "杀毒的", emoji: "🛡️", breakdown: "anti + virus" },
    { lemma: "antibiotic", ipa: "/ˌæntibaɪˈɒtɪk/", meaning: "抗生素", emoji: "💊", breakdown: "anti + bio + tic" },
    { lemma: "antisocial", ipa: "/ˌæntiˈsəʊʃl/", meaning: "反社会的", emoji: "🐺", breakdown: "anti + social" },
    { lemma: "anticlockwise", ipa: "/ˌæntiˈklɒkwaɪz/", meaning: "逆时针", emoji: "↺", breakdown: "anti + clockwise" },
  ]),
  R({ slug: "de", affix: "de-", type: "prefix", family: "prefix", familyName: "前缀", group: "neg", groupName: "否定前缀", meaning: "去掉，向下", meaningEn: "remove / down", tip: "forest → deforest。", color: "#7F1D1D", emoji: "⬇️", stage: "B2" }, [
    { lemma: "deforest", ipa: "/ˌdiːˈfɒrɪst/", meaning: "砍伐森林", emoji: "🌲", breakdown: "de + forest" },
    { lemma: "decrease", ipa: "/dɪˈkriːs/", meaning: "减少", emoji: "📉", breakdown: "de + crease" },
    { lemma: "decode", ipa: "/ˌdiːˈkəʊd/", meaning: "解码", emoji: "🔓", breakdown: "de + code" },
    { lemma: "devalue", ipa: "/ˌdiːˈvæljuː/", meaning: "贬值", emoji: "💱", breakdown: "de + value" },
  ]),

  R({ slug: "re", affix: "re-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "再，重新", meaningEn: "again / back", tip: "write → rewrite。", color: "#3D7EA6", emoji: "🔁", stage: "A2" }, [
    { lemma: "rewrite", ipa: "/ˌriːˈraɪt/", meaning: "重写", emoji: "✍️", breakdown: "re + write" },
    { lemma: "return", ipa: "/rɪˈtɜːn/", meaning: "返回", emoji: "↩️", breakdown: "re + turn" },
    { lemma: "repeat", ipa: "/rɪˈpiːt/", meaning: "重复", emoji: "🔁", breakdown: "re + peat" },
    { lemma: "rebuild", ipa: "/ˌriːˈbɪld/", meaning: "重建", emoji: "🏗️", breakdown: "re + build" },
    { lemma: "recycle", ipa: "/ˌriːˈsaɪkl/", meaning: "回收", emoji: "♻️", breakdown: "re + cycle" },
  ]),
  R({ slug: "pre", affix: "pre-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "在……之前", meaningEn: "before", tip: "view → preview。", color: "#4A7C59", emoji: "⏮️", stage: "B1" }, [
    { lemma: "preview", ipa: "/ˈpriːvjuː/", meaning: "预习；预览", emoji: "👀", breakdown: "pre + view" },
    { lemma: "prepare", ipa: "/prɪˈpeə/", meaning: "准备", emoji: "🧳", breakdown: "pre + pare" },
    { lemma: "predict", ipa: "/prɪˈdɪkt/", meaning: "预测", emoji: "🔮", breakdown: "pre + dict" },
    { lemma: "prevent", ipa: "/prɪˈvent/", meaning: "预防", emoji: "🛡️", breakdown: "pre + vent" },
    { lemma: "preschool", ipa: "/ˈpriːskuːl/", meaning: "学前的", emoji: "🧸", breakdown: "pre + school" },
  ]),
  R({ slug: "post", affix: "post-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "在……之后", meaningEn: "after", tip: "war → postwar。", color: "#0F766E", emoji: "⏭️", stage: "B1" }, [
    { lemma: "postwar", ipa: "/ˌpəʊstˈwɔː/", meaning: "战后的", emoji: "🕊️", breakdown: "post + war" },
    { lemma: "postpone", ipa: "/pəˈspəʊn/", meaning: "推迟", emoji: "⏭️", breakdown: "post + pone" },
    { lemma: "postgraduate", ipa: "/ˌpəʊstˈɡrædʒuət/", meaning: "研究生", emoji: "🎓", breakdown: "post + graduate" },
    { lemma: "postscript", ipa: "/ˈpəʊstskrɪpt/", meaning: "附言 PS", emoji: "📝", breakdown: "post + script" },
  ]),
  R({ slug: "ex", affix: "ex-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "向外，前任", meaningEn: "out / former", tip: "port → export 出口。", color: "#0369A1", emoji: "📤", stage: "B1" }, [
    { lemma: "export", ipa: "/ɪkˈspɔːt/", meaning: "出口", emoji: "🚢", breakdown: "ex + port" },
    { lemma: "exit", ipa: "/ˈeksɪt/", meaning: "出口；离开", emoji: "🚪", breakdown: "ex + it" },
    { lemma: "exclude", ipa: "/ɪkˈskluːd/", meaning: "排除", emoji: "🚫", breakdown: "ex + clude" },
    { lemma: "expand", ipa: "/ɪkˈspænd/", meaning: "扩大", emoji: "📈", breakdown: "ex + pand" },
  ]),
  R({ slug: "sub", affix: "sub-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "在……之下", meaningEn: "under / below", tip: "way → subway。", color: "#1D4ED8", emoji: "⬇️", stage: "B1" }, [
    { lemma: "subway", ipa: "/ˈsʌbweɪ/", meaning: "地铁", emoji: "🚇", breakdown: "sub + way" },
    { lemma: "submarine", ipa: "/ˌsʌbməˈriːn/", meaning: "潜艇", emoji: "🚤", breakdown: "sub + marine" },
    { lemma: "subtitle", ipa: "/ˈsʌbtaɪtl/", meaning: "字幕；副标题", emoji: "💬", breakdown: "sub + title" },
    { lemma: "subtract", ipa: "/səbˈtrækt/", meaning: "减去", emoji: "➖", breakdown: "sub + tract" },
  ]),
  R({ slug: "trans", affix: "trans-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "穿过，转变", meaningEn: "across / change", tip: "port → transport。", color: "#6D28D9", emoji: "↔️", stage: "B1" }, [
    { lemma: "transport", ipa: "/ˈtrænspɔːt/", meaning: "运输", emoji: "🚚", breakdown: "trans + port" },
    { lemma: "translate", ipa: "/trænzˈleɪt/", meaning: "翻译", emoji: "🈯", breakdown: "trans + late" },
    { lemma: "transfer", ipa: "/trænsˈfɜː/", meaning: "转移；换乘", emoji: "🔁", breakdown: "trans + fer" },
    { lemma: "transform", ipa: "/trænsˈfɔːm/", meaning: "转变", emoji: "🦋", breakdown: "trans + form" },
  ]),
  R({ slug: "inter", affix: "inter-", type: "prefix", family: "prefix", familyName: "前缀", group: "time", groupName: "时间方向前缀", meaning: "在……之间", meaningEn: "between", tip: "national → international。", color: "#7C3AED", emoji: "🌐", stage: "B1" }, [
    { lemma: "international", ipa: "/ˌɪntəˈnæʃnəl/", meaning: "国际的", emoji: "🌐", breakdown: "inter + national" },
    { lemma: "internet", ipa: "/ˈɪntənet/", meaning: "互联网", emoji: "🕸️", breakdown: "inter + net" },
    { lemma: "interview", ipa: "/ˈɪntəvjuː/", meaning: "面试；采访", emoji: "🎤", breakdown: "inter + view" },
    { lemma: "interact", ipa: "/ˌɪntərˈækt/", meaning: "互动", emoji: "🤝", breakdown: "inter + act" },
  ]),
  R({ slug: "over", affix: "over-", type: "prefix", family: "prefix", familyName: "前缀", group: "degree", groupName: "程度数量前缀", meaning: "过度，在上", meaningEn: "too much / above", tip: "weight → overweight。", color: "#B45309", emoji: "📈", stage: "B1" }, [
    { lemma: "overweight", ipa: "/ˌəʊvəˈweɪt/", meaning: "超重的", emoji: "⚖️", breakdown: "over + weight" },
    { lemma: "overcome", ipa: "/ˌəʊvəˈkʌm/", meaning: "克服", emoji: "🧗", breakdown: "over + come" },
    { lemma: "overlook", ipa: "/ˌəʊvəˈlʊk/", meaning: "忽略；俯瞰", emoji: "🙈", breakdown: "over + look" },
    { lemma: "overtime", ipa: "/ˈəʊvətaɪm/", meaning: "加班", emoji: "🌙", breakdown: "over + time" },
  ]),
  R({ slug: "under", affix: "under-", type: "prefix", family: "prefix", familyName: "前缀", group: "degree", groupName: "程度数量前缀", meaning: "不足，在下", meaningEn: "too little / below", tip: "estimate → underestimate。", color: "#0F766E", emoji: "📉", stage: "B1" }, [
    { lemma: "underestimate", ipa: "/ˌʌndərˈestɪmeɪt/", meaning: "低估", emoji: "📉", breakdown: "under + estimate" },
    { lemma: "underground", ipa: "/ˌʌndəˈɡraʊnd/", meaning: "地下的", emoji: "🚇", breakdown: "under + ground" },
    { lemma: "underline", ipa: "/ˌʌndəˈlaɪn/", meaning: "划线；强调", emoji: "➖", breakdown: "under + line" },
    { lemma: "undergraduate", ipa: "/ˌʌndəˈɡrædʒuət/", meaning: "本科生", emoji: "🎓", breakdown: "under + graduate" },
  ]),
  R({ slug: "multi", affix: "multi-", type: "prefix", family: "prefix", familyName: "前缀", group: "degree", groupName: "程度数量前缀", meaning: "多", meaningEn: "many", tip: "cultural → multicultural。", color: "#7E22CE", emoji: "🌈", stage: "B1" }, [
    { lemma: "multicultural", ipa: "/ˌmʌltiˈkʌltʃərəl/", meaning: "多元文化的", emoji: "🌈", breakdown: "multi + cultural" },
    { lemma: "multimedia", ipa: "/ˌmʌltiˈmiːdiə/", meaning: "多媒体", emoji: "🎬", breakdown: "multi + media" },
    { lemma: "multinational", ipa: "/ˌmʌltiˈnæʃnəl/", meaning: "跨国的", emoji: "🏢", breakdown: "multi + national" },
    { lemma: "multiple", ipa: "/ˈmʌltɪpl/", meaning: "多个的", emoji: "🔢", breakdown: "multi + ple" },
  ]),
  R({ slug: "semi", affix: "semi-", type: "prefix", family: "prefix", familyName: "前缀", group: "degree", groupName: "程度数量前缀", meaning: "半", meaningEn: "half", tip: "final → semifinal。", color: "#0369A1", emoji: "🌗", stage: "B1" }, [
    { lemma: "semifinal", ipa: "/ˌsemiˈfaɪnl/", meaning: "半决赛", emoji: "🥈", breakdown: "semi + final" },
    { lemma: "semicircle", ipa: "/ˈsemisɜːkl/", meaning: "半圆", emoji: "◐", breakdown: "semi + circle" },
    { lemma: "semiconductor", ipa: "/ˌsemikənˈdʌktə/", meaning: "半导体", emoji: "💠", breakdown: "semi + conductor" },
  ]),
  R({ slug: "micro", affix: "micro-", type: "prefix", family: "prefix", familyName: "前缀", group: "degree", groupName: "程度数量前缀", meaning: "微小", meaningEn: "small", tip: "scope → microscope。", color: "#155E75", emoji: "🔬", stage: "B2" }, [
    { lemma: "microscope", ipa: "/ˈmaɪkrəskəʊp/", meaning: "显微镜", emoji: "🔬", breakdown: "micro + scope" },
    { lemma: "microwave", ipa: "/ˈmaɪkrəweɪv/", meaning: "微波炉", emoji: "📻", breakdown: "micro + wave" },
    { lemma: "microchip", ipa: "/ˈmaɪkrəʊtʃɪp/", meaning: "芯片", emoji: "💾", breakdown: "micro + chip" },
  ]),

  R({ slug: "able", affix: "-able", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "能够……的", meaningEn: "capable of", tip: "看见 able，先想「能不能」。", color: "#3D8B6E", emoji: "✅", stage: "A2" }, [
    { lemma: "able", ipa: "/ˈeɪbl/", meaning: "能够的", emoji: "✅", breakdown: "able" },
    { lemma: "disable", ipa: "/dɪsˈeɪbl/", meaning: "禁用", emoji: "🚫", breakdown: "dis + able" },
    { lemma: "enable", ipa: "/ɪˈneɪbl/", meaning: "使能够", emoji: "🟢", breakdown: "en + able" },
    { lemma: "comfortable", ipa: "/ˈkʌmftəbl/", meaning: "舒服的", emoji: "😌", breakdown: "comfort + able" },
    { lemma: "available", ipa: "/əˈveɪləbl/", meaning: "可获得的", emoji: "🟢", breakdown: "avail + able" },
    { lemma: "portable", ipa: "/ˈpɔːtəbl/", meaning: "便携的", emoji: "🔋", breakdown: "port + able" },
  ]),
  R({ slug: "ful", affix: "-ful", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "充满……的", meaningEn: "full of", tip: "care → careful。", color: "#D4A017", emoji: "💛", stage: "A2" }, [
    { lemma: "careful", ipa: "/ˈkeəfl/", meaning: "小心的", emoji: "⚠️", breakdown: "care + ful" },
    { lemma: "helpful", ipa: "/ˈhelpfl/", meaning: "有帮助的", emoji: "🤗", breakdown: "help + ful" },
    { lemma: "grateful", ipa: "/ˈɡreɪtfl/", meaning: "感激的", emoji: "🙏", breakdown: "grate + ful" },
    { lemma: "powerful", ipa: "/ˈpaʊəfl/", meaning: "强大的", emoji: "💪", breakdown: "power + ful" },
    { lemma: "beautiful", ipa: "/ˈbjuːtɪfl/", meaning: "美丽的", emoji: "🌸", breakdown: "beauty + ful" },
  ]),
  R({ slug: "less", affix: "-less", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "没有……的", meaningEn: "without", tip: "和 -ful 成对：hopeful / hopeless。", color: "#2A9D8F", emoji: "🕳️", stage: "A2" }, [
    { lemma: "hopeless", ipa: "/ˈhəʊpləs/", meaning: "没有希望的", emoji: "🌧️", breakdown: "hope + less" },
    { lemma: "wireless", ipa: "/ˈwaɪələs/", meaning: "无线的", emoji: "📡", breakdown: "wire + less" },
    { lemma: "homeless", ipa: "/ˈhəʊmləs/", meaning: "无家可归的", emoji: "🏚️", breakdown: "home + less" },
    { lemma: "careless", ipa: "/ˈkeələs/", meaning: "粗心的", emoji: "🙄", breakdown: "care + less" },
    { lemma: "endless", ipa: "/ˈendləs/", meaning: "无穷的", emoji: "♾️", breakdown: "end + less" },
  ]),
  R({ slug: "ive", affix: "-ive", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "有……性质的", meaningEn: "having the nature of", tip: "act → active。", color: "#7C3AED", emoji: "⚡", stage: "B1" }, [
    { lemma: "active", ipa: "/ˈæktɪv/", meaning: "积极的", emoji: "⚡", breakdown: "act + ive" },
    { lemma: "creative", ipa: "/kriˈeɪtɪv/", meaning: "有创造力的", emoji: "🎨", breakdown: "create + ive" },
    { lemma: "effective", ipa: "/ɪˈfektɪv/", meaning: "有效的", emoji: "🎯", breakdown: "effect + ive" },
    { lemma: "expensive", ipa: "/ɪkˈspensɪv/", meaning: "昂贵的", emoji: "💎", breakdown: "expend + ive" },
  ]),
  R({ slug: "ous", affix: "-ous", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "充满……的", meaningEn: "full of", tip: "danger → dangerous。", color: "#B45309", emoji: "⚠️", stage: "B1" }, [
    { lemma: "dangerous", ipa: "/ˈdeɪndʒərəs/", meaning: "危险的", emoji: "⚠️", breakdown: "danger + ous" },
    { lemma: "famous", ipa: "/ˈfeɪməs/", meaning: "著名的", emoji: "🌟", breakdown: "fame + ous" },
    { lemma: "various", ipa: "/ˈveəriəs/", meaning: "各种各样的", emoji: "🌈", breakdown: "vary + ous" },
    { lemma: "curious", ipa: "/ˈkjʊəriəs/", meaning: "好奇的", emoji: "🧐", breakdown: "curi + ous" },
  ]),
  R({ slug: "al", affix: "-al", type: "suffix", family: "suffix", familyName: "后缀", group: "adj", groupName: "形容词后缀", meaning: "……的", meaningEn: "relating to", tip: "nation → national。", color: "#1D4ED8", emoji: "🏷️", stage: "B1" }, [
    { lemma: "national", ipa: "/ˈnæʃnəl/", meaning: "国家的", emoji: "🏳️", breakdown: "nation + al" },
    { lemma: "personal", ipa: "/ˈpɜːsənl/", meaning: "个人的", emoji: "👤", breakdown: "person + al" },
    { lemma: "cultural", ipa: "/ˈkʌltʃərəl/", meaning: "文化的", emoji: "🎭", breakdown: "culture + al" },
    { lemma: "legal", ipa: "/ˈliːɡl/", meaning: "合法的", emoji: "⚖️", breakdown: "leg + al" },
  ]),

  R({ slug: "tion", affix: "-tion", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "行为或状态", meaningEn: "action or state", tip: "act → action。", color: "#6B5B95", emoji: "📦", stage: "B1" }, [
    { lemma: "action", ipa: "/ˈækʃn/", meaning: "行动", emoji: "🎬", breakdown: "act + tion" },
    { lemma: "information", ipa: "/ˌɪnfəˈmeɪʃn/", meaning: "信息", emoji: "ℹ️", breakdown: "inform + ation" },
    { lemma: "education", ipa: "/ˌedʒuˈkeɪʃn/", meaning: "教育", emoji: "🎓", breakdown: "educate + tion" },
    { lemma: "pollution", ipa: "/pəˈluːʃn/", meaning: "污染", emoji: "🏭", breakdown: "pollute + tion" },
    { lemma: "reservation", ipa: "/ˌrezəˈveɪʃn/", meaning: "预订", emoji: "📅", breakdown: "reserve + ation" },
  ]),
  R({ slug: "ment", affix: "-ment", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "行为或结果", meaningEn: "result / action", tip: "develop → development。", color: "#0F766E", emoji: "🧱", stage: "B1" }, [
    { lemma: "development", ipa: "/dɪˈveləpmənt/", meaning: "发展", emoji: "📈", breakdown: "develop + ment" },
    { lemma: "government", ipa: "/ˈɡʌvnmənt/", meaning: "政府", emoji: "🏛️", breakdown: "govern + ment" },
    { lemma: "environment", ipa: "/ɪnˈvaɪrənmənt/", meaning: "环境", emoji: "🌍", breakdown: "environ + ment" },
    { lemma: "assignment", ipa: "/əˈsaɪnmənt/", meaning: "作业", emoji: "📝", breakdown: "assign + ment" },
    { lemma: "investment", ipa: "/ɪnˈvestmənt/", meaning: "投资", emoji: "💰", breakdown: "invest + ment" },
  ]),
  R({ slug: "ness", affix: "-ness", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "性质，状态", meaningEn: "quality / state", tip: "happy → happiness。", color: "#DB2777", emoji: "💗", stage: "A2" }, [
    { lemma: "happiness", ipa: "/ˈhæpinəs/", meaning: "幸福", emoji: "😊", breakdown: "happy + ness" },
    { lemma: "kindness", ipa: "/ˈkaɪndnəs/", meaning: "善良", emoji: "💗", breakdown: "kind + ness" },
    { lemma: "darkness", ipa: "/ˈdɑːknəs/", meaning: "黑暗", emoji: "🌑", breakdown: "dark + ness" },
    { lemma: "weakness", ipa: "/ˈwiːknəs/", meaning: "弱点", emoji: "🫠", breakdown: "weak + ness" },
  ]),
  R({ slug: "ity", affix: "-ity", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "性质", meaningEn: "quality", tip: "active → activity。", color: "#7C3AED", emoji: "🏷️", stage: "B1" }, [
    { lemma: "activity", ipa: "/ækˈtɪvəti/", meaning: "活动", emoji: "🏃", breakdown: "active + ity" },
    { lemma: "ability", ipa: "/əˈbɪləti/", meaning: "能力", emoji: "💪", breakdown: "able + ity" },
    { lemma: "equality", ipa: "/iˈkwɒləti/", meaning: "平等", emoji: "⚖️", breakdown: "equal + ity" },
    { lemma: "diversity", ipa: "/daɪˈvɜːsəti/", meaning: "多样性", emoji: "🌈", breakdown: "diverse + ity" },
  ]),
  R({ slug: "er", affix: "-er / -or", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "做……的人", meaningEn: "person who", tip: "teach → teacher；act → actor。", color: "#C45C26", emoji: "👤", stage: "A2" }, [
    { lemma: "teacher", ipa: "/ˈtiːtʃə/", meaning: "老师", emoji: "👩‍🏫", breakdown: "teach + er" },
    { lemma: "waiter", ipa: "/ˈweɪtə/", meaning: "服务员", emoji: "👨‍🍳", breakdown: "wait + er" },
    { lemma: "actor", ipa: "/ˈæktə/", meaning: "演员", emoji: "🎭", breakdown: "act + or" },
    { lemma: "editor", ipa: "/ˈedɪtə/", meaning: "编辑", emoji: "✏️", breakdown: "edit + or" },
  ]),
  R({ slug: "ist", affix: "-ist", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "从事……的人", meaningEn: "person / specialist", tip: "art → artist；science → scientist。", color: "#1E3A5F", emoji: "🎨", stage: "B1" }, [
    { lemma: "artist", ipa: "/ˈɑːtɪst/", meaning: "艺术家", emoji: "🎨", breakdown: "art + ist" },
    { lemma: "scientist", ipa: "/ˈsaɪəntɪst/", meaning: "科学家", emoji: "🔬", breakdown: "science + ist" },
    { lemma: "journalist", ipa: "/ˈdʒɜːnəlɪst/", meaning: "记者", emoji: "🎤", breakdown: "journal + ist" },
    { lemma: "tourist", ipa: "/ˈtʊərɪst/", meaning: "游客", emoji: "🧳", breakdown: "tour + ist" },
  ]),
  R({ slug: "ism", affix: "-ism", type: "suffix", family: "suffix", familyName: "后缀", group: "noun", groupName: "名词后缀", meaning: "主义，现象", meaningEn: "belief / system", tip: "capital → capitalism。", color: "#7F1D1D", emoji: "📜", stage: "B2" }, [
    { lemma: "tourism", ipa: "/ˈtʊərɪzəm/", meaning: "旅游业", emoji: "✈️", breakdown: "tour + ism" },
    { lemma: "journalism", ipa: "/ˈdʒɜːnəlɪzəm/", meaning: "新闻业", emoji: "📰", breakdown: "journal + ism" },
    { lemma: "criticism", ipa: "/ˈkrɪtɪsɪzəm/", meaning: "批评", emoji: "🗯️", breakdown: "critic + ism" },
    { lemma: "mechanism", ipa: "/ˈmekənɪzəm/", meaning: "机制", emoji: "⚙️", breakdown: "mechan + ism" },
  ]),

  R({ slug: "ize", affix: "-ize", type: "suffix", family: "suffix", familyName: "后缀", group: "verb", groupName: "动词后缀", meaning: "使……化", meaningEn: "to make", tip: "modern → modernize。", color: "#0E7490", emoji: "🔧", stage: "B1" }, [
    { lemma: "modernize", ipa: "/ˈmɒdənaɪz/", meaning: "使现代化", emoji: "🏙️", breakdown: "modern + ize" },
    { lemma: "organize", ipa: "/ˈɔːɡənaɪz/", meaning: "组织", emoji: "📋", breakdown: "organ + ize" },
    { lemma: "realize", ipa: "/ˈriːəlaɪz/", meaning: "意识到", emoji: "💡", breakdown: "real + ize" },
    { lemma: "emphasize", ipa: "/ˈemfəsaɪz/", meaning: "强调", emoji: "❗", breakdown: "emphasis + ize" },
  ]),
  R({ slug: "ify", affix: "-ify", type: "suffix", family: "suffix", familyName: "后缀", group: "verb", groupName: "动词后缀", meaning: "使成为", meaningEn: "to make into", tip: "simple → simplify。", color: "#155E75", emoji: "🪄", stage: "B1" }, [
    { lemma: "simplify", ipa: "/ˈsɪmplɪfaɪ/", meaning: "简化", emoji: "🪄", breakdown: "simple + ify" },
    { lemma: "identify", ipa: "/aɪˈdentɪfaɪ/", meaning: "识别", emoji: "🆔", breakdown: "ident + ify" },
    { lemma: "classify", ipa: "/ˈklæsɪfaɪ/", meaning: "分类", emoji: "📂", breakdown: "class + ify" },
    { lemma: "justify", ipa: "/ˈdʒʌstɪfaɪ/", meaning: "证明合理", emoji: "✅", breakdown: "just + ify" },
  ]),
  R({ slug: "en", affix: "-en", type: "suffix", family: "suffix", familyName: "后缀", group: "verb", groupName: "动词后缀", meaning: "使变得", meaningEn: "to make / become", tip: "wide → widen；short → shorten。", color: "#3F6212", emoji: "↔️", stage: "B1" }, [
    { lemma: "widen", ipa: "/ˈwaɪdn/", meaning: "加宽", emoji: "↔️", breakdown: "wide + en" },
    { lemma: "shorten", ipa: "/ˈʃɔːtn/", meaning: "缩短", emoji: "✂️", breakdown: "short + en" },
    { lemma: "strengthen", ipa: "/ˈstreŋθn/", meaning: "加强", emoji: "💪", breakdown: "strength + en" },
    { lemma: "weaken", ipa: "/ˈwiːkən/", meaning: "削弱", emoji: "🫠", breakdown: "weak + en" },
  ]),

  R({ slug: "port", affix: "port", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "运送，携带", meaningEn: "carry", tip: "portable = 能被带走的。", color: "#1E6B48", emoji: "🧳", stage: "B1" }, [
    { lemma: "portable", ipa: "/ˈpɔːtəbl/", meaning: "便携的", emoji: "🔋", breakdown: "port + able" },
    { lemma: "transport", ipa: "/ˈtrænspɔːt/", meaning: "运输", emoji: "🚚", breakdown: "trans + port" },
    { lemma: "export", ipa: "/ɪkˈspɔːt/", meaning: "出口", emoji: "🚢", breakdown: "ex + port" },
    { lemma: "import", ipa: "/ɪmˈpɔːt/", meaning: "进口", emoji: "📦", breakdown: "im + port" },
    { lemma: "passport", ipa: "/ˈpɑːspɔːt/", meaning: "护照", emoji: "🛂", breakdown: "pass + port" },
  ]),
  R({ slug: "spect", affix: "spect / vis", type: "root", family: "root", familyName: "词根", group: "sense", groupName: "感知词根", meaning: "看", meaningEn: "see / look", tip: "inspect = 向里看；television = 远距离看。", color: "#7C3AED", emoji: "👀", stage: "B1" }, [
    { lemma: "inspect", ipa: "/ɪnˈspekt/", meaning: "检查", emoji: "🔍", breakdown: "in + spect" },
    { lemma: "respect", ipa: "/rɪˈspekt/", meaning: "尊重", emoji: "🙇", breakdown: "re + spect" },
    { lemma: "expect", ipa: "/ɪkˈspekt/", meaning: "期待", emoji: "🤞", breakdown: "ex + spect" },
    { lemma: "television", ipa: "/ˈtelɪvɪʒn/", meaning: "电视", emoji: "📺", breakdown: "tele + vis" },
    { lemma: "visible", ipa: "/ˈvɪzəbl/", meaning: "可见的", emoji: "👁️", breakdown: "vis + ible" },
  ]),
  R({ slug: "dict", affix: "dict", type: "root", family: "root", familyName: "词根", group: "sense", groupName: "感知词根", meaning: "说", meaningEn: "say / speak", tip: "predict = 预先说。", color: "#C45C26", emoji: "🗣️", stage: "B1" }, [
    { lemma: "predict", ipa: "/prɪˈdɪkt/", meaning: "预测", emoji: "🔮", breakdown: "pre + dict" },
    { lemma: "dictionary", ipa: "/ˈdɪkʃənri/", meaning: "词典", emoji: "📕", breakdown: "dict + ionary" },
    { lemma: "dictate", ipa: "/dɪkˈteɪt/", meaning: "口述；支配", emoji: "📢", breakdown: "dict + ate" },
    { lemma: "contradict", ipa: "/ˌkɒntrəˈdɪkt/", meaning: "反驳", emoji: "⚔️", breakdown: "contra + dict" },
  ]),
  R({ slug: "aud", affix: "aud", type: "root", family: "root", familyName: "词根", group: "sense", groupName: "感知词根", meaning: "听", meaningEn: "hear", tip: "audience = 听的人。", color: "#0E7490", emoji: "👂", stage: "B1" }, [
    { lemma: "audience", ipa: "/ˈɔːdiəns/", meaning: "听众；观众", emoji: "👥", breakdown: "aud + ience" },
    { lemma: "audio", ipa: "/ˈɔːdiəʊ/", meaning: "音频", emoji: "🔊", breakdown: "aud + io" },
    { lemma: "audit", ipa: "/ˈɔːdɪt/", meaning: "审计", emoji: "🔍", breakdown: "aud + it" },
    { lemma: "audible", ipa: "/ˈɔːdəbl/", meaning: "听得见的", emoji: "👂", breakdown: "aud + ible" },
  ]),
  R({ slug: "phon", affix: "phon", type: "root", family: "root", familyName: "词根", group: "sense", groupName: "感知词根", meaning: "声音", meaningEn: "sound", tip: "telephone = 远处的声音。", color: "#0369A1", emoji: "🔊", stage: "B1" }, [
    { lemma: "telephone", ipa: "/ˈtelɪfəʊn/", meaning: "电话", emoji: "☎️", breakdown: "tele + phon" },
    { lemma: "microphone", ipa: "/ˈmaɪkrəfəʊn/", meaning: "麦克风", emoji: "🎤", breakdown: "micro + phon" },
    { lemma: "symphony", ipa: "/ˈsɪmfəni/", meaning: "交响乐", emoji: "🎼", breakdown: "sym + phon + y" },
    { lemma: "phonetic", ipa: "/fəˈnetɪk/", meaning: "语音的", emoji: "🔤", breakdown: "phon + etic" },
  ]),
  R({ slug: "duc", affix: "duc / duct", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "引导", meaningEn: "lead", tip: "educate = 把人引导出来。", color: "#1D4ED8", emoji: "➡️", stage: "B2" }, [
    { lemma: "educate", ipa: "/ˈedʒukeɪt/", meaning: "教育", emoji: "🎓", breakdown: "e + duc + ate" },
    { lemma: "produce", ipa: "/prəˈdjuːs/", meaning: "生产", emoji: "🏭", breakdown: "pro + duc" },
    { lemma: "introduce", ipa: "/ˌɪntrəˈdjuːs/", meaning: "介绍", emoji: "👋", breakdown: "intro + duc" },
    { lemma: "conduct", ipa: "/kənˈdʌkt/", meaning: "实施；指挥", emoji: "🎼", breakdown: "con + duct" },
  ]),
  R({ slug: "ject", affix: "ject", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "投，抛", meaningEn: "throw", tip: "reject = 扔回去。", color: "#B91C1C", emoji: "🎯", stage: "B2" }, [
    { lemma: "reject", ipa: "/rɪˈdʒekt/", meaning: "拒绝", emoji: "🚫", breakdown: "re + ject" },
    { lemma: "project", ipa: "/ˈprɒdʒekt/", meaning: "项目；投射", emoji: "📁", breakdown: "pro + ject" },
    { lemma: "inject", ipa: "/ɪnˈdʒekt/", meaning: "注射", emoji: "💉", breakdown: "in + ject" },
    { lemma: "subject", ipa: "/ˈsʌbdʒɪkt/", meaning: "主题；科目", emoji: "📘", breakdown: "sub + ject" },
  ]),
  R({ slug: "scrib", affix: "scrib / script", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "写", meaningEn: "write", tip: "describe = 把样子写下来。", color: "#6B5B95", emoji: "✍️", stage: "B1" }, [
    { lemma: "describe", ipa: "/dɪˈskraɪb/", meaning: "描述", emoji: "✍️", breakdown: "de + scrib" },
    { lemma: "prescribe", ipa: "/prɪˈskraɪb/", meaning: "开处方", emoji: "💊", breakdown: "pre + scrib" },
    { lemma: "script", ipa: "/skrɪpt/", meaning: "剧本；脚本", emoji: "🎬", breakdown: "script" },
    { lemma: "manuscript", ipa: "/ˈmænjuskrɪpt/", meaning: "手稿", emoji: "📜", breakdown: "manu + script" },
  ]),
  R({ slug: "tract", affix: "tract", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "拉", meaningEn: "pull", tip: "attract = 拉过来。", color: "#A16207", emoji: "🧲", stage: "B2" }, [
    { lemma: "attract", ipa: "/əˈtrækt/", meaning: "吸引", emoji: "🧲", breakdown: "at + tract" },
    { lemma: "contract", ipa: "/ˈkɒntrækt/", meaning: "合同；收缩", emoji: "📝", breakdown: "con + tract" },
    { lemma: "subtract", ipa: "/səbˈtrækt/", meaning: "减去", emoji: "➖", breakdown: "sub + tract" },
    { lemma: "abstract", ipa: "/ˈæbstrækt/", meaning: "抽象的", emoji: "🌫️", breakdown: "abs + tract" },
  ]),
  R({ slug: "form", affix: "form", type: "root", family: "root", familyName: "词根", group: "action", groupName: "动作词根", meaning: "形状", meaningEn: "shape", tip: "transform = 改变形状。", color: "#0F766E", emoji: "🦋", stage: "B1" }, [
    { lemma: "transform", ipa: "/trænsˈfɔːm/", meaning: "转变", emoji: "🦋", breakdown: "trans + form" },
    { lemma: "inform", ipa: "/ɪnˈfɔːm/", meaning: "通知", emoji: "ℹ️", breakdown: "in + form" },
    { lemma: "reform", ipa: "/rɪˈfɔːm/", meaning: "改革", emoji: "🔧", breakdown: "re + form" },
    { lemma: "formal", ipa: "/ˈfɔːml/", meaning: "正式的", emoji: "👔", breakdown: "form + al" },
  ]),
  R({ slug: "bio", affix: "bio", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "生命", meaningEn: "life", tip: "biology = 研究生命的学科。", color: "#15803D", emoji: "🧬", stage: "B1" }, [
    { lemma: "biology", ipa: "/baɪˈɒlədʒi/", meaning: "生物学", emoji: "🧬", breakdown: "bio + logy" },
    { lemma: "biography", ipa: "/baɪˈɒɡrəfi/", meaning: "传记", emoji: "📖", breakdown: "bio + graph + y" },
    { lemma: "biodiversity", ipa: "/ˌbaɪəʊdaɪˈvɜːsəti/", meaning: "生物多样性", emoji: "🦋", breakdown: "bio + diversity" },
    { lemma: "antibiotic", ipa: "/ˌæntibaɪˈɒtɪk/", meaning: "抗生素", emoji: "💊", breakdown: "anti + bio + tic" },
  ]),
  R({ slug: "geo", affix: "geo", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "地球", meaningEn: "earth", tip: "geography = 描写地球。", color: "#3F6212", emoji: "🌍", stage: "B1" }, [
    { lemma: "geography", ipa: "/dʒiˈɒɡrəfi/", meaning: "地理", emoji: "🗺️", breakdown: "geo + graph + y" },
    { lemma: "geology", ipa: "/dʒiˈɒlədʒi/", meaning: "地质学", emoji: "🪨", breakdown: "geo + logy" },
    { lemma: "geometry", ipa: "/dʒiˈɒmətri/", meaning: "几何", emoji: "📐", breakdown: "geo + metry" },
    { lemma: "geographic", ipa: "/ˌdʒiːəˈɡræfɪk/", meaning: "地理的", emoji: "🌏", breakdown: "geo + graphic" },
  ]),
  R({ slug: "log", affix: "log / logy", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "学科，言语", meaningEn: "study / speech", tip: "biology、psychology 都是 -logy。", color: "#4338CA", emoji: "📘", stage: "B1" }, [
    { lemma: "biology", ipa: "/baɪˈɒlədʒi/", meaning: "生物学", emoji: "🧬", breakdown: "bio + logy" },
    { lemma: "psychology", ipa: "/saɪˈkɒlədʒi/", meaning: "心理学", emoji: "🧠", breakdown: "psycho + logy" },
    { lemma: "logic", ipa: "/ˈlɒdʒɪk/", meaning: "逻辑", emoji: "🧩", breakdown: "log + ic" },
    { lemma: "dialogue", ipa: "/ˈdaɪəlɒɡ/", meaning: "对话", emoji: "💬", breakdown: "dia + logue" },
  ]),
  R({ slug: "graph", affix: "graph", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "写，画", meaningEn: "write / draw", tip: "photograph = 用光来画。", color: "#0E7490", emoji: "🖼️", stage: "B1" }, [
    { lemma: "photograph", ipa: "/ˈfəʊtəɡrɑːf/", meaning: "照片", emoji: "📷", breakdown: "photo + graph" },
    { lemma: "autograph", ipa: "/ˈɔːtəɡrɑːf/", meaning: "亲笔签名", emoji: "✒️", breakdown: "auto + graph" },
    { lemma: "paragraph", ipa: "/ˈpærəɡrɑːf/", meaning: "段落", emoji: "📄", breakdown: "para + graph" },
    { lemma: "graphics", ipa: "/ˈɡræfɪks/", meaning: "图形", emoji: "🎨", breakdown: "graph + ics" },
  ]),
  R({ slug: "chron", affix: "chron", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "时间", meaningEn: "time", tip: "chronic = 和时间相关的、长期的。", color: "#1E3A5F", emoji: "⏳", stage: "B2" }, [
    { lemma: "chronic", ipa: "/ˈkrɒnɪk/", meaning: "慢性的", emoji: "📆", breakdown: "chron + ic" },
    { lemma: "chronicle", ipa: "/ˈkrɒnɪkl/", meaning: "编年史", emoji: "📜", breakdown: "chron + icle" },
    { lemma: "synchronize", ipa: "/ˈsɪŋkrənaɪz/", meaning: "同步", emoji: "🔄", breakdown: "syn + chron + ize" },
    { lemma: "chronology", ipa: "/krəˈnɒlədʒi/", meaning: "年表", emoji: "📅", breakdown: "chron + ology" },
  ]),
  R({ slug: "tele", affix: "tele", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "远", meaningEn: "far", tip: "telephone、television 都是「远」。", color: "#0369A1", emoji: "📡", stage: "A2" }, [
    { lemma: "telephone", ipa: "/ˈtelɪfəʊn/", meaning: "电话", emoji: "☎️", breakdown: "tele + phon" },
    { lemma: "television", ipa: "/ˈtelɪvɪʒn/", meaning: "电视", emoji: "📺", breakdown: "tele + vis" },
    { lemma: "telescope", ipa: "/ˈtelɪskəʊp/", meaning: "望远镜", emoji: "🔭", breakdown: "tele + scope" },
    { lemma: "telegram", ipa: "/ˈtelɪɡræm/", meaning: "电报", emoji: "📨", breakdown: "tele + gram" },
  ]),
  R({ slug: "auto", affix: "auto", type: "root", family: "root", familyName: "词根", group: "study", groupName: "学科词根", meaning: "自己", meaningEn: "self", tip: "automatic = 自己动。", color: "#334155", emoji: "🤖", stage: "B1" }, [
    { lemma: "automatic", ipa: "/ˌɔːtəˈmætɪk/", meaning: "自动的", emoji: "🤖", breakdown: "auto + matic" },
    { lemma: "automobile", ipa: "/ˈɔːtəməbiːl/", meaning: "汽车", emoji: "🚗", breakdown: "auto + mobile" },
    { lemma: "autograph", ipa: "/ˈɔːtəɡrɑːf/", meaning: "亲笔签名", emoji: "✒️", breakdown: "auto + graph" },
    { lemma: "autonomy", ipa: "/ɔːˈtɒnəmi/", meaning: "自主", emoji: "🗽", breakdown: "auto + nomy" },
  ]),
  R({ slug: "bene", affix: "bene", type: "root", family: "root", familyName: "词根", group: "quality", groupName: "性质词根", meaning: "好", meaningEn: "good", tip: "benefit = 好处。", color: "#15803D", emoji: "🎁", stage: "B2" }, [
    { lemma: "benefit", ipa: "/ˈbenɪfɪt/", meaning: "益处", emoji: "🎁", breakdown: "bene + fit" },
    { lemma: "beneficial", ipa: "/ˌbenɪˈfɪʃl/", meaning: "有益的", emoji: "✅", breakdown: "bene + ficial" },
    { lemma: "benevolent", ipa: "/bəˈnevələnt/", meaning: "仁慈的", emoji: "💗", breakdown: "bene + volent" },
  ]),
  R({ slug: "mal", affix: "mal", type: "root", family: "root", familyName: "词根", group: "quality", groupName: "性质词根", meaning: "坏", meaningEn: "bad", tip: "和 bene 成对记。", color: "#B91C1C", emoji: "☠️", stage: "B2" }, [
    { lemma: "malfunction", ipa: "/ˌmælˈfʌŋkʃn/", meaning: "故障", emoji: "⚠️", breakdown: "mal + function" },
    { lemma: "malnutrition", ipa: "/ˌmælnjuˈtrɪʃn/", meaning: "营养不良", emoji: "🥣", breakdown: "mal + nutrition" },
    { lemma: "malicious", ipa: "/məˈlɪʃəs/", meaning: "恶意的", emoji: "😈", breakdown: "mal + icious" },
  ]),
];
