function scene(data) {
  return data;
}

export const scenarios = [
  scene({
    slug: "coffee",
    title: "咖啡馆点单",
    titleEn: "At the Café",
    emoji: "☕",
    place: "Coffee shop",
    description: "点美式、说热冷、加奶少糖，是最容易开口的日常场景。",
    stage: "A1",
    usefulPhrases: [
      { en: "Can I have a coffee, please?", zh: "请给我一杯咖啡。", ipa: "/kæn aɪ hæv ə ˈkɒfi/" },
      { en: "For here or to go?", zh: "在店里喝还是带走？", ipa: "/fə hɪə ɔː tə ɡəʊ/" },
      { en: "I'd like it iced.", zh: "我要冰的。", ipa: "/aɪd laɪk ɪt aɪst/" },
      { en: "No sugar, please.", zh: "请不要加糖。", ipa: "/nəʊ ˈʃʊɡə pliːz/" },
      { en: "Can I pay by card?", zh: "可以刷卡吗？", ipa: "/kæn aɪ peɪ baɪ kɑːd/" },
      { en: "Could I have the wifi password?", zh: "能告诉我无线网密码吗？", ipa: "/kəd aɪ hæv ðə ˈwaɪfaɪ ˈpɑːswɜːd/" },
    ],
    dialogue: [
      { speaker: "Barista", en: "Hi! What can I get for you?", zh: "您好，要点什么？", ipa: "/haɪ wɒt kæn aɪ ɡet fə juː/" },
      { speaker: "You", en: "A medium latte, please.", zh: "请给我一杯中杯拿铁。", ipa: "/ə ˈmiːdiəm ˈlæteɪ pliːz/" },
      { speaker: "Barista", en: "Hot or iced?", zh: "热的还是冰的？", ipa: "/hɒt ɔː aɪst/" },
      { speaker: "You", en: "Iced, please. And oat milk if you have it.", zh: "冰的。如果有燕麦奶就用燕麦奶。", ipa: "/aɪst pliːz ənd əʊt mɪlk/" },
      { speaker: "Barista", en: "Sure. Any sugar or syrup?", zh: "好的。要加糖或糖浆吗？", ipa: "/ʃʊə ˈeni ˈʃʊɡə ɔː ˈsɪrəp/" },
      { speaker: "You", en: "No sugar, thanks. For here.", zh: "不加糖，谢谢。在店里喝。", ipa: "/nəʊ ˈʃʊɡə θæŋks fə hɪə/" },
      { speaker: "Barista", en: "That's 4.50. Card or cash?", zh: "4.5 元。刷卡还是现金？", ipa: "/ðæts ˈfɔː ˈfɪfti kɑːd ɔː kæʃ/" },
      { speaker: "You", en: "Card, please. And what's the wifi password?", zh: "刷卡。无线网密码是多少？", ipa: "/kɑːd pliːz ənd wɒts ðə ˈwaɪfaɪ ˈpɑːswɜːd/" },
      { speaker: "Barista", en: "It's coffee123. I'll call your name when it's ready.", zh: "是 coffee123。做好了会叫您。", ipa: "/ɪts ˈkɒfi wʌn tuː θriː/" },
      { speaker: "You", en: "Thanks. I'll wait by the window.", zh: "谢谢，我在窗边等。", ipa: "/θæŋks aɪl weɪt baɪ ðə ˈwɪndəʊ/" },
    ],
    quizzes: [
      { question: "点单时最自然的说法是？", options: ["Give me coffee now.", "Can I have a coffee, please?", "I must coffee.", "Coffee to me."], answer: 1, explain: "Can I have … please? 礼貌又常用。" },
      { question: "to go 的意思是？", options: ["在店里喝", "带走", "免费续杯", "加冰"], answer: 1, explain: "to go = 外带。" },
      { question: "不想加糖该说？", options: ["More sugar, please.", "No sugar, please.", "It's spicy.", "Check-out please."], answer: 1, explain: "No sugar, please." },
      { question: "barista 是？", options: ["服务员（餐厅）", "咖啡师", "机长", "前台"], answer: 1, explain: "barista 专指咖啡馆做咖啡的人。" },
      { question: "iced latte 是？", options: ["热拿铁", "冰拿铁", "无咖啡因", "脱因美式"], answer: 1, explain: "iced 表示冰的。" },
      { question: "刷卡怎么说？", options: ["Pay by cash", "Pay by card", "Pay by gate", "Pay by room"], answer: 1, explain: "pay by card。" },
      { question: "For here 表示？", options: ["外带", "店内用餐", "打包明天", "送到酒店"], answer: 1, explain: "for here 是在店里喝。" },
      { question: "做好了会叫名字，对应哪句？", options: ["I'll call your name when it's ready.", "Boarding starts at 10:30.", "Here's your key.", "Stay near the shore."], answer: 0, explain: "咖啡馆常说 I'll call your name。" },
    ],
  }),
  scene({
    slug: "supermarket",
    title: "超市购物",
    titleEn: "At the Supermarket",
    emoji: "🛒",
    place: "Supermarket",
    description: "找货架、问促销、自助结账，把蔬菜水果词立刻用上。",
    stage: "A1",
    usefulPhrases: [
      { en: "Where can I find the milk?", zh: "牛奶在哪？", ipa: "/weə kæn aɪ faɪnd ðə mɪlk/" },
      { en: "Is this on sale?", zh: "这个在打折吗？", ipa: "/ɪz ðɪs ɒn seɪl/" },
      { en: "I need a bag, please.", zh: "请给我一个袋子。", ipa: "/aɪ niːd ə bæɡ/" },
      { en: "Do you take cards?", zh: "可以刷卡吗？", ipa: "/duː ju teɪk kɑːdz/" },
      { en: "That's all, thanks.", zh: "就这些，谢谢。", ipa: "/ðæts ɔːl θæŋks/" },
      { en: "Can I have a receipt?", zh: "可以给我收据吗？", ipa: "/kæn aɪ hæv ə rɪˈsiːt/" },
    ],
    dialogue: [
      { speaker: "You", en: "Excuse me, where is the fruit section?", zh: "请问水果区在哪里？", ipa: "/ɪkˈskjuːz miː weə ɪz ðə fruːt ˈsekʃn/" },
      { speaker: "Staff", en: "Aisle 3, on your left.", zh: "第三通道，在您左边。", ipa: "/aɪl θriː ɒn jɔː left/" },
      { speaker: "You", en: "Thanks. Are these apples on sale?", zh: "谢谢。这些苹果在打折吗？", ipa: "/θæŋks ɑː ðiːz ˈæplz ɒn seɪl/" },
      { speaker: "Staff", en: "Yes. Buy one kilo, get 20% off.", zh: "是的。买一公斤打八折。", ipa: "/jes baɪ wʌn ˈkiːləʊ ɡet ˈtwenti pəˈsent ɒf/" },
      { speaker: "You", en: "Great. I'll take these tomatoes too.", zh: "太好了。这些番茄我也要。", ipa: "/ɡreɪt aɪl teɪk ðiːz təˈmɑːtəʊz tuː/" },
      { speaker: "Staff", en: "The self-checkout is over there if you're ready.", zh: "如果选好了，自助收银台在那边。", ipa: "/ðə self ˈtʃekaʊt ɪz ˈəʊvə ðeə/" },
      { speaker: "You", en: "I think I need a cashier. I also have a bottle of water.", zh: "我还是找人工吧，我还有一瓶水。", ipa: "/aɪ θɪŋk aɪ niːd ə kæˈʃɪə/" },
      { speaker: "Cashier", en: "That's 8.20. Would you like a bag?", zh: "一共 8.20。要袋子吗？", ipa: "/ðæts eɪt ˈtwenti wəd ju laɪk ə bæɡ/" },
      { speaker: "You", en: "Yes, please. And a receipt.", zh: "要的，再给我一张收据。", ipa: "/jes pliːz ənd ə rɪˈsiːt/" },
      { speaker: "Cashier", en: "Here you are. Have a nice day!", zh: "给您。祝您愉快！", ipa: "/hɪə juː ɑː hæv ə naɪs deɪ/" },
    ],
    quizzes: [
      { question: "aisle 在超市里指？", options: ["收银台", "货架通道", "停车场", "试衣间"], answer: 1, explain: "aisle 是货架之间的通道。" },
      { question: "on sale 表示？", options: ["售罄", "打折促销", "进口货", "冷冻食品"], answer: 1, explain: "on sale = 特价。" },
      { question: "receipt 是？", options: ["发票/收据", "优惠券", "会员卡", "购物袋"], answer: 0, explain: "receipt 是购物凭证。" },
      { question: "self-checkout 是？", options: ["人工通道", "自助结账", "退货处", "客服台"], answer: 1, explain: "自己扫码付款。" },
      { question: "问牛奶在哪，最合适的是？", options: ["Where can I find the milk?", "How much is the gate?", "I'd like a quiet room.", "Is it safe to swim?"], answer: 0, explain: "Where can I find … 用来找货。" },
      { question: "20% off 的意思是？", options: ["加价两成", "打八折", "买二送一", "免费"], answer: 1, explain: "off 表示减免，20% off 即八折。" },
      { question: "That's all 在结账时表示？", options: ["我还要很多", "就这些", "我不要袋子", "我走错店了"], answer: 1, explain: "告诉收银员没有别的了。" },
      { question: "cashier 是？", options: ["保安", "收银员", "厨师", "飞行员"], answer: 1, explain: "cashier 负责收款。" },
    ],
  }),
  scene({
    slug: "taxi",
    title: "坐出租车",
    titleEn: "Taking a Taxi",
    emoji: "🚕",
    place: "Taxi",
    description: "报目的地、系安全带、刷卡付钱，落地后马上能用。",
    stage: "A1",
    usefulPhrases: [
      { en: "Could you take me to the airport?", zh: "请送我去机场。", ipa: "/kəd ju teɪk miː tə ði ˈeəpɔːt/" },
      { en: "How long will it take?", zh: "大概要多久？", ipa: "/haʊ lɒŋ wɪl ɪt teɪk/" },
      { en: "Please drop me off here.", zh: "请在这里让我下车。", ipa: "/pliːz drɒp miː ɒf hɪə/" },
      { en: "Can I pay by card?", zh: "可以刷卡吗？", ipa: "/kæn aɪ peɪ baɪ kɑːd/" },
      { en: "Keep the change.", zh: "不用找了。", ipa: "/kiːp ðə tʃeɪndʒ/" },
      { en: "Could you slow down a little?", zh: "能开慢一点吗？", ipa: "/kəd ju sləʊ daʊn ə ˈlɪtl/" },
    ],
    dialogue: [
      { speaker: "You", en: "Taxi! Are you free?", zh: "出租车！有空吗？", ipa: "/ˈtæksi ɑː ju friː/" },
      { speaker: "Driver", en: "Yes. Where to?", zh: "有。去哪儿？", ipa: "/jes weə tuː/" },
      { speaker: "You", en: "The Grand Hotel, please. On King Street.", zh: "请去格兰酒店，在国王街。", ipa: "/ðə ɡrænd həʊˈtel ɒn kɪŋ striːt/" },
      { speaker: "Driver", en: "Got it. Please put on your seat belt.", zh: "好的。请系好安全带。", ipa: "/ɡɒt ɪt pliːz pʊt ɒn jɔː siːt belt/" },
      { speaker: "You", en: "How long will it take in this traffic?", zh: "这会儿堵车大概要多久？", ipa: "/haʊ lɒŋ wɪl ɪt teɪk ɪn ðɪs ˈtræfɪk/" },
      { speaker: "Driver", en: "About twenty minutes. I'll take a faster route.", zh: "大约二十分钟。我走更快的路。", ipa: "/əˈbaʊt ˈtwenti ˈmɪnɪts/" },
      { speaker: "You", en: "Great. Could you drop me at the main entrance?", zh: "太好了。请在正门口停。", ipa: "/ɡreɪt kəd ju drɒp miː ət ðə meɪn ˈentrəns/" },
      { speaker: "Driver", en: "Sure. That's 18 dollars.", zh: "没问题。一共 18 美元。", ipa: "/ʃʊə ðæts ˈeɪtiːn ˈdɒləz/" },
      { speaker: "You", en: "I'll pay by card. Here's a small tip.", zh: "我刷卡。这是一点小费。", ipa: "/aɪl peɪ baɪ kɑːd hɪəz ə smɔːl tɪp/" },
      { speaker: "Driver", en: "Thank you. Have a good stay!", zh: "谢谢。祝您住得愉快！", ipa: "/θæŋk juː hæv ə ɡʊd steɪ/" },
    ],
    quizzes: [
      { question: "司机问 Where to? 是在问？", options: ["几点出发", "去哪里", "行李多重", "能否刷卡"], answer: 1, explain: "Where to? = 去哪儿？" },
      { question: "seat belt 是？", options: ["座椅加热", "安全带", "后备箱", "发票"], answer: 1, explain: "seat belt = 安全带。" },
      { question: "drop me off 表示？", options: ["接我上班", "让我下车", "帮我搬行李", "绕路"], answer: 1, explain: "drop off 是在某地放下乘客。" },
      { question: "How long will it take? 问的是？", options: ["多少钱", "要多久", "车号多少", "能不能停车"], answer: 1, explain: "问耗时。" },
      { question: "Keep the change 的意思是？", options: ["请找零", "不用找了", "请开发票", "请开慢点"], answer: 1, explain: "把零钱当小费。" },
      { question: "tip 在出租车场景里多指？", options: ["建议", "小费", "路线", "罚单"], answer: 1, explain: "这里是小费。" },
      { question: "请开慢点该说？", options: ["Speed up, please.", "Could you slow down a little?", "Turn off the meter.", "Get out here."], answer: 1, explain: "slow down = 减速。" },
      { question: "Are you free? 对出租车司机是在问？", options: ["你下班了吗", "这辆车有空吗", "车费免费吗", "你认识我吗"], answer: 1, explain: "free 表示这辆车没载客。" },
    ],
  }),
  scene({
    slug: "directions",
    title: "问路指路",
    titleEn: "Asking for Directions",
    emoji: "🗺️",
    place: "City street",
    description: "左转右转、过马路、走路几分钟，迷路时最管用。",
    stage: "A1",
    usefulPhrases: [
      { en: "Excuse me, how do I get to the station?", zh: "请问去车站怎么走？", ipa: "/ɪkˈskjuːz miː haʊ duː aɪ ɡet tə ðə ˈsteɪʃn/" },
      { en: "Go straight ahead.", zh: "一直往前走。", ipa: "/ɡəʊ streɪt əˈhed/" },
      { en: "Turn left at the traffic lights.", zh: "在红绿灯处左转。", ipa: "/tɜːn left ət ðə ˈtræfɪk laɪts/" },
      { en: "It's on your right.", zh: "就在你右边。", ipa: "/ɪts ɒn jɔː raɪt/" },
      { en: "Is it within walking distance?", zh: "走路能到吗？", ipa: "/ɪz ɪt wɪˈðɪn ˈwɔːkɪŋ ˈdɪstəns/" },
      { en: "Could you show me on the map?", zh: "能在地图上指给我看吗？", ipa: "/kəd ju ʃəʊ miː ɒn ðə mæp/" },
    ],
    dialogue: [
      { speaker: "You", en: "Excuse me, I'm looking for the city museum.", zh: "打扰一下，我在找城市博物馆。", ipa: "/ɪkˈskjuːz miː aɪm ˈlʊkɪŋ fə ðə ˈsɪti mjuˈziːəm/" },
      { speaker: "Local", en: "It's not far. Go straight for two blocks.", zh: "不远。一直走两个街区。", ipa: "/ɪts nɒt fɑː ɡəʊ streɪt fə tuː blɒks/" },
      { speaker: "You", en: "Then what?", zh: "然后呢？", ipa: "/ðen wɒt/" },
      { speaker: "Local", en: "Turn right at the traffic lights. You'll see a park.", zh: "红绿灯处右转，你会看到一座公园。", ipa: "/tɜːn raɪt ət ðə ˈtræfɪk laɪts/" },
      { speaker: "You", en: "Is the museum next to the park?", zh: "博物馆就在公园旁边吗？", ipa: "/ɪz ðə mjuˈziːəm nekst tə ðə pɑːk/" },
      { speaker: "Local", en: "Yes, on your left. About eight minutes on foot.", zh: "对，在你左边。走路大约八分钟。", ipa: "/jes ɒn jɔː left əˈbaʊt eɪt ˈmɪnɪts/" },
      { speaker: "You", en: "Should I take the subway instead?", zh: "要不要改坐地铁？", ipa: "/ʃəd aɪ teɪk ðə ˈsʌbweɪ ɪnˈsted/" },
      { speaker: "Local", en: "No need. It's within walking distance.", zh: "不用，走路就到。", ipa: "/nəʊ niːd ɪts wɪˈðɪn ˈwɔːkɪŋ ˈdɪstəns/" },
      { speaker: "You", en: "Thanks a lot. Have a nice day!", zh: "非常感谢。祝你愉快！", ipa: "/θæŋks ə lɒt/" },
      { speaker: "Local", en: "You're welcome. Don't miss the gift shop.", zh: "不客气。别错过礼品店。", ipa: "/jɔː ˈwelkəm dəʊnt mɪs ðə ɡɪft ʃɒp/" },
    ],
    quizzes: [
      { question: "How do I get to … 用来？", options: ["点餐", "问路", "退房", "安检"], answer: 1, explain: "这是问路的标准句。" },
      { question: "Go straight ahead 的意思是？", options: ["掉头", "直行", "坐电梯", "过马路"], answer: 1, explain: "straight ahead = 一直往前。" },
      { question: "traffic lights 是？", options: ["路灯", "红绿灯", "霓虹灯", "手电筒"], answer: 1, explain: "traffic lights = 交通信号灯。" },
      { question: "on your right 表示？", options: ["在你左边", "在你右边", "在你身后", "在地下"], answer: 1, explain: "right = 右边。" },
      { question: "on foot 的意思是？", options: ["开车", "走路", "骑车", "坐船"], answer: 1, explain: "on foot = 步行。" },
      { question: "within walking distance 表示？", options: ["必须打车", "走路就到", "只能地铁", "隔了一座山"], answer: 1, explain: "步行距离之内。" },
      { question: "two blocks 里的 block 指？", options: ["积木", "街区", "障碍", "大楼电梯"], answer: 1, explain: "城市里一个街区叫 a block。" },
      { question: "next to 表示？", options: ["对面", "旁边", "里面", "楼上"], answer: 1, explain: "next to = 紧挨着。" },
    ],
  }),
  scene({
    slug: "hotel",
    title: "入住酒店",
    titleEn: "Hotel Check-in",
    emoji: "🏨",
    place: "Hotel lobby",
    description: "报预订、要房型、问早餐和无线网，落地后第一段对话。",
    stage: "A2",
    usefulPhrases: [
      { en: "I have a reservation.", zh: "我有预订。", ipa: "/aɪ hæv ə ˌrezəˈveɪʃn/" },
      { en: "I'd like a quiet room, please.", zh: "我想要一间安静的房间。", ipa: "/aɪd laɪk ə ˈkwaɪət ruːm/" },
      { en: "What's the wifi password?", zh: "无线网密码是多少？", ipa: "/wɒts ðə ˈwaɪfaɪ ˈpɑːswɜːd/" },
      { en: "Is breakfast included?", zh: "含早餐吗？", ipa: "/ɪz ˈbrekfəst ɪnˈkluːdɪd/" },
      { en: "Could I have a late check-out?", zh: "可以延迟退房吗？", ipa: "/kəd aɪ hæv ə leɪt tʃek aʊt/" },
      { en: "The air conditioner isn't working.", zh: "空调坏了。", ipa: "/ði eə kənˈdɪʃnə ˈɪznt ˈwɜːkɪŋ/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hello. I have a reservation under Chen.", zh: "你好，我用陈的名字订了房。", ipa: "/həˈləʊ aɪ hæv ə ˌrezəˈveɪʃn ˈʌndə tʃen/" },
      { speaker: "Staff", en: "Welcome. May I see your passport, please?", zh: "欢迎。请出示您的护照。", ipa: "/ˈwelkəm meɪ aɪ siː jɔː ˈpɑːspɔːt/" },
      { speaker: "You", en: "Sure. Here you are. I booked a double room.", zh: "好的，给您。我订的是双人房。", ipa: "/ʃʊə hɪə juː ɑː aɪ bʊkt ə ˈdʌbl ruːm/" },
      { speaker: "Staff", en: "A quiet double is available on the third floor.", zh: "三楼有一间安静的双人房。", ipa: "/ə ˈkwaɪət ˈdʌbl ɪz əˈveɪləbl/" },
      { speaker: "You", en: "That's great. Is breakfast included?", zh: "太好了。含早餐吗？", ipa: "/ðæts ɡreɪt ɪz ˈbrekfəst ɪnˈkluːdɪd/" },
      { speaker: "Staff", en: "Yes, from 7 to 10 in the restaurant. Here's your key.", zh: "含，餐厅 7 点到 10 点。这是房卡。", ipa: "/jes frəm ˈsevn tə ten/" },
      { speaker: "You", en: "What's the wifi password?", zh: "无线网密码是多少？", ipa: "/wɒts ðə ˈwaɪfaɪ ˈpɑːswɜːd/" },
      { speaker: "Staff", en: "It's hotel2026. The gym is in the basement.", zh: "是 hotel2026。健身房在地下室。", ipa: "/ɪts həʊˈtel tuː əʊ tuː sɪks/" },
      { speaker: "You", en: "Could I have two extra towels, please?", zh: "能再给我两条毛巾吗？", ipa: "/kəd aɪ hæv tuː ˈekstrə ˈtaʊəlz/" },
      { speaker: "Staff", en: "Of course. I'll send them up in ten minutes.", zh: "当然。十分钟内送到房间。", ipa: "/əv kɔːs aɪl send ðəm ʌp/" },
    ],
    quizzes: [
      { question: "办理入住时，工作人员最可能要看什么？", options: ["Menu", "Passport", "Sunscreen", "Ticket"], answer: 1, explain: "入住通常需要护照或身份证件。" },
      { question: "“I have a reservation.” 的意思是？", options: ["我要退房", "我有预订", "我要菜单", "我要登机"], answer: 1, explain: "reservation 表示预订。" },
      { question: "想问退房时间，该说？", options: ["What time is check-in?", "What time is check-out?", "Where is the beach?", "How much is the bill?"], answer: 1, explain: "check-out 是退房。" },
      { question: "double room 是？", options: ["单人房", "双人房", "套房", "宿舍"], answer: 1, explain: "double 常指双人床房。" },
      { question: "included 在 Is breakfast included? 里表示？", options: ["另外收费", "已包含", "需要预约", "已取消"], answer: 1, explain: "included = 包含在内。" },
      { question: "extra towels 指？", options: ["额外毛巾", "额外枕头", "洗衣袋", "拖鞋"], answer: 0, explain: "extra 额外；towel 毛巾。" },
      { question: "空调坏了该说？", options: ["The TV is loud.", "The air conditioner isn't working.", "I need a window seat.", "The waves are big."], answer: 1, explain: "isn't working 表示设备故障。" },
      { question: "late check-out 的意思是？", options: ["提前入住", "延迟退房", "取消订单", "升级套房"], answer: 1, explain: "晚一点再退房。" },
    ],
  }),
  scene({
    slug: "airport",
    title: "机场值机",
    titleEn: "At the Airport",
    emoji: "✈️",
    place: "Airport",
    description: "值机、托运、找登机口，出国最高频的一段英语。",
    stage: "A2",
    usefulPhrases: [
      { en: "Where is the check-in counter?", zh: "值机柜台在哪里？", ipa: "/weə ɪz ðə tʃek ɪn ˈkaʊntə/" },
      { en: "I'd like a window seat, please.", zh: "我想要靠窗的座位。", ipa: "/aɪd laɪk ə ˈwɪndəʊ siːt/" },
      { en: "Is this the way to gate 12?", zh: "这是去 12 号登机口的路吗？", ipa: "/ɪz ðɪs ðə weɪ tə ɡeɪt twelv/" },
      { en: "My luggage is a bit heavy.", zh: "我的行李有点重。", ipa: "/maɪ ˈlʌɡɪdʒ ɪz ə bɪt ˈhevi/" },
      { en: "Do I need to take off my shoes?", zh: "需要脱鞋吗？", ipa: "/duː aɪ niːd tə teɪk ɒf maɪ ʃuːz/" },
      { en: "Has boarding started yet?", zh: "开始登机了吗？", ipa: "/hæz ˈbɔːdɪŋ ˈstɑːtɪd jet/" },
    ],
    dialogue: [
      { speaker: "You", en: "Excuse me, where can I check in for flight CA981?", zh: "请问 CA981 在哪里值机？", ipa: "/ɪkˈskjuːz miː weə kæn aɪ tʃek ɪn/" },
      { speaker: "Staff", en: "Please go to counter 21. Have your passport ready.", zh: "请到 21 号柜台，准备好护照。", ipa: "/pliːz ɡəʊ tə ˈkaʊntə ˈtwenti wʌn/" },
      { speaker: "You", en: "Can I take this bag as carry-on luggage?", zh: "这个包可以当手提行李吗？", ipa: "/kæn aɪ teɪk ðɪs bæɡ əz ˈkæri ɒn ˈlʌɡɪdʒ/" },
      { speaker: "Staff", en: "Yes. Please put your suitcase on the scale.", zh: "可以。请把行李箱放到秤上。", ipa: "/jes pliːz pʊt jɔː ˈsuːtkeɪs ɒn ðə skeɪl/" },
      { speaker: "You", en: "I'd like a window seat if possible.", zh: "如果可以，我想要靠窗座位。", ipa: "/aɪd laɪk ə ˈwɪndəʊ siːt/" },
      { speaker: "Staff", en: "Done. Here's your boarding pass. Gate 18.", zh: "好了。这是登机牌，18 号口。", ipa: "/dʌn hɪəz jɔː ˈbɔːdɪŋ pɑːs/" },
      { speaker: "You", en: "What time does boarding start?", zh: "几点开始登机？", ipa: "/wɒt taɪm dəz ˈbɔːdɪŋ stɑːt/" },
      { speaker: "Staff", en: "At 10:30. Security is that way.", zh: "10:30。安检往那边走。", ipa: "/ət ˈten ˈθɜːti sɪˈkjʊərəti ɪz ðæt weɪ/" },
      { speaker: "You", en: "Do I need to take out my laptop?", zh: "笔记本电脑要拿出来吗？", ipa: "/duː aɪ niːd tə teɪk aʊt maɪ ˈlæptɒp/" },
      { speaker: "Staff", en: "Yes, and any liquids over 100 ml.", zh: "要的，超过 100 毫升的液体也要拿出来。", ipa: "/jes ənd ˈeni ˈlɪkwɪdz ˈəʊvə wʌn ˈhʌndrəd/" },
    ],
    quizzes: [
      { question: "登机口用英语怎么说？", options: ["Window", "Gate", "Counter", "Scale"], answer: 1, explain: "gate 在机场就是登机口。" },
      { question: "想要靠窗座位该说？", options: ["I'd like a window seat.", "I'd like a spicy dish.", "I'd like a quiet room.", "I'd like the bill."], answer: 0, explain: "window seat = 靠窗座位。" },
      { question: "luggage 的意思是？", options: ["护照", "行李", "登机口", "菜单"], answer: 1, explain: "luggage 是行李（不可数）。" },
      { question: "boarding pass 是？", options: ["护照", "登机牌", "行李票", "签证"], answer: 1, explain: "boarding pass 用来登机。" },
      { question: "carry-on 指？", options: ["托运行李", "手提行李", "超重费", "延误证明"], answer: 1, explain: "带上飞机的小件行李。" },
      { question: "scale 在值机柜台旁是？", options: ["安检门", "秤", "传送带终点", "VIP 室"], answer: 1, explain: "用来称行李重量。" },
      { question: "boarding 的意思是？", options: ["值机", "登机", "落地", "转机"], answer: 1, explain: "board the plane = 登机。" },
      { question: "liquids over 100 ml 通常要？", options: ["放口袋里", "单独拿出来过安检", "托运到酒店", "丢掉护照"], answer: 1, explain: "液体超 100 毫升有安检规定。" },
    ],
  }),
  scene({
    slug: "restaurant",
    title: "餐厅点餐",
    titleEn: "Ordering Food",
    emoji: "🍽️",
    place: "Restaurant",
    description: "订位、问推荐、说忌口、结账，把餐饮词立刻用起来。",
    stage: "A2",
    usefulPhrases: [
      { en: "A table for two, please.", zh: "请安排两人桌。", ipa: "/ə ˈteɪbl fə tuː pliːz/" },
      { en: "What do you recommend?", zh: "有什么推荐？", ipa: "/wɒt də ju ˌrekəˈmend/" },
      { en: "I'm allergic to peanuts.", zh: "我对花生过敏。", ipa: "/aɪm əˈlɜːdʒɪk tə ˈpiːnʌts/" },
      { en: "Could we have the bill, please?", zh: "请结账。", ipa: "/kəd wi hæv ðə bɪl/" },
      { en: "Can we split the bill?", zh: "可以分开付吗？", ipa: "/kæn wi splɪt ðə bɪl/" },
      { en: "This isn't what I ordered.", zh: "这不是我点的。", ipa: "/ðɪs ˈɪznt wɒt aɪ ˈɔːdəd/" },
    ],
    dialogue: [
      { speaker: "Waiter", en: "Hi! Do you have a reservation?", zh: "您好，有预订吗？", ipa: "/haɪ duː ju hæv ə ˌrezəˈveɪʃn/" },
      { speaker: "You", en: "Yes, under Chen. A table for two.", zh: "有，姓陈，两人桌。", ipa: "/jes ˈʌndə tʃen ə ˈteɪbl fə tuː/" },
      { speaker: "Waiter", en: "This way, please. Are you ready to order?", zh: "请这边走。可以点餐了吗？", ipa: "/ðɪs weɪ pliːz ɑː ju ˈredi tə ˈɔːdə/" },
      { speaker: "You", en: "What do you recommend today?", zh: "今天有什么推荐？", ipa: "/wɒt də ju ˌrekəˈmend təˈdeɪ/" },
      { speaker: "Waiter", en: "The tomato soup and grilled fish are popular.", zh: "番茄汤和烤鱼很受欢迎。", ipa: "/ðə təˈmɑːtəʊ suːp ənd ɡrɪld fɪʃ/" },
      { speaker: "You", en: "I'll have the soup and a salad. Not spicy, please.", zh: "我要汤和沙拉。请不要辣。", ipa: "/aɪl hæv ðə suːp ənd ə ˈsæləd/" },
      { speaker: "Waiter", en: "Anything to drink? And any allergies?", zh: "喝点什么？有过敏吗？", ipa: "/ˈeniθɪŋ tə drɪŋk ənd ˈeni ˈælədʒiz/" },
      { speaker: "You", en: "Water, please. I'm allergic to peanuts.", zh: "水。我对花生过敏。", ipa: "/ˈwɔːtə pliːz aɪm əˈlɜːdʒɪk tə ˈpiːnʌts/" },
      { speaker: "Waiter", en: "Noted. I'll make sure the kitchen knows.", zh: "记下了，我会告知厨房。", ipa: "/ˈnəʊtɪd aɪl meɪk ʃʊə ðə ˈkɪtʃɪn nəʊz/" },
      { speaker: "You", en: "Thanks. Could we have the bill later?", zh: "谢谢。稍后请结账。", ipa: "/θæŋks kəd wi hæv ðə bɪl ˈleɪtə/" },
    ],
    quizzes: [
      { question: "点餐时 “What do you recommend?” 是在？", options: ["抱怨", "询问推荐", "要水", "问路"], answer: 1, explain: "recommend 是推荐。" },
      { question: "不想吃辣该说？", options: ["Very spicy, please.", "Not spicy, please.", "I need a gate.", "Check-out please."], answer: 1, explain: "Not spicy, please. 明确说不辣。" },
      { question: "bill 在餐厅里指？", options: ["账单", "账单夹里的鸟", "登机牌", "房卡"], answer: 0, explain: "Could we have the bill = 请结账。" },
      { question: "I'm allergic to peanuts 是在说？", options: ["我喜欢花生", "我对花生过敏", "花生售罄", "花生很辣"], answer: 1, explain: "allergic to = 对……过敏。" },
      { question: "A table for two 表示？", options: ["两道菜", "两人桌", "两点开门", "第二桌"], answer: 1, explain: "for two = 两个人。" },
      { question: "split the bill 的意思是？", options: ["逃单", "AA 制分开付", "只要水单", "打包剩菜"], answer: 1, explain: "split 表示分摊。" },
      { question: "This isn't what I ordered 用于？", options: ["夸奖厨师", "上错菜", "预约座位", "要菜单"], answer: 1, explain: "不是我点的那份。" },
      { question: "grilled fish 是？", options: ["生鱼片", "烤鱼", "鱼汤", "炸薯条"], answer: 1, explain: "grill 是烤。" },
    ],
  }),
  scene({
    slug: "beach",
    title: "海边度假",
    titleEn: "Beach Trip",
    emoji: "🏖️",
    place: "Seaside",
    description: "租椅子、问海浪、买水防晒，把度假聊起来。",
    stage: "A2",
    usefulPhrases: [
      { en: "Is it safe to swim here?", zh: "这里游泳安全吗？", ipa: "/ɪz ɪt seɪf tə swɪm hɪə/" },
      { en: "I'd like to rent a beach umbrella.", zh: "我想租一把沙滩伞。", ipa: "/aɪd laɪk tə rent ə biːtʃ ʌmˈbrelə/" },
      { en: "Where can I buy sunscreen?", zh: "哪里能买到防晒霜？", ipa: "/weə kæn aɪ baɪ ˈsʌnskriːn/" },
      { en: "The sunset is beautiful.", zh: "日落真美。", ipa: "/ðə ˈsʌnset ɪz ˈbjuːtɪfl/" },
      { en: "How much is it for the day?", zh: "租一天多少钱？", ipa: "/haʊ mʌtʃ ɪz ɪt fə ðə deɪ/" },
      { en: "Where are the restrooms?", zh: "洗手间在哪？", ipa: "/weə ɑː ðə ˈrestruːmz/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi! Can I rent two chairs and an umbrella?", zh: "你好，我能租两把椅子和一把伞吗？", ipa: "/haɪ kæn aɪ rent tuː tʃeəz/" },
      { speaker: "Staff", en: "Of course. That's 20 dollars for the day.", zh: "当然。一天 20 美元。", ipa: "/əv kɔːs ðæts ˈtwenti ˈdɒləz/" },
      { speaker: "You", en: "Is it safe to swim now? The waves look big.", zh: "现在游泳安全吗？浪看起来挺大。", ipa: "/ɪz ɪt seɪf tə swɪm naʊ/" },
      { speaker: "Staff", en: "It's better to stay near the shore. There's a red flag today.", zh: "最好待在岸边。今天挂了红旗。", ipa: "/ɪts ˈbetə tə steɪ nɪə ðə ʃɔː/" },
      { speaker: "You", en: "Thanks. Where can I get some cold water?", zh: "谢谢。哪里能买到冰水？", ipa: "/θæŋks weə kæn aɪ ɡet səm kəʊld ˈwɔːtə/" },
      { speaker: "Staff", en: "There's a small shop behind you. They also sell sunscreen.", zh: "你身后有家小店，也卖防晒霜。", ipa: "/ðeəz ə smɔːl ʃɒp bɪˈhaɪnd juː/" },
      { speaker: "You", en: "Do you have lockers for valuables?", zh: "有存放贵重物品的柜子吗？", ipa: "/duː ju hæv ˈlɒkəz fə ˈvæljuəblz/" },
      { speaker: "Staff", en: "Yes, 3 dollars. Keep the key with you.", zh: "有，3 美元。钥匙请随身带着。", ipa: "/jes θriː ˈdɒləz kiːp ðə kiː/" },
      { speaker: "You", en: "Perfect. Where are the restrooms?", zh: "太好了。洗手间在哪？", ipa: "/ˈpɜːfɪkt weə ɑː ðə ˈrestruːmz/" },
      { speaker: "Staff", en: "Next to the lifeguard tower.", zh: "在救生塔旁边。", ipa: "/nekst tə ðə ˈlaɪfɡɑːd ˈtaʊə/" },
    ],
    quizzes: [
      { question: "sunscreen 是什么？", options: ["太阳镜", "防晒霜", "沙滩椅", "海浪"], answer: 1, explain: "sun + screen，挡住阳光。" },
      { question: "想问能不能游泳，最合适的是？", options: ["Is it safe to swim here?", "Can I have the bill?", "Where is gate 12?", "I'd like a double room."], answer: 0, explain: "直接问是否安全。" },
      { question: "wave 在海边的意思是？", options: ["挥手", "海浪", "微波加热", "告别"], answer: 1, explain: "海滩语境下优先理解为海浪。" },
      { question: "red flag 在海滩常表示？", options: ["正在促销", "游泳危险", "可以冲浪课", "免费遮阳伞"], answer: 1, explain: "红旗提醒风浪大、不宜游。" },
      { question: "locker 是？", options: ["救生圈", "储物柜", "沙滩垫", "望远镜"], answer: 1, explain: "带锁的小柜子。" },
      { question: "lifeguard 是？", options: ["导游", "救生员", "清洁工", "收银员"], answer: 1, explain: "负责海滩安全。" },
      { question: "rent 在 I'd like to rent 里是？", options: ["购买", "租用", "归还", "维修"], answer: 1, explain: "rent = 租。" },
      { question: "restrooms 指？", options: ["休息室沙发", "洗手间", "更衣室锁", "急救室"], answer: 1, explain: "美式英语里 restroom 常指厕所。" },
    ],
  }),
  scene({
    slug: "shopping",
    title: "商场买衣服",
    titleEn: "Clothes Shopping",
    emoji: "👗",
    place: "Clothing store",
    description: "问尺码、试穿、换货退货，服饰主题词马上能开口。",
    stage: "A2",
    usefulPhrases: [
      { en: "Do you have this in a medium?", zh: "这个有中号吗？", ipa: "/duː ju hæv ðɪs ɪn ə ˈmiːdiəm/" },
      { en: "Can I try this on?", zh: "我能试穿吗？", ipa: "/kæn aɪ traɪ ðɪs ɒn/" },
      { en: "Where is the fitting room?", zh: "试衣间在哪？", ipa: "/weə ɪz ðə ˈfɪtɪŋ ruːm/" },
      { en: "It's a bit too tight.", zh: "有点太紧了。", ipa: "/ɪts ə bɪt tuː taɪt/" },
      { en: "Do you have a larger size?", zh: "有更大号的吗？", ipa: "/duː ju hæv ə ˈlɑːdʒə saɪz/" },
      { en: "Can I return it within 14 days?", zh: "14 天内可以退货吗？", ipa: "/kæn aɪ rɪˈtɜːn ɪt wɪˈðɪn ˌfɔːˈtiːn deɪz/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi, I'm looking for a jacket. Something not too heavy.", zh: "你好，我想找一件外套，不要太厚。", ipa: "/haɪ aɪm ˈlʊkɪŋ fə ə ˈdʒækɪt/" },
      { speaker: "Staff", en: "This one is popular. Would you like to try a medium?", zh: "这件很受欢迎。要试中号吗？", ipa: "/ðɪs wʌn ɪz ˈpɒpjələ/" },
      { speaker: "You", en: "Yes. Where is the fitting room?", zh: "好。试衣间在哪？", ipa: "/jes weə ɪz ðə ˈfɪtɪŋ ruːm/" },
      { speaker: "Staff", en: "At the back, on your right. Take this tag with you.", zh: "在后面靠右。请带上这张吊牌。", ipa: "/ət ðə bæk ɒn jɔː raɪt/" },
      { speaker: "You", en: "It's a bit too tight in the shoulders.", zh: "肩膀这里有点紧。", ipa: "/ɪts ə bɪt tuː taɪt ɪn ðə ˈʃəʊldəz/" },
      { speaker: "Staff", en: "I'll get you a large. Same color?", zh: "我给您拿大号。还是这个颜色吗？", ipa: "/aɪl ɡet juː ə lɑːdʒ seɪm ˈkʌlə/" },
      { speaker: "You", en: "Yes. How much is it after the discount?", zh: "对。打折后多少钱？", ipa: "/jes haʊ mʌtʃ ɪz ɪt ˈɑːftə ðə ˈdɪskaʊnt/" },
      { speaker: "Staff", en: "Forty-eight. You can return it within 14 days with the receipt.", zh: "48。14 天内凭收据可退。", ipa: "/ˈfɔːti eɪt juː kæn rɪˈtɜːn ɪt/" },
      { speaker: "You", en: "Great. I'll take it. Can I pay by card?", zh: "太好了，就要这件。可以刷卡吗？", ipa: "/ɡreɪt aɪl teɪk ɪt/" },
      { speaker: "Staff", en: "Of course. Would you like it in a bag or a box?", zh: "当然。要袋子还是盒子？", ipa: "/əv kɔːs wəd ju laɪk ɪt ɪn ə bæɡ/" },
    ],
    quizzes: [
      { question: "try on 的意思是？", options: ["买下", "试穿", "退货", "熨烫"], answer: 1, explain: "try on = 试穿。" },
      { question: "fitting room 是？", options: ["仓库", "试衣间", "收银台", "停车场"], answer: 1, explain: "换衣服的隔间。" },
      { question: "too tight 表示？", options: ["太松", "太紧", "太长", "太花"], answer: 1, explain: "tight = 紧。" },
      { question: "Do you have this in a medium? 是在问？", options: ["有没有中号", "能不能打折", "是否纯棉", "能否烫印"], answer: 0, explain: "in a medium = 中号这件。" },
      { question: "return 在商店里常指？", options: ["归还/退货", "返回首页", "回酒店", "换零钱"], answer: 0, explain: "return an item = 退货。" },
      { question: "discount 是？", options: ["税", "折扣", "运费", "会员积分"], answer: 1, explain: "after the discount = 折后价。" },
      { question: "large 作为尺码是？", options: ["小号", "中号", "大号", "均码"], answer: 2, explain: "S/M/L 中 L 是 large。" },
      { question: "tag 在试衣时多指？", options: ["价签/吊牌", "银行卡", "登机牌", "房卡"], answer: 0, explain: "衣服上的吊牌。" },
    ],
  }),
  scene({
    slug: "subway",
    title: "坐地铁",
    titleEn: "On the Subway",
    emoji: "🚇",
    place: "Metro station",
    description: "买票、换乘、问末班车，城市通勤刚需英语。",
    stage: "A2",
    usefulPhrases: [
      { en: "Which line goes to the museum?", zh: "哪条线去博物馆？", ipa: "/wɪtʃ laɪn ɡəʊz tə ðə mjuˈziːəm/" },
      { en: "Where can I buy a ticket?", zh: "在哪买票？", ipa: "/weə kæn aɪ baɪ ə ˈtɪkɪt/" },
      { en: "Do I need to transfer?", zh: "需要换乘吗？", ipa: "/duː aɪ niːd tə trænsˈfɜː/" },
      { en: "Is this the right platform?", zh: "这是正确的站台吗？", ipa: "/ɪz ðɪs ðə raɪt ˈplætfɔːm/" },
      { en: "What time is the last train?", zh: "末班车几点？", ipa: "/wɒt taɪm ɪz ðə lɑːst treɪn/" },
      { en: "Excuse me, this is my stop.", zh: "不好意思，我到站了。", ipa: "/ɪkˈskjuːz miː ðɪs ɪz maɪ stɒp/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi, which line goes to Central Station?", zh: "你好，去中央车站坐哪条线？", ipa: "/haɪ wɪtʃ laɪn ɡəʊz tə ˈsentrəl ˈsteɪʃn/" },
      { speaker: "Staff", en: "Take the blue line, two stops. Then transfer to the red line.", zh: "坐蓝线两站，再换乘红线。", ipa: "/teɪk ðə bluː laɪn tuː stɒps/" },
      { speaker: "You", en: "Where can I buy a day pass?", zh: "一日票在哪买？", ipa: "/weə kæn aɪ baɪ ə deɪ pɑːs/" },
      { speaker: "Staff", en: "The machine over there. It takes cards.", zh: "那边的机器，可以刷卡。", ipa: "/ðə məˈʃiːn ˈəʊvə ðeə/" },
      { speaker: "You", en: "Is this the right platform for downtown?", zh: "去市中心是这个站台吗？", ipa: "/ɪz ðɪs ðə raɪt ˈplætfɔːm fə ˈdaʊntaʊn/" },
      { speaker: "Staff", en: "Yes. Stand behind the yellow line, please.", zh: "对。请站在黄线后面。", ipa: "/jes stænd bɪˈhaɪnd ðə ˈjeləʊ laɪn/" },
      { speaker: "You", en: "What time is the last train?", zh: "末班车几点？", ipa: "/wɒt taɪm ɪz ðə lɑːst treɪn/" },
      { speaker: "Staff", en: "11:40 on weekdays. Mind the gap when you board.", zh: "工作日 11:40。上车时小心空隙。", ipa: "/ɪˈlevn ˈfɔːti ɒn ˈwiːkdeɪz/" },
      { speaker: "You", en: "Thanks. How many stops to Central?", zh: "谢谢。到中央车站还有几站？", ipa: "/θæŋks haʊ ˈmeni stɒps/" },
      { speaker: "Staff", en: "Four after you transfer. You'll hear the announcement.", zh: "换乘后再四站。会有广播。", ipa: "/fɔː ˈɑːftə juː trænsˈfɜː/" },
    ],
    quizzes: [
      { question: "line 在地铁里指？", options: ["排队", "线路", "台词", "绳索"], answer: 1, explain: "the blue line = 蓝线。" },
      { question: "transfer 表示？", options: ["退票", "换乘", "逃票", "坐过站"], answer: 1, explain: "换另一条线。" },
      { question: "platform 是？", options: ["车厢", "站台", "闸机", "地图"], answer: 1, explain: "等车的站台。" },
      { question: "last train 是？", options: ["首班车", "末班车", "快车", "区间车"], answer: 1, explain: "当天最后一班。" },
      { question: "day pass 通常是？", options: ["单程票", "一日票", "年卡", "学生证"], answer: 1, explain: "当天不限次乘坐。" },
      { question: "Mind the gap 是在提醒？", options: ["小心车门与站台空隙", "不要大声说话", "禁止饮食", "给老人让座"], answer: 0, explain: "伦敦等地的经典提示。" },
      { question: "This is my stop 表示？", options: ["我坐过了", "我到站了", "这不是我的包", "请开门"], answer: 1, explain: "要下车了。" },
      { question: "two stops 的意思是？", options: ["两张票", "坐两站", "两个出口", "两条线同时开"], answer: 1, explain: "再坐两站就到。" },
    ],
  }),
  scene({
    slug: "pharmacy",
    title: "药店买药",
    titleEn: "At the Pharmacy",
    emoji: "💊",
    place: "Pharmacy",
    description: "说症状、问用法用量、买创可贴，旅行常备用语。",
    stage: "A2",
    usefulPhrases: [
      { en: "I have a headache.", zh: "我头疼。", ipa: "/aɪ hæv ə ˈhedeɪk/" },
      { en: "Do you have anything for a cold?", zh: "有治感冒的药吗？", ipa: "/duː ju hæv ˈeniθɪŋ fə ə kəʊld/" },
      { en: "How often should I take this?", zh: "这个多久吃一次？", ipa: "/haʊ ˈɒfn ʃəd aɪ teɪk ðɪs/" },
      { en: "I need some plasters / band-aids.", zh: "我需要创可贴。", ipa: "/aɪ niːd səm ˈplɑːstəz/" },
      { en: "Does this cause drowsiness?", zh: "这个会嗜睡吗？", ipa: "/dəz ðɪs kɔːz ˈdraʊzinəs/" },
      { en: "I don't have a prescription.", zh: "我没有处方。", ipa: "/aɪ dəʊnt hæv ə prɪˈskrɪpʃn/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi. I have a sore throat and a slight fever.", zh: "你好。我嗓子疼，还有点低烧。", ipa: "/haɪ aɪ hæv ə sɔː θrəʊt/" },
      { speaker: "Pharmacist", en: "How long have you felt like this?", zh: "这样有多久了？", ipa: "/haʊ lɒŋ hæv ju felt laɪk ðɪs/" },
      { speaker: "You", en: "Since yesterday. I don't have a prescription.", zh: "从昨天开始。我没有处方。", ipa: "/sɪns ˈjestədeɪ/" },
      { speaker: "Pharmacist", en: "This cold medicine is over the counter. Take two tablets every eight hours.", zh: "这是非处方感冒药。每八小时两片。", ipa: "/ðɪs kəʊld ˈmedsn ɪz ˈəʊvə ðə ˈkaʊntə/" },
      { speaker: "You", en: "Does it make you sleepy?", zh: "吃了会困吗？", ipa: "/dəz ɪt meɪk ju ˈsliːpi/" },
      { speaker: "Pharmacist", en: "A little. Don't drive after you take it.", zh: "会有一点。服药后不要开车。", ipa: "/ə ˈlɪtl dəʊnt draɪv/" },
      { speaker: "You", en: "I also need band-aids and sunscreen.", zh: "我还要创可贴和防晒霜。", ipa: "/aɪ ˈɔːlsəʊ niːd bænd eɪdz/" },
      { speaker: "Pharmacist", en: "They're on the shelf behind you. Drink plenty of water.", zh: "就在你身后货架上。多喝水。", ipa: "/ðeə ɒn ðə ʃelf bɪˈhaɪnd juː/" },
      { speaker: "You", en: "Thanks. Can I pay by card?", zh: "谢谢。可以刷卡吗？", ipa: "/θæŋks kæn aɪ peɪ baɪ kɑːd/" },
      { speaker: "Pharmacist", en: "Yes. If it gets worse, see a doctor tomorrow.", zh: "可以。如果加重，明天去看医生。", ipa: "/jes ɪf ɪt ɡets wɜːs siː ə ˈdɒktə/" },
    ],
    quizzes: [
      { question: "sore throat 是？", options: ["胃痛", "嗓子疼", "扭伤", "过敏"], answer: 1, explain: "throat 是喉咙。" },
      { question: "over the counter 的药是？", options: ["必须处方", "非处方药", "住院药", "过期药"], answer: 1, explain: "OTC，不用处方也能买。" },
      { question: "How often should I take this? 问的是？", options: ["价格", "用法用量/频率", "产地", "口味"], answer: 1, explain: "how often = 多久一次。" },
      { question: "tablet 在药店指？", options: ["平板电脑", "药片", "桌子", "处方单"], answer: 1, explain: "tablet = 片剂。" },
      { question: "drowsiness / sleepy 表示？", options: ["兴奋", "困倦", "止痛", "止咳"], answer: 1, explain: "部分感冒药会嗜睡。" },
      { question: "prescription 是？", options: ["收据", "处方", "病历号", "保险卡"], answer: 1, explain: "医生开的处方。" },
      { question: "If it gets worse 的意思是？", options: ["如果好转", "如果加重", "如果售罄", "如果过敏消失"], answer: 1, explain: "worse 是更糟。" },
      { question: "pharmacist 是？", options: ["护士", "药剂师", "牙医", "救生员"], answer: 1, explain: "药房里配药、给建议的人。" },
    ],
  }),
  scene({
    slug: "hotel-checkout",
    title: "酒店退房",
    titleEn: "Hotel Check-out",
    emoji: "🛎️",
    place: "Hotel front desk",
    description: "还房卡、核对账单、寄存行李，离开前最后一段对话。",
    stage: "A2",
    usefulPhrases: [
      { en: "I'd like to check out, please.", zh: "我想退房。", ipa: "/aɪd laɪk tə tʃek aʊt/" },
      { en: "Could I see the bill?", zh: "能看一下账单吗？", ipa: "/kəd aɪ siː ðə bɪl/" },
      { en: "There seems to be a mistake.", zh: "好像有一笔账不对。", ipa: "/ðeə siːmz tə bi ə mɪsˈteɪk/" },
      { en: "Can I leave my luggage here?", zh: "行李可以先寄存在这里吗？", ipa: "/kæn aɪ liːv maɪ ˈlʌɡɪdʒ hɪə/" },
      { en: "Could I have an invoice?", zh: "能开一张发票吗？", ipa: "/kəd aɪ hæv ən ˈɪnvɔɪs/" },
      { en: "Is there an airport shuttle?", zh: "有去机场的班车吗？", ipa: "/ɪz ðeər ən ˈeəpɔːt ˈʃʌtl/" },
    ],
    dialogue: [
      { speaker: "You", en: "Good morning. I'd like to check out. Room 305.", zh: "早上好。我要退房，305 房。", ipa: "/ɡʊd ˈmɔːnɪŋ aɪd laɪk tə tʃek aʊt/" },
      { speaker: "Staff", en: "Of course. Did you take anything from the minibar?", zh: "好的。迷你吧有消费吗？", ipa: "/əv kɔːs dɪd ju teɪk ˈeniθɪŋ frəm ðə ˈmɪnibɑː/" },
      { speaker: "You", en: "Just one bottle of water. Could I see the bill?", zh: "只喝了一瓶水。能看账单吗？", ipa: "/dʒʌst wʌn ˈbɒtl əv ˈwɔːtə/" },
      { speaker: "Staff", en: "Here it is. Breakfast is included, so that's 126 in total.", zh: "给您。早餐已含，一共 126。", ipa: "/hɪə ɪt ɪz ˈbrekfəst ɪz ɪnˈkluːdɪd/" },
      { speaker: "You", en: "This taxi charge isn't mine. I didn't take a taxi.", zh: "这笔出租车费不是我的，我没打车。", ipa: "/ðɪs ˈtæksi tʃɑːdʒ ˈɪznt maɪn/" },
      { speaker: "Staff", en: "Sorry about that. I'll remove it right away.", zh: "抱歉，我马上去掉。", ipa: "/ˈsɒri əˈbaʊt ðæt aɪl rɪˈmuːv ɪt/" },
      { speaker: "You", en: "Thanks. Can I leave my suitcase until 4 p.m.?", zh: "谢谢。行李箱能存到下午四点吗？", ipa: "/θæŋks kæn aɪ liːv maɪ ˈsuːtkeɪs/" },
      { speaker: "Staff", en: "Yes, complimentary. Here's your luggage tag.", zh: "可以，免费。这是行李牌。", ipa: "/jes ˌkɒmplɪˈmentri hɪəz jɔː ˈlʌɡɪdʒ tæɡ/" },
      { speaker: "You", en: "Is there a shuttle to the airport?", zh: "有去机场的班车吗？", ipa: "/ɪz ðeər ə ˈʃʌtl tə ði ˈeəpɔːt/" },
      { speaker: "Staff", en: "It leaves at 3:15 from the front door. Have a safe trip!", zh: "3:15 从正门发车。一路平安！", ipa: "/ɪt liːvz ət θriː ˈfɪfˈtiːn/" },
    ],
    quizzes: [
      { question: "check out 在酒店指？", options: ["办理入住", "退房", "叫早", "升级房间"], answer: 1, explain: "与 check in 相对。" },
      { question: "minibar 是？", options: ["迷你酒吧/房间小冰箱", "健身房", "停车场", "早餐券"], answer: 0, explain: "房间里的收费小冰箱。" },
      { question: "There seems to be a mistake 用于？", options: ["夸奖服务", "指出账单错误", "要求升级", "预约班车"], answer: 1, explain: "礼貌地提出问题。" },
      { question: "invoice 更接近？", options: ["发票/报销单据", "房卡", "地图", "小费"], answer: 0, explain: "商务出行常要 invoice。" },
      { question: "shuttle 在这里是？", options: ["航天飞机", "接驳班车", "电梯", "行李车"], answer: 1, explain: "airport shuttle 去机场的班车。" },
      { question: "complimentary 表示？", options: ["必须付费", "免费赠送", "需要预约", "仅限会员"], answer: 1, explain: "complimentary = 免费提供。" },
      { question: "charge 在账单上指？", options: ["充电", "收费项目", "指控", "冲锋"], answer: 1, explain: "a taxi charge = 一笔车费。" },
      { question: "leave my luggage here 是在？", options: ["托运上飞机", "寄存行李", "报失行李", "称重"], answer: 1, explain: "退房后先把行李放前台。" },
    ],
  }),
  scene({
    slug: "gym",
    title: "健身房办卡",
    titleEn: "At the Gym",
    emoji: "🏋️",
    place: "Fitness center",
    description: "办体验、问器械、预约团课，运动主题能立刻开口。",
    stage: "A2",
    usefulPhrases: [
      { en: "I'd like a day pass, please.", zh: "我想办一张日卡。", ipa: "/aɪd laɪk ə deɪ pɑːs/" },
      { en: "Where are the changing rooms?", zh: "更衣室在哪？", ipa: "/weə ɑː ðə ˈtʃeɪndʒɪŋ ruːmz/" },
      { en: "Is this machine free?", zh: "这台器械有人用吗？", ipa: "/ɪz ðɪs məˈʃiːn friː/" },
      { en: "Can I book a class?", zh: "能预约一节课吗？", ipa: "/kæn aɪ bʊk ə klɑːs/" },
      { en: "How does this treadmill work?", zh: "这台跑步机怎么用？", ipa: "/haʊ dəz ðɪs ˈtredmɪl wɜːk/" },
      { en: "Do you have lockers?", zh: "有储物柜吗？", ipa: "/duː ju hæv ˈlɒkəz/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi, I'm staying next door. Can I use the gym today?", zh: "你好，我住在隔壁。今天能用健身房吗？", ipa: "/haɪ aɪm ˈsteɪɪŋ nekst dɔː/" },
      { speaker: "Staff", en: "Yes. A day pass is 12 dollars, including a towel.", zh: "可以。日卡 12 美元，含毛巾。", ipa: "/jes ə deɪ pɑːs ɪz twelv ˈdɒləz/" },
      { speaker: "You", en: "Great. Where are the changing rooms and lockers?", zh: "太好了。更衣室和储物柜在哪？", ipa: "/ɡreɪt weə ɑː ðə ˈtʃeɪndʒɪŋ ruːmz/" },
      { speaker: "Staff", en: "Down the hall on the left. You'll need a 1-dollar coin for the locker.", zh: "走廊左边。储物柜要一美元硬币。", ipa: "/daʊn ðə hɔːl ɒn ðə left/" },
      { speaker: "You", en: "Is there a yoga class this afternoon?", zh: "今天下午有瑜伽课吗？", ipa: "/ɪz ðeər ə ˈjəʊɡə klɑːs/" },
      { speaker: "Staff", en: "At 4 p.m. I can book you a spot. Bring a water bottle.", zh: "下午四点。我可以帮你占位。请带水瓶。", ipa: "/ət fɔː piː em aɪ kæn bʊk juː ə spɒt/" },
      { speaker: "You", en: "How does this treadmill start?", zh: "这台跑步机怎么启动？", ipa: "/haʊ dəz ðɪs ˈtredmɪl stɑːt/" },
      { speaker: "Staff", en: "Press the green button, then choose a speed. Wipe it after use.", zh: "按绿色按钮再选速度。用完请擦干净。", ipa: "/pres ðə ɡriːn ˈbʌtn/" },
      { speaker: "You", en: "Got it. Is this bike free?", zh: "明白了。这辆单车有人用吗？", ipa: "/ɡɒt ɪt ɪz ðɪs baɪk friː/" },
      { speaker: "Staff", en: "Yes. Enjoy your workout!", zh: "没人。训练愉快！", ipa: "/jes ɪnˈdʒɔɪ jɔː ˈwɜːkaʊt/" },
    ],
    quizzes: [
      { question: "day pass 在健身房是？", options: ["年卡", "当日体验卡", "私教课", "储物柜钥匙"], answer: 1, explain: "按天付费使用。" },
      { question: "changing room 是？", options: ["教室", "更衣室", "前台", "泳池"], answer: 1, explain: "换衣服的地方。" },
      { question: "Is this machine free? 问的是？", options: ["这台免费吗", "这台有人在用吗", "这台坏了吗", "这台能租回家吗"], answer: 1, explain: "free 这里表示空闲。" },
      { question: "treadmill 是？", options: ["哑铃", "跑步机", "瑜伽垫", "单车"], answer: 1, explain: "tread 踩 + mill。" },
      { question: "book a class 表示？", options: ["买书", "预约课程", "取消会员", "称体重"], answer: 1, explain: "book = 预订。" },
      { question: "workout 指？", options: ["下班", "训练/锻炼", "工作餐", "拉伸以外的会议"], answer: 1, explain: "一次锻炼。" },
      { question: "Wipe it after use 是在请你？", options: ["用完擦干净", "用完关掉灯", "用完喊教练", "用完拍照"], answer: 0, explain: "wipe 擦拭。" },
      { question: "spot 在 I can book you a spot 里指？", options: ["污渍", "名额/位置", "聚光灯", "斑点狗"], answer: 1, explain: "课上的一个位置。" },
    ],
  }),
  scene({
    slug: "delivery",
    title: "收快递与外卖",
    titleEn: "Delivery",
    emoji: "📦",
    place: "Apartment door",
    description: "对地址、签收、说放门口，城市生活每天都在用。",
    stage: "A2",
    usefulPhrases: [
      { en: "I have a delivery for Chen.", zh: "有陈的快递。", ipa: "/aɪ hæv ə dɪˈlɪvəri fə tʃen/" },
      { en: "Could you leave it at the door?", zh: "能放门口吗？", ipa: "/kəd ju liːv ɪt ət ðə dɔː/" },
      { en: "I'll come down in a minute.", zh: "我马上下来。", ipa: "/aɪl kʌm daʊn ɪn ə ˈmɪnɪt/" },
      { en: "This is the wrong address.", zh: "地址不对。", ipa: "/ðɪs ɪz ðə rɒŋ əˈdres/" },
      { en: "Can I get a refund?", zh: "能退款吗？", ipa: "/kæn aɪ ɡet ə ˈriːfʌnd/" },
      { en: "The food is cold / the box is damaged.", zh: "食物凉了 / 箱子破了。", ipa: "/ðə fuːd ɪz kəʊld/" },
    ],
    dialogue: [
      { speaker: "Driver", en: "Hi, delivery for Chen. Apartment 5B.", zh: "你好，陈的快递，5B 室。", ipa: "/haɪ dɪˈlɪvəri fə tʃen/" },
      { speaker: "You", en: "That's me. I'll come down in a minute.", zh: "是我。我马上下来。", ipa: "/ðæts miː aɪl kʌm daʊn/" },
      { speaker: "Driver", en: "No rush. Could you confirm the last four digits of your phone?", zh: "不急。请确认手机后四位。", ipa: "/nəʊ rʌʃ kəd ju kənˈfɜːm/" },
      { speaker: "You", en: "7682. Could you leave the food at the door next time?", zh: "7682。下次餐可以放门口吗？", ipa: "/ˈsevn sɪks eɪt tuː/" },
      { speaker: "Driver", en: "Sure, if you write it in the notes.", zh: "可以，请写在备注里。", ipa: "/ʃʊə ɪf ju raɪt ɪt ɪn ðə nəʊts/" },
      { speaker: "You", en: "Thanks. Oh — this box looks damaged.", zh: "谢谢。哦，这个箱子看起来破了。", ipa: "/θæŋks ðɪs bɒks lʊks ˈdæmɪdʒd/" },
      { speaker: "Driver", en: "I'm sorry. You can take a photo and apply for a refund.", zh: "抱歉。你可以拍照申请退款。", ipa: "/aɪm ˈsɒri juː kæn teɪk ə ˈfəʊtəʊ/" },
      { speaker: "You", en: "Will the replacement arrive today?", zh: "补发今天能到吗？", ipa: "/wɪl ðə rɪˈpleɪsmənt əˈraɪv təˈdeɪ/" },
      { speaker: "Driver", en: "Usually by 8 p.m. Check the tracking link.", zh: "一般晚上 8 点前。看物流链接。", ipa: "/ˈjuːʒuəli baɪ eɪt piː em/" },
      { speaker: "You", en: "Got it. Thanks for waiting.", zh: "明白了。谢谢你等我。", ipa: "/ɡɒt ɪt θæŋks fə ˈweɪtɪŋ/" },
    ],
    quizzes: [
      { question: "delivery 在这里指？", options: ["演讲", "配送/快递", "交货期股票", "解脱"], answer: 1, explain: "送货上门。" },
      { question: "leave it at the door 表示？", options: ["放门口", "放前台", "送进电梯", "改日再送"], answer: 0, explain: "不用当面签收。" },
      { question: "damaged 的意思是？", options: ["完好", "损坏", "加急", "冷冻"], answer: 1, explain: "破损了。" },
      { question: "refund 是？", options: ["退款", "小费", "运费险以外的税", "好评"], answer: 0, explain: "get a refund = 拿到退款。" },
      { question: "confirm 表示？", options: ["取消", "确认", "投诉", "忽略"], answer: 1, explain: "核对信息。" },
      { question: "replacement 指？", options: ["原件", "补发/替换件", "发票", "评价"], answer: 1, explain: "重新发一件。" },
      { question: "tracking 用来？", options: ["追踪物流", "追踪卡路里", "追踪航班延误以外的事", "录音"], answer: 0, explain: "tracking link 物流查询。" },
      { question: "I'll come down 的意思是？", options: ["我降价", "我下楼", "我下降音量", "我取消订单"], answer: 1, explain: "下楼取件。" },
    ],
  }),
  scene({
    slug: "clinic",
    title: "诊所看病",
    titleEn: "Seeing a Doctor",
    emoji: "🩺",
    place: "Clinic",
    description: "挂号、说症状、问检查和请假条，健康主题核心对话。",
    stage: "B1",
    usefulPhrases: [
      { en: "I'd like to make an appointment.", zh: "我想预约挂号。", ipa: "/aɪd laɪk tə meɪk ən əˈpɔɪntmənt/" },
      { en: "I've had a fever since last night.", zh: "我从昨晚开始发烧。", ipa: "/aɪv hæd ə ˈfiːvə sɪns lɑːst naɪt/" },
      { en: "It hurts when I swallow.", zh: "吞咽的时候疼。", ipa: "/ɪt hɜːts wen aɪ ˈswɒləʊ/" },
      { en: "Are you taking any medicine?", zh: "你在吃药吗？", ipa: "/ɑː ju ˈteɪkɪŋ ˈeni ˈmedsn/" },
      { en: "Do I need a blood test?", zh: "需要验血吗？", ipa: "/duː aɪ niːd ə blʌd test/" },
      { en: "Could I have a sick note, please?", zh: "能开一张病假条吗？", ipa: "/kəd aɪ hæv ə sɪk nəʊt/" },
    ],
    dialogue: [
      { speaker: "Receptionist", en: "Good morning. Do you have an appointment?", zh: "早上好。有预约吗？", ipa: "/ɡʊd ˈmɔːnɪŋ duː ju hæv ən əˈpɔɪntmənt/" },
      { speaker: "You", en: "Yes, at 9:30 with Dr. Patel. I've had a fever since last night.", zh: "有，9:30 看 Patel 医生。我昨晚开始发烧。", ipa: "/jes ət naɪn ˈθɜːti/" },
      { speaker: "Doctor", en: "Any cough or shortness of breath?", zh: "有咳嗽或气短吗？", ipa: "/ˈeni kɒf ɔː ˈʃɔːtnəs əv breθ/" },
      { speaker: "You", en: "A dry cough. It hurts when I swallow.", zh: "干咳。吞咽时疼。", ipa: "/ə draɪ kɒf ɪt hɜːts/" },
      { speaker: "Doctor", en: "Are you taking any medicine or do you have allergies?", zh: "在吃药吗？有过敏吗？", ipa: "/ɑː ju ˈteɪkɪŋ ˈeni ˈmedsn/" },
      { speaker: "You", en: "Just vitamin C. I'm allergic to penicillin.", zh: "只吃了维 C。我对青霉素过敏。", ipa: "/dʒʌst ˈvɪtəmɪn siː/" },
      { speaker: "Doctor", en: "I'll do a quick throat exam. You may need a blood test.", zh: "我先看一下喉咙。可能需要验血。", ipa: "/aɪl duː ə kwɪk θrəʊt ɪɡˈzæm/" },
      { speaker: "You", en: "How soon will I feel better? I have work tomorrow.", zh: "多久能好？我明天还要上班。", ipa: "/haʊ suːn wɪl aɪ fiːl ˈbetə/" },
      { speaker: "Doctor", en: "Rest for two days. I'll give you a sick note and some lozenges.", zh: "休息两天。我给你开病假条和含片。", ipa: "/rest fə tuː deɪz/" },
      { speaker: "You", en: "Thank you. Should I come back if it gets worse?", zh: "谢谢。如果加重要再来吗？", ipa: "/θæŋk juː ʃəd aɪ kʌm bæk/" },
    ],
    quizzes: [
      { question: "appointment 在诊所指？", options: ["任命", "预约就诊", "药方", "保险"], answer: 1, explain: "make an appointment = 挂号预约。" },
      { question: "fever 是？", options: ["发烧", "骨折", "过敏", "失眠"], answer: 0, explain: "体温升高。" },
      { question: "It hurts when I swallow 描述？", options: ["胸痛", "吞咽痛", "耳鸣", "皮疹"], answer: 1, explain: "swallow = 吞咽。" },
      { question: "blood test 是？", options: ["X 光", "验血", "打针", "量血压"], answer: 1, explain: "抽血化验。" },
      { question: "sick note 用来？", options: ["点餐", "向单位/学校请假", "办理登机", "租伞"], answer: 1, explain: "医生证明你需要休息。" },
      { question: "allergic to penicillin 表示？", options: ["喜欢青霉素", "对青霉素过敏", "正在注射", "没有保险"], answer: 1, explain: "必须告诉医生过敏史。" },
      { question: "dry cough 是？", options: ["有痰的咳", "干咳", "大笑", "打喷嚏"], answer: 1, explain: "少痰或无痰。" },
      { question: "shortness of breath 指？", options: ["口臭", "气短/呼吸困难", "口渴", "打嗝"], answer: 1, explain: "呼吸浅而急。" },
    ],
  }),
  scene({
    slug: "bank",
    title: "银行办业务",
    titleEn: "At the Bank",
    emoji: "🏦",
    place: "Bank",
    description: "开户、换汇、挂失卡，出国和六级听力都常见。",
    stage: "B1",
    usefulPhrases: [
      { en: "I'd like to open an account.", zh: "我想开户。", ipa: "/aɪd laɪk tə ˈəʊpən ən əˈkaʊnt/" },
      { en: "Can I exchange some money?", zh: "可以换汇吗？", ipa: "/kæn aɪ ɪksˈtʃeɪndʒ səm ˈmʌni/" },
      { en: "What's the exchange rate today?", zh: "今天汇率是多少？", ipa: "/wɒts ði ɪksˈtʃeɪndʒ reɪt/" },
      { en: "I lost my card. I'd like to block it.", zh: "卡丢了，我想挂失。", ipa: "/aɪ lɒst maɪ kɑːd/" },
      { en: "Could I get a statement, please?", zh: "能打一份流水吗？", ipa: "/kəd aɪ ɡet ə ˈsteɪtmənt/" },
      { en: "Is there a fee for this transfer?", zh: "转账收手续费吗？", ipa: "/ɪz ðeər ə fiː fə ðɪs ˈtrænsfɜː/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hello. I'd like to exchange 500 dollars into local currency.", zh: "你好。我想把 500 美元换成当地货币。", ipa: "/həˈləʊ aɪd laɪk tə ɪksˈtʃeɪndʒ/" },
      { speaker: "Clerk", en: "May I see your passport? Today's rate is on the board.", zh: "请出示护照。今天汇率写在牌子上。", ipa: "/meɪ aɪ siː jɔː ˈpɑːspɔːt/" },
      { speaker: "You", en: "Is there a commission fee?", zh: "有手续费吗？", ipa: "/ɪz ðeər ə kəˈmɪʃn fiː/" },
      { speaker: "Clerk", en: "Two percent. Would you like small bills as well?", zh: "百分之二。也要一些小面额吗？", ipa: "/tuː pəˈsent wəd ju laɪk smɔːl bɪlz/" },
      { speaker: "You", en: "Yes, some twenties please. I also need to report a lost card.", zh: "要，来一些二十的。我还要挂失一张卡。", ipa: "/jes səm ˈtwentiz/" },
      { speaker: "Clerk", en: "I can block it now. We'll send a replacement in five days.", zh: "我可以马上冻结。新卡五天后寄出。", ipa: "/aɪ kæn blɒk ɪt naʊ/" },
      { speaker: "You", en: "Could I get a statement for last month?", zh: "能打上个月的流水吗？", ipa: "/kəd aɪ ɡet ə ˈsteɪtmənt/" },
      { speaker: "Clerk", en: "Printed or emailed? There is no fee for email.", zh: "打印纸质还是发邮件？邮件免费。", ipa: "/ˈprɪntɪd ɔː ˈiːmeɪld/" },
      { speaker: "You", en: "Email is fine. One more thing — can I transfer to my home account?", zh: "发邮件吧。还能转到国内账户吗？", ipa: "/ˈiːmeɪl ɪz faɪn/" },
      { speaker: "Clerk", en: "Yes, but international transfers take two business days.", zh: "可以，国际汇款要两个工作日。", ipa: "/jes bət ˌɪntəˈnæʃnəl ˈtrænsfɜːz/" },
    ],
    quizzes: [
      { question: "exchange rate 是？", options: ["利率", "汇率", "手续费", "余额"], answer: 1, explain: "两种货币的兑换比率。" },
      { question: "open an account 表示？", options: ["结账离店", "开户", "开灯", "开口说话"], answer: 1, explain: "bank account 银行账户。" },
      { question: "block a card 是在？", options: ["办新卡", "冻结/挂失", "提高额度", "绑定微信"], answer: 1, explain: "防止被盗刷。" },
      { question: "statement 在银行指？", options: ["声明演讲", "账单/流水", "汇率牌", "密码"], answer: 1, explain: "bank statement。" },
      { question: "commission / fee 通常是？", options: ["利息", "手续费", "存款", "贷款"], answer: 1, explain: "银行服务收费。" },
      { question: "small bills 指？", options: ["小发票", "小面额钞票", "账单纠纷", "硬币"], answer: 1, explain: "零散的纸币。" },
      { question: "business days 不含？", options: ["周一到周五", "通常的周末与公共假期", "工作日下午", "开户当天"], answer: 1, explain: "两个工作日可能跨过周末。" },
      { question: "replacement 在丢卡语境下是？", options: ["旧卡", "补发卡", "账单", "汇率"], answer: 1, explain: "重新做一张卡。" },
    ],
  }),
  scene({
    slug: "lost-luggage",
    title: "行李丢失",
    titleEn: "Lost Luggage",
    emoji: "🧳",
    place: "Baggage claim",
    description: "描述箱子、填表、要赔偿，航班出状况时的应急英语。",
    stage: "B1",
    usefulPhrases: [
      { en: "My suitcase didn't arrive.", zh: "我的行李箱没到。", ipa: "/maɪ ˈsuːtkeɪs ˈdɪdnt əˈraɪv/" },
      { en: "It's a black hard-shell case with a red ribbon.", zh: "黑色硬壳箱，绑了红丝带。", ipa: "/ɪts ə blæk hɑːd ʃel keɪs/" },
      { en: "Here's my baggage receipt.", zh: "这是行李票。", ipa: "/hɪəz maɪ ˈbæɡɪdʒ rɪˈsiːt/" },
      { en: "Where will you deliver it?", zh: "你们会送到哪里？", ipa: "/weə wɪl ju dɪˈlɪvə ɪt/" },
      { en: "Can I get a compensation form?", zh: "能给我赔偿表吗？", ipa: "/kæn aɪ ɡet ə ˌkɒmpenˈseɪʃn fɔːm/" },
      { en: "I need some essentials for tonight.", zh: "今晚需要一些生活必需品。", ipa: "/aɪ niːd səm ɪˈsenʃlz/" },
    ],
    dialogue: [
      { speaker: "You", en: "Excuse me, my suitcase didn't come out on the belt.", zh: "打扰一下，我的行李箱没从传送带出来。", ipa: "/ɪkˈskjuːz miː maɪ ˈsuːtkeɪs/" },
      { speaker: "Staff", en: "I'm sorry. Can I see your boarding pass and baggage tag?", zh: "抱歉。请出示登机牌和行李牌。", ipa: "/aɪm ˈsɒri kæn aɪ siː/" },
      { speaker: "You", en: "Here. It's a black hard-shell case with a red ribbon.", zh: "给。黑色硬壳，绑了红丝带。", ipa: "/hɪə ɪts ə blæk hɑːd ʃel keɪs/" },
      { speaker: "Staff", en: "It may be on the next flight. We'll track it and call you.", zh: "可能在下一班飞机上。我们会追踪并打电话。", ipa: "/ɪt meɪ bi ɒn ðə nekst flaɪt/" },
      { speaker: "You", en: "I'm staying at the Grand Hotel. Could you deliver it there?", zh: "我住格兰酒店。能送到那里吗？", ipa: "/aɪm ˈsteɪɪŋ ət ðə ɡrænd həʊˈtel/" },
      { speaker: "Staff", en: "Yes. Please fill in this form with your phone number.", zh: "可以。请填表并留下电话。", ipa: "/jes pliːz fɪl ɪn ðɪs fɔːm/" },
      { speaker: "You", en: "I need a toothbrush and a charger tonight. Is there an essentials kit?", zh: "今晚需要牙刷和充电器。有应急包吗？", ipa: "/aɪ niːd ə ˈtuːθbrʌʃ/" },
      { speaker: "Staff", en: "We can give you a small kit and a compensation form.", zh: "可以给你一个小应急包和赔偿表。", ipa: "/wi kæn ɡɪv juː ə smɔːl kɪt/" },
      { speaker: "You", en: "How long does it usually take?", zh: "一般要多久能找到？", ipa: "/haʊ lɒŋ dəz ɪt ˈjuːʒuəli teɪk/" },
      { speaker: "Staff", en: "Most bags arrive within 24 hours. Keep this reference number.", zh: "多数 24 小时内到。请保管这个查询号。", ipa: "/məʊst bæɡz əˈraɪv wɪˈðɪn/" },
    ],
    quizzes: [
      { question: "baggage claim 是？", options: ["值机柜台", "行李提取处", "安检", "登机口"], answer: 1, explain: "落地后取行李的地方。" },
      { question: "hard-shell case 指？", options: ["软布袋", "硬壳箱", "纸箱", "背包"], answer: 1, explain: "硬质行李箱。" },
      { question: "baggage tag 用来？", options: ["识别托运行李", "点餐", "开房", "换汇"], answer: 0, explain: "贴在箱子上的行李牌。" },
      { question: "track it 表示？", options: ["扔掉", "追踪查找", "安检打开", "超重罚款"], answer: 1, explain: "系统里查行李位置。" },
      { question: "essentials 在丢失行李时多指？", options: ["奢侈品", "牙刷充电器等必需品", "纪念品", "登机牌复印件以外的小说"], answer: 1, explain: "过夜急需的东西。" },
      { question: "compensation 接近？", options: ["赔偿", "表扬", "升舱", "安检放行"], answer: 0, explain: "对损失的补偿。" },
      { question: "reference number 是？", options: ["房间号", "查询/案件编号", "航班号本身", "护照号必填项以外的小费"], answer: 1, explain: "后续跟进要用这个号。" },
      { question: "on the belt 里的 belt 指？", options: ["皮带", "行李传送带", "安全带", "腰带店"], answer: 1, explain: "baggage belt。" },
    ],
  }),
  scene({
    slug: "campus",
    title: "校园选课",
    titleEn: "On Campus",
    emoji: "🎓",
    place: "University office",
    description: "问课程、截止日期、办公室时间，留学和六级场景都用得上。",
    stage: "B1",
    usefulPhrases: [
      { en: "Is this course still available?", zh: "这门课还有名额吗？", ipa: "/ɪz ðɪs kɔːs stɪl əˈveɪləbl/" },
      { en: "What's the deadline to register?", zh: "注册截止日期是哪天？", ipa: "/wɒts ðə ˈdedlaɪn tə ˈredʒɪstə/" },
      { en: "Where is the professor's office?", zh: "教授办公室在哪？", ipa: "/weə ɪz ðə prəˈfesəz ˈɒfɪs/" },
      { en: "Could I get a syllabus?", zh: "能给我一份课程大纲吗？", ipa: "/kəd aɪ ɡet ə ˈsɪləbəs/" },
      { en: "I need to switch tutorials.", zh: "我需要换讨论课时间。", ipa: "/aɪ niːd tə swɪtʃ tjuːˈtɔːriəlz/" },
      { en: "How is the final assessed?", zh: "期末怎么考核？", ipa: "/haʊ ɪz ðə ˈfaɪnl əˈsest/" },
    ],
    dialogue: [
      { speaker: "You", en: "Hi, I'd like to add the academic writing class.", zh: "你好，我想加选学术写作课。", ipa: "/haɪ aɪd laɪk tə æd/" },
      { speaker: "Advisor", en: "Let me check. There's one seat left, but the lecture clashes with your seminar.", zh: "我查一下。还剩一个名额，但和你的研讨课冲突。", ipa: "/let mi tʃek ðeəz wʌn siːt left/" },
      { speaker: "You", en: "Can I switch to the Thursday tutorial instead?", zh: "能改到周四的讨论课吗？", ipa: "/kæn aɪ swɪtʃ tə ðə ˈθɜːzdeɪ/" },
      { speaker: "Advisor", en: "Yes. The deadline to register is Friday at 5.", zh: "可以。注册截止是周五下午 5 点。", ipa: "/jes ðə ˈdedlaɪn ɪz ˈfraɪdeɪ/" },
      { speaker: "You", en: "Where can I find the syllabus and reading list?", zh: "课程大纲和书单在哪看？", ipa: "/weə kæn aɪ faɪnd ðə ˈsɪləbəs/" },
      { speaker: "Advisor", en: "On the course page. Office hours are Tuesday mornings.", zh: "在课程网页。答疑时间是周二上午。", ipa: "/ɒn ðə kɔːs peɪdʒ/" },
      { speaker: "You", en: "How is the final assessed? Exam or essay?", zh: "期末怎么考？闭卷还是论文？", ipa: "/haʊ ɪz ðə ˈfaɪnl əˈsest/" },
      { speaker: "Advisor", en: "A 2,000-word essay plus a short presentation.", zh: "两千词论文加一个短展示。", ipa: "/ə tuː ˈθaʊznd wɜːd ˈeseɪ/" },
      { speaker: "You", en: "Is there a writing center if I need extra help?", zh: "需要额外帮助的话有写作中心吗？", ipa: "/ɪz ðeər ə ˈraɪtɪŋ ˈsentə/" },
      { speaker: "Advisor", en: "Yes, book a slot online. Bring a draft.", zh: "有，网上预约。请带上草稿。", ipa: "/jes bʊk ə slɒt ˈɒnlaɪn/" },
    ],
    quizzes: [
      { question: "deadline 是？", options: ["开学日", "截止日期", "假期", "学分"], answer: 1, explain: "必须完成的最后期限。" },
      { question: "syllabus 指？", options: ["成绩单", "课程大纲", "学生证", "校历"], answer: 1, explain: "每周内容、作业和评分。" },
      { question: "clashes with 表示？", options: ["互相推荐", "时间冲突", "可以免修", "已满员以外的意思"], answer: 1, explain: "两个课同一时间。" },
      { question: "office hours 是？", options: ["银行营业时间", "教授答疑时间", "图书馆关门", "食堂档口"], answer: 1, explain: "可以找老师问问题。" },
      { question: "assessed 在 How is it assessed 里指？", options: ["怎么收费", "怎么考核评分", "怎么选宿舍", "怎么办签证"], answer: 1, explain: "assessment = 评价、考核。" },
      { question: "tutorial / seminar 更接近？", options: ["大型讲座", "小班讨论课", "运动会", "毕业典礼"], answer: 1, explain: "相对 lecture 更小的课。" },
      { question: "draft 是？", options: ["草稿", "终稿打印费", "参考文献以外的海报", "出勤表"], answer: 0, explain: "还没改完的版本。" },
      { question: "register 在校园里常指？", options: ["收银", "选课/注册", "寄存行李", "挂号看病以外的登机"], answer: 1, explain: "register for a course。" },
    ],
  }),
  scene({
    slug: "meeting",
    title: "职场开会",
    titleEn: "In a Meeting",
    emoji: "💼",
    place: "Meeting room",
    description: "打断、澄清、认领任务，六级听力和面试都爱考。",
    stage: "B1",
    usefulPhrases: [
      { en: "Could we go over the agenda?", zh: "我们过一下议程吧？", ipa: "/kəd wi ɡəʊ ˈəʊvə ði ˈædʒəndə/" },
      { en: "Sorry to interrupt, but I have a question.", zh: "抱歉打断，我有个问题。", ipa: "/ˈsɒri tə ˌɪntəˈrʌpt/" },
      { en: "Could you clarify that last point?", zh: "最后那点能再说清楚吗？", ipa: "/kəd ju ˈklærəfaɪ ðæt/" },
      { en: "I'll take that action item.", zh: "这项我来跟进。", ipa: "/aɪl teɪk ðæt ˈækʃn ˈaɪtəm/" },
      { en: "Let's take this offline.", zh: "这件事会后再细聊。", ipa: "/lets teɪk ðɪs ˈɒflaɪn/" },
      { en: "What's the deadline on this?", zh: "这件事截止日期是？", ipa: "/wɒts ðə ˈdedlaɪn ɒn ðɪs/" },
    ],
    dialogue: [
      { speaker: "Manager", en: "Let's start. The goal today is to finalize the launch date.", zh: "开始吧。今天目标是敲定上线日期。", ipa: "/lets stɑːt ðə ɡəʊl təˈdeɪ/" },
      { speaker: "You", en: "Could we go over the agenda first? I joined two minutes late.", zh: "能先过一下议程吗？我晚了两分钟。", ipa: "/kəd wi ɡəʊ ˈəʊvə ði ˈædʒəndə/" },
      { speaker: "Manager", en: "Sure. Design, testing, then marketing.", zh: "好。设计、测试，然后市场。", ipa: "/ʃʊə dɪˈzaɪn ˈtestɪŋ/" },
      { speaker: "Colleague", en: "Testing may slip if the copy isn't ready.", zh: "如果文案没好，测试可能会推迟。", ipa: "/ˈtestɪŋ meɪ slɪp/" },
      { speaker: "You", en: "Sorry to interrupt, but could you clarify 'slip'?", zh: "抱歉打断，slip 是指延期吗？", ipa: "/ˈsɒri tə ˌɪntəˈrʌpt/" },
      { speaker: "Colleague", en: "Yes, delay by a week. I'll take that action item.", zh: "对，晚一周。这事我来跟。", ipa: "/jes dɪˈleɪ baɪ ə wiːk/" },
      { speaker: "Manager", en: "What's the deadline on the copy then?", zh: "那文案截止是哪天？", ipa: "/wɒts ðə ˈdedlaɪn/" },
      { speaker: "You", en: "Thursday. If we need more time, let's take the budget offline.", zh: "周四。预算如果要细谈，会后再说。", ipa: "/ˈθɜːzdeɪ ɪf wi niːd mɔː taɪm/" },
      { speaker: "Manager", en: "Agreed. I'll send the minutes after the call.", zh: "同意。会后我发会议纪要。", ipa: "/əˈɡriːd aɪl send ðə ˈmɪnɪts/" },
      { speaker: "You", en: "Thanks. I'll update the timeline today.", zh: "谢谢。我今天更新时间表。", ipa: "/θæŋks aɪl ˌʌpˈdeɪt ðə ˈtaɪmlaɪn/" },
    ],
    quizzes: [
      { question: "agenda 是？", options: ["纪要", "会议议程", "预算", "请假条"], answer: 1, explain: "会上要讨论的事项清单。" },
      { question: "interrupt 表示？", options: ["总结", "打断发言", "投票", "散会"], answer: 1, explain: "Sorry to interrupt 是礼貌插话。" },
      { question: "clarify 的意思是？", options: ["取消", "澄清说明", "批准报销", "升职"], answer: 1, explain: "把不清楚的点说清楚。" },
      { question: "action item 指？", options: ["待办任务", "咖啡订单", "座位表", "门禁卡"], answer: 0, explain: "会后要完成的事项。" },
      { question: "minutes 在开会后常指？", options: ["分钟数", "会议纪要", "分钟视频", "等待时间"], answer: 1, explain: "meeting minutes。" },
      { question: "Let's take this offline 意思是？", options: ["断网开会", "会后私下讨论", "取消项目", "公开直播"], answer: 1, explain: "不占用大家时间。" },
      { question: "slip 在进度语境下接近？", options: ["摔倒", "延期/进度落后", "滑动工资", "签字"], answer: 1, explain: "the date may slip。" },
      { question: "finalize 表示？", options: ["开始讨论", "最终敲定", "无限延期", "保密"], answer: 1, explain: "确定最终版本。" },
    ],
  }),
  scene({
    slug: "phone-booking",
    title: "电话预约",
    titleEn: "Booking by Phone",
    emoji: "📞",
    place: "Phone call",
    description: "报名字、确认时间、改约取消，听不清时怎么礼貌请对方重复。",
    stage: "B1",
    usefulPhrases: [
      { en: "I'm calling to make a reservation.", zh: "我打电话是想预订。", ipa: "/aɪm ˈkɔːlɪŋ tə meɪk ə ˌrezəˈveɪʃn/" },
      { en: "Could you speak a little more slowly?", zh: "能说慢一点吗？", ipa: "/kəd ju spiːk ə ˈlɪtl mɔː ˈsləʊli/" },
      { en: "Let me confirm: Saturday at 7, for four.", zh: "我确认一下：周六 7 点，四位。", ipa: "/let mi kənˈfɜːm/" },
      { en: "I'd like to reschedule.", zh: "我想改期。", ipa: "/aɪd laɪk tə ˌriːˈskedjuːl/" },
      { en: "Could you spell that, please?", zh: "能拼写一下吗？", ipa: "/kəd ju spel ðæt/" },
      { en: "The line is bad. Could you repeat that?", zh: "信号不好，能再说一遍吗？", ipa: "/ðə laɪn ɪz bæd/" },
    ],
    dialogue: [
      { speaker: "Staff", en: "Good afternoon, Riverside Restaurant. How can I help you?", zh: "下午好，河畔餐厅。有什么可以帮您？", ipa: "/ɡʊd ˌɑːftəˈnuːn/" },
      { speaker: "You", en: "Hi, I'm calling to make a reservation for Saturday.", zh: "你好，我想订周六的位置。", ipa: "/haɪ aɪm ˈkɔːlɪŋ/" },
      { speaker: "Staff", en: "What time and how many people?", zh: "几点，几位？", ipa: "/wɒt taɪm ənd haʊ ˈmeni ˈpiːpl/" },
      { speaker: "You", en: "Seven o'clock, for four. A table by the window if possible.", zh: "七点，四位。如果可以要靠窗。", ipa: "/ˈsevn əˈklɒk fə fɔː/" },
      { speaker: "Staff", en: "The name, please?", zh: "请问贵姓？", ipa: "/ðə neɪm pliːz/" },
      { speaker: "You", en: "Chen. C-H-E-N. Could you speak a little more slowly?", zh: "陈，C-H-E-N。能说慢一点吗？", ipa: "/tʃen siː eɪtʃ iː en/" },
      { speaker: "Staff", en: "Of course. That's Saturday 7 p.m., four people, window table.", zh: "好的。周六晚 7 点，四位，靠窗。", ipa: "/əv kɔːs ðæts ˈsætədeɪ/" },
      { speaker: "You", en: "Let me confirm: Saturday at 7, for four. Could I also leave a phone number?", zh: "我确认：周六 7 点四位。能留个电话吗？", ipa: "/let mi kənˈfɜːm/" },
      { speaker: "Staff", en: "Please. If you need to reschedule, call before 4 p.m.", zh: "请留。若要改期，请在下午 4 点前打来。", ipa: "/pliːz ɪf ju niːd tə ˌriːˈskedjuːl/" },
      { speaker: "You", en: "Got it. Thank you. Goodbye.", zh: "明白了。谢谢，再见。", ipa: "/ɡɒt ɪt θæŋk juː ɡʊdˈbaɪ/" },
    ],
    quizzes: [
      { question: "I'm calling to … 用来？", options: ["说明来电目的", "结束通话", "点餐辣度", "安检"], answer: 0, explain: "电话开头先说来意。" },
      { question: "reschedule 的意思是？", options: ["取消后不再来", "改期", "加菜", "开发票"], answer: 1, explain: "换一个时间。" },
      { question: "Could you spell that 是在请对方？", options: ["说慢点", "按字母拼写", "发邮件", "降价"], answer: 1, explain: "核对姓名地址常用。" },
      { question: "The line is bad 表示？", options: ["队伍很长", "通话信号不好", "线路停运", "账单有误"], answer: 1, explain: "电话听不清。" },
      { question: "Let me confirm 之后通常会？", options: ["重复关键信息", "直接挂断", "开始投诉", "要求升舱"], answer: 0, explain: "避免听错时间人数。" },
      { question: "for four 在订位时指？", options: ["四点钟", "四位客人", "四号桌必须", "四分辣"], answer: 1, explain: "how many people。" },
      { question: "How can I help you? 是？", options: ["客服开场", "安检指令", "登机广播", "医嘱"], answer: 0, explain: "接电话/前台常用。" },
      { question: "repeat that 请对方？", options: ["说慢", "再说一遍", "拼写", "发短信"], answer: 1, explain: "没听清就请 repeat。" },
    ],
  }),
];
